### ISSUE TITLE
NoClassDefFound for EmbeddedBroker with Scala 2.12

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-kafka#1058]
I'm running Spring Kafka 2.2.4 and overriding the dependencies to use Kafka 2.1.1.

Everything is fine using Scala 2.11 but we are now using 2.12 in production (as recommended by Kafka since 2.1.0). Changing my pom to use 2.12 results in the following exception running tests
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedKafka': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class kafka.server.KafkaConfig$
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:405)
	at org.springframework.kafka.test.context.EmbeddedKafkaContextCustomizer.customizeContext(EmbeddedKafkaContextCustomizer.java:109)
	at org.springframework.test.context.support.AbstractContextLoader.customizeContext(AbstractContextLoader.java:187)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:127)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:275)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 33 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class kafka.server.KafkaConfig$
	at kafka.utils.TestUtils$.createBrokerConfig(TestUtils.scala:234)
	at kafka.utils.TestUtils.createBrokerConfig(TestUtils.scala)
	at org.springframework.kafka.test.EmbeddedKafkaBroker.createBrokerProperties(EmbeddedKafkaBroker.java:239)
	at org.springframework.kafka.test.EmbeddedKafkaBroker.afterPropertiesSet(EmbeddedKafkaBroker.java:214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758)
	... 42 more
```

**Comment by garyrussell** [comment]
@manderson23 Did you override all the dependencies as described in [Appendix A: Override Dependencies to use the 2.1.x kafka-clients with an Embedded Broker](https://docs.spring.io/spring-kafka/reference/html/#deps-for-21x)?

I just upgraded the master branch (which uses the 2.2.0 client to scala 2.12) and the full test suite ran without any issues.

**Comment by garyrussell** [comment]
BTW, the [2.1 documentation](https://kafka.apache.org/21/documentation.html) still refers to 2.11; where do you see that recommendation.

**Comment by manderson23** [comment]
@garyrussell I'm overriding the dependencies as documented. 

With 2.11 when I run `mvn dependency:tree` I see the following kafka jars
```
[INFO] +- org.apache.kafka:kafka-clients:jar:2.1.1:compile
[INFO] +- org.springframework.kafka:spring-kafka-test:jar:2.2.4.RELEASE:test
[INFO] +- org.springframework.kafka:spring-kafka:jar:2.2.4.RELEASE:test
[INFO] +- org.apache.kafka:kafka-clients:jar:test:2.1.1:test
[INFO] +- org.apache.kafka:kafka_2.11:jar:2.1.1:test
[INFO] \- org.apache.kafka:kafka_2.11:jar:test:2.1.1:test
````
However, when I switch to 2.12 I see
```
[INFO] +- org.apache.kafka:kafka-clients:jar:2.1.1:compile
[INFO] +- org.springframework.kafka:spring-kafka-test:jar:2.2.4.RELEASE:test
[INFO] |  +- org.apache.kafka:kafka_2.11:jar:2.0.1:test
[INFO] |  \- org.apache.kafka:kafka_2.11:jar:test:2.0.1:test
[INFO] +- org.springframework.kafka:spring-kafka:jar:2.2.4.RELEASE:test
[INFO] +- org.apache.kafka:kafka-clients:jar:test:2.1.1:test
[INFO] +- org.apache.kafka:kafka_2.12:jar:2.1.1:test
[INFO] \- org.apache.kafka:kafka_2.12:jar:test:2.1.1:test
```
where 2.11 jars are included below spring-kafka-test.

If I change the spring-kafka-test dependency to exclude kafka_2.11 then I don't get the exception.

The [downloads](http://kafka.apache.org/downloads.html) pages states from 2.0.1 onwards that 2.12 is recommended if you don't require a specific Scala version.

**Comment by garyrussell** [comment]
Thanks; I updated the docs.
