### ISSUE TITLE
How can i use 'org.springframework.kafka.listener.RecordInterceptor' to intercept a message

### ISSUE THREAD

**Issue by rajeshhereforyou** [spring-projects/spring-kafka#1124]
Hi,

I'm using spring-kafka  2.2.7.RELEASE and trying to intercept a consumer record by defining a custom interceptor class which is implements 'org.springframework.kafka.listener.RecordInterceptor' and overriding the 'intercept' method and defining this custom interceptor as a Component. Now, the 'interceptor' method is not being called when i send a message.

I can't set this custom interceptor class as ConsumerInterceptor by setting   consumer config property ConsumerConfig.'INTERCEPTOR_CLASSES_CONFIG' because it is throwing ClassCastException as shown below. So, I'm not sure how can i make use of this new interface to intercept a record.

> Caused by: java.lang.ClassCastException: class mypackage.kafka.consumer.interceptor.SapphireKafkaConsumerInterceptor
   2019-06-17T13:12:32.03-0400 [APP/PROC/WEB/0] OUT 	at java.lang.Class.asSubclass(Class.java:3404) ~[?:1.8.0_202]
   2019-06-17T13:12:32.03-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.utils.Utils.loadClass(Utils.java:333) ~[kafka-clients-2.0.1.jar!/:?]
   2019-06-17T13:12:32.03-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:322) ~[kafka-clients-2.0.1.jar!/:?]
   2019-06-17T13:12:32.03-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:355) ~[kafka-clients-2.0.1.jar!/:?]
   2019-06-17T13:12:32.03-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:332) ~[kafka-clients-2.0.1.jar!/:?]
   2019-06-17T13:12:32.03-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:319) ~[kafka-clients-2.0.1.jar!/:?]
   2019-06-17T13:12:32.03-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:687) ~[kafka-clients-2.0.1.jar!/:?]
   2019-06-17T13:12:32.03-0400 [APP/PROC/WEB/0] OUT 	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:615) ~[kafka-clients-2.0.1.jar!/:?]
   2019-06-17T13:12:32.03-0400 [APP/PROC/WEB/0] OUT 	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createKafkaConsumer(DefaultKafkaConsumerFactory.java:164) ~[spring-kafka-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
   2019-06-17T13:12:32.03-0400 [APP/PROC/WEB/0] OUT 	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createConsumerWithAdjustedProperties(DefaultKafkaConsumerFactory.java:160) ~[spring-kafka-2.2.7.RELEASE.jar!/:2.2.

**Comment by garyrussell** [comment]
GitHib issues are not for asking questions; they are for reporting bugs or asking for new features.

It doesn't go there; Kafka doesn't know anything about it; it goes on the listener container factory `@Bean`.

**Comment by rajeshhereforyou** [comment]
Thanks for the explanation. I'll check this.
