### ISSUE TITLE
A MimeTypeSerializer to store MimeType as a string in JSON is needed.

### ISSUE THREAD

**Issue by hanishi** [spring-projects/spring-kafka#1129]
**Affects Version(s):**  2.2.4

When a Spring Cloud Stream's `http` Source app writes a `Message<?>` whose `MessageHeaders` includes `List<MediaType>` using kafka-binder to a topic assigned as its `output` destination, it is serialized and stored in it as follows: 

```
accept=[{"type":"text","subtype":"html","parameters":{},"qualityValue":1.0,"wildcardType":false,"wildcardSubtype":false,"charset":null,"concrete":true},{"type":"application","subtype":"xhtml+xml","parameters":{},"qualityValue":1.0,"wildcardType":false,"wildcardSubtype":false,"charset":null,"concrete":true},{"type":"application","subtype":"xml","parameters":{"q":"0.9"},"qualityValue":0.9,"wildcardType":false,"wildcardSubtype":false,"charset":null,"concrete":true},{"type":"image","subtype":"webp","parameters":{},"qualityValue":1.0,"wildcardType":false,"wildcardSubtype":false,"charset":null,"concrete":true},{"type":"image","subtype":"apng","parameters":{},"qualityValue":1.0,"wildcardType":false,"wildcardSubtype":false,"charset":null,"concrete":true},{"type":"*","subtype":"*","parameters":{"q":"0.8"},"qualityValue":0.8,"wildcardType":true,"wildcardSubtype":true,"charset":null,"concrete":false},{"type":"application","subtype":"signed-exchange","parameters":{"v":"b3"},"qualityValue":1.0,"wildcardType":false,"wildcardSubtype":false,"charset":null,"concrete":true}]
```

This record is deserialized as a `java.util.LinkedHashMap` in `MessageHeaders`, which makes the `setHttpHeader` private method of `DefaultHttpHeaderMapper` fail with the following **java.lang.IllegalArgumentException**,  when a receiving app tries to build a `HttpEntity` from a `Message<?>`

```
Caused by: java.lang.IllegalArgumentException: Expected MediaType or String value for 'Accept' header value, but received: class java.util.LinkedHashMap
    at org.springframework.integration.http.support.DefaultHttpHeaderMapper.setHttpHeader(DefaultHttpHeaderMapper.java:593) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.integration.http.support.DefaultHttpHeaderMapper.fromHeaders(DefaultHttpHeaderMapper.java:434) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.integration.http.support.DefaultHttpHeaderMapper.fromHeaders(DefaultHttpHeaderMapper.java:74) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.integration.http.outbound.AbstractHttpRequestExecutingMessageHandler.mapHeaders(AbstractHttpRequestExecutingMessageHandler.java:404) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.integration.http.outbound.AbstractHttpRequestExecutingMessageHandler.createHttpEntityFromPayload(AbstractHttpRequestExecutingMessageHandler.java:373) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.integration.http.outbound.AbstractHttpRequestExecutingMessageHandler.generateHttpRequest(AbstractHttpRequestExecutingMessageHandler.java:363) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.integration.http.outbound.AbstractHttpRequestExecutingMessageHandler.handleRequestMessage(AbstractHttpRequestExecutingMessageHandler.java:287) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123) ~[spring-integration-core-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:162) ~[spring-integration-core-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
    ... 31 common frames omitted
```

There is a need for a `MimeTypeSerializer` to store **MimeType** as a string in the JSON so it is properly handled at a receiving end.

**Comment by artembilan** [comment]
Gitter discussion for more info: https://gitter.im/spring-projects/spring-integration?at=5d0b98dacedb297a8184422a

**Comment by garyrussell** [comment]
This broke backwards compatibility; a 3.0 app can't talk to a 2.1 app because the MimeType is no longer a String.
