### ISSUE TITLE
EmbeddedKafka broken when using placeholder properties for topics

### ISSUE THREAD

**Issue by catchin** [spring-projects/spring-kafka#1144]
**Affects Version(s):** 2.3.0.M3

**Unaffected Version(s):** 2.3.0.M2

When upgrading from spring-kafka-test:2.2.0.M2 to spring-kafka-test:2.2.0.M3, it is no longer possible to use property placeholders for defining topics in `@EmbeddedKafka` annotation.

For example, `@EmbeddedKafka(topics = ["\${some.topic}"])`, stops working. See example here: https://github.com/catchin/spring-embedded-kafka-test

Stack trace: 

	Failed to evaluate condition [org.springframework.kafka.test.condition.EmbeddedKafkaCondition]
	org.junit.jupiter.engine.execution.ConditionEvaluationException: Failed to evaluate condition [org.springframework.kafka.test.condition.EmbeddedKafkaCondition]
		at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluationException(ConditionEvaluator.java:80)
		at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:69)
		at org.junit.jupiter.engine.execution.ConditionEvaluator.lambda$evaluate$0(ConditionEvaluator.java:55)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
		at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
		at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
		at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
		at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
		at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:57)
		at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:171)
		at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:54)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$checkWhetherSkipped$2(NodeTestTask.java:115)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.checkWhetherSkipped(NodeTestTask.java:115)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:77)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
		at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
		at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
		at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102)
		at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82)
		at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78)
		at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
		at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
		at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
		at com.sun.proxy.$Proxy2.stop(Unknown Source)
		at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
		at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
		at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
		at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
		at java.base/java.lang.Thread.run(Thread.java:834)
	Caused by: kafka.common.KafkaException: 
		at org.springframework.kafka.test.EmbeddedKafkaBroker.createTopics(EmbeddedKafkaBroker.java:297)
		at org.springframework.kafka.test.EmbeddedKafkaBroker.lambda$createKafkaTopics$4(EmbeddedKafkaBroker.java:284)
		at org.springframework.kafka.test.EmbeddedKafkaBroker.doWithAdmin(EmbeddedKafkaBroker.java:311)
		at org.springframework.kafka.test.EmbeddedKafkaBroker.createKafkaTopics(EmbeddedKafkaBroker.java:283)
		at org.springframework.kafka.test.EmbeddedKafkaBroker.afterPropertiesSet(EmbeddedKafkaBroker.java:229)
		at org.springframework.kafka.test.condition.EmbeddedKafkaCondition.createBroker(EmbeddedKafkaCondition.java:145)
		at org.springframework.kafka.test.condition.EmbeddedKafkaCondition.evaluateExecutionCondition(EmbeddedKafkaCondition.java:97)
		at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:64)
		... 66 more
	Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidTopicException: Topic name "${some.topic}" is illegal, it contains a character other than ASCII alphanumerics, '.', '_' and '-'
		at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
		at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
		at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:104)
		at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
		at org.springframework.kafka.test.EmbeddedKafkaBroker.createTopics(EmbeddedKafkaBroker.java:294)
		... 73 more
	Caused by: org.apache.kafka.common.errors.InvalidTopicException: Topic name "${some.topic}" is illegal, it contains a character other than ASCII alphanumerics, '.', '_' and '-'

The test runs again when modifying the build.gradle.kts to use `    testImplementation("org.springframework.kafka:spring-kafka-test:2.2.0.M2")`

**Comment by garyrussell** [comment]
I will look at your code, but we have [lots of tests that use placeholders](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/test/java/org/springframework/kafka/annotation/EnableKafkaIntegrationTests.java#L1437).

**Comment by garyrussell** [comment]
Sorry - those tests are in the `@KafkaListener`; I misread your question; I was not aware we supported placeholders there. Investigating...

**Comment by garyrussell** [comment]
So, it doesn't "work" in M2 either; before M3, `@EmbeddedKafa` only creates a broker when there is a Spring test application available, the context customizer adds the bean to the test context.

In M3, we now allow `@EmbeddedKafka` to be used as a stand-alone broker, without a Spring test application context (similar to `@ClassRule` in JUnit4).

With M2, if you change your test to

```
@EmbeddedKafka(topics = ["\${some.topic}"])
@SpringJUnitConfig
class KafkaTest {
    @Test
    fun `it runs`() {

    }
}
```

You will see the same failure with M2.

Without the `@SpringJUnitConfig`, the `@EmbeddedKafka` is simply ignored.

We could add support for placeholders **but only when a Spring test application context is present**.

@artembilan WDYT?

**Comment by artembilan** [comment]
> We could add support for placeholders but only when a Spring test application context is present.

Isn't that exactly what we have here? If we don't have a Spring Application context around, placeholders are not resolved therefore we fail.
We might need just advertise in the Docs that placeholders in those attributes are going to work only if you use `@EmbeddedKafka` in the Spring environment.

Am i missing anything?

**Comment by garyrussell** [comment]
Right; they won't be resolved when there is no Spring context, but they are currently not resolved when there **is** a context.

**Comment by artembilan** [comment]
How is that possible?
See `EmbeddedKafkaContextCustomizer`:
```
String[] topics =
		Arrays.stream(this.embeddedKafka.topics())
					.map(environment::resolvePlaceholders)
					.toArray(String[]::new);
```

and `KafkaStreamsTests` with its:
```
@RunWith(SpringRunner.class)
@DirtiesContext
@TestPropertySource(properties = "streaming.topic.two=streamingTopic2")
@EmbeddedKafka(partitions = 1,
		topics = {
				KafkaStreamsTests.STREAMING_TOPIC1,
				"${streaming.topic.two}",
				KafkaStreamsTests.FOOS },
		brokerProperties = {
				"auto.create.topics.enable=${topics.autoCreate:false}",
				"delete.topic.enable=${topic.delete:true}" },
		brokerPropertiesLocation = "classpath:/${broker.filename:broker}.properties")
public class KafkaStreamsTests {
```

Or do you mean it doesn't work with `@SpringJUnitConfig`?
Don't we still need to add a `@TestPropertySource` there then?

**Comment by garyrussell** [comment]
Not sure, all I can say is the test in my comment above fails with `Topic name "${some.topic}" is illegal,`.

**Comment by garyrussell** [comment]
Not sure, all I can say is the test in my comment above fails with `Topic name "${some.topic}" is illegal,`.

Shouldn't we fail with a resolution failure if there is no property with that name?

**Comment by artembilan** [comment]
> test in my comment above fails with 

Doesn't that `\$` mean do not treat it as property-placeholder?

> Shouldn't we fail with a resolution failure

I think we can't violate here a property-placeholder behavior. If it falls back to the plain value for that syntax, then we should propagate it as is and therefore fail somewhere later.
I mean it works the same way everywhere in Spring, so, why it should not here in Spring Kafka?

**Comment by garyrussell** [comment]
The `\` is a Kotlin escape.

>everywhere in Spring

?

		@KafkaListener(id = "bar", topicPattern = "${topicTwo}")

fails with 

>Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'topicTwo' in value "${topicTwo}"

**Comment by artembilan** [comment]
Who throws that exception?

**Comment by garyrussell** [comment]
```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'topicTwo' in value "${topicTwo}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178) ~[spring-core-5.2.0.M3.jar:5.2.0.M3]
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124) ~[spring-core-5.2.0.M3.jar:5.2.0.M3]
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:237) ~[spring-core-5.2.0.M3.jar:5.2.0.M3]
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:211) ~[spring-core-5.2.0.M3.jar:5.2.0.M3]
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175) ~[spring-context-5.2.0.M2.jar:5.2.0.M2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:851) ~[spring-beans-5.2.0.M3.jar:5.2.0.M3]
	at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor.resolve(KafkaListenerAnnotationBeanPostProcessor.java:744) ~[main/:?]
```

**Comment by artembilan** [comment]
OK. I see:
```
throw new IllegalArgumentException("Could not resolve placeholder '" +
							placeholder + "'" + " in value \"" + value + "\"");
```
- `PropertyPlaceholderHelper`.

So, do you mean our logic in the `EmbeddedKafkaContextCustomizer` is wrong?
May that is what we need to fix...

**Comment by artembilan** [comment]
Anyway it is not going to work when we don't have Spring environment around at all as it is originally reported here.
As you said: it was ignored before without any Kafka in the test.
Now it is going to work without Spring or with Spring when we would like to use property placeholders.

Not sure what else you would like to reconsider here...

**Comment by artembilan** [comment]
> And passes unresolved PH unchanged rather than throwing an exception.

Yeah... And why is that I wonder... Sounds like a request for Spring Core?
I can play with that to make it similar what we have with the `@KafkaListener`

**Comment by garyrussell** [comment]
Don't bother; we can document it.

```java
@EmbeddedKafka(topics = ["\${some.topic}"])
@SpringJUnitConfig
@TestPropertySource(properties = ["some.topic=foo"])
class KafkaTest {
    @Test
    fun `it runs`() {

    }
}
```

works.

**Comment by catchin** [comment]
Indeed, adding `@SpringJUnitConfig` works. 

However, using the standard `@SpringBootTest` configuration fails:

    @SpringBootTest
    @EmbeddedKafka(topics = ["\${some.topic}"])
    class KafkaTest {
        @Test
        fun `it runs`() {
    
        }
    }

Is this intended?

**Comment by garyrussell** [comment]
It should work as long as the property `some.topic` is in one of the property sources visible to the test.

**Comment by garyrussell** [comment]
Yes, it works when you add `some.topic=myTopic` to `application.properties`.

**Comment by catchin** [comment]
@garyrussell  I tried it exactly like above and when adding the property to application.yaml it still does not work. I also another test to verify the property is resolved.

**Comment by catchin** [comment]
@artembilan It does understand the `yaml` extension. This test https://github.com/catchin/spring-embedded-kafka-test/blob/master/src/test/kotlin/com/example/demo/PropertyTest.kt passes.

**Comment by catchin** [comment]
@garyrussell @artembilan 
In my opinion this issue should be reopened. 
The test including `@SpringBootTest` and property in application.yaml fails. See also here: https://travis-ci.org/catchin/spring-embedded-kafka-test

**Comment by catchin** [comment]
I also tried with application.properties with the same error.

Am 27. Juni 2019 18:39:04 MESZ schrieb Artem Bilan <notifications@github.com>:

**Comment by artembilan** [comment]
Hm. I see that `EmbeddedKafkaContextCustomizer` who takes care about property placeholders is invoked only if we have a `@SpringJUnitConfig` alongside with those `@SpringBootTest` and `@EmbeddedKafka`.
Not sure what is wrong just with the `@SpringBootTest`...

**Comment by garyrussell** [comment]
The issue is that the Junit5 `EmbeddedKafkaCondition` uses the presence of a `@SpringJunitConfig` annotation to decide whether to create a stand-alone (not Spring) broker...

```java
		if (element.isPresent() &&
				AnnotatedElementUtils.findMergedAnnotation(element.get(), SpringJUnitConfig.class) == null) {

			EmbeddedKafka embedded = AnnotatedElementUtils.findMergedAnnotation(element.get(), EmbeddedKafka.class);
			// When running in a spring test context, the EmbeddedKafkaContextCustomizer will create the broker.
			if (embedded != null) {
				EmbeddedKafkaBroker broker = getBrokerFromStore(context);
				if (broker == null) {
					broker = createBroker(embedded);
					BROKERS.set(broker);
					getStore(context).put(EMBEDDED_BROKER, broker);
				}
			}
		}
```

We can't test for `@SpringBootTest` since we can't depend on Boot. So maybe we just document that you must use `@SpringJunitCongig` ?

**Comment by garyrussell** [comment]
(Turns out I was still using M2 when I "thought" it was working).

**Comment by artembilan** [comment]
Well, maybe an `@ExtendWith(SpringExtension.class)` to check instead?
It is there on `@SpringBootTest`, too.

**Comment by garyrussell** [comment]
Hmmm - yes; that should work.

**Comment by garyrussell** [comment]
Trying it now...

**Comment by garyrussell** [comment]
@catchin Thanks for your patience and persistence.

This change was needed so we could provide similar capability to JUnit4's `@ClassRule`.

We appreciate users trying milestones so we catch these kind of issues before the release.

Thanks again.

**Comment by catchin** [comment]
Thank you as well! I'm glad I could help.
