### ISSUE TITLE
JsonMappingException thrown when BinderHeaderMapper tries to deserialize a list of values retrieved by key Allow

### ISSUE THREAD

**Issue by hanishi** [spring-projects/spring-kafka#1175]
**Affects Version(s):** 2.2.4

Upon receiving a `Message`, when `BinderHeaderMapper` tries to deserialize a list of values, namely **["GET","HEAD","OPTIONS"]**, retrieved by key named **Allow** from the source Header in its 
```
public void toHeaders(Headers source, final Map<String, Object> headers)
```
method, it raises `com.fasterxml.jackson.databind.JsonMappingException` with message saying,

 **"Type [simple type, class java.lang.Enum] not Java Enum type
 at [Source: (byte[])"["GET","HEAD","OPTIONS"]"; line: 1, column: 1]"**

The key-value pair was sent to the kafka topic as a part of a Message and the `BinderHeaderMapper` received it in a kafka record's `Header`. The key-value pair had been extracted from an `HttpHeaders` in the 
```
public Map<String, Object> toHeaders(HttpHeaders source)
``` 
method of `DefaultHttpHeaderMapper` when this method was invoked in a `WebClient` used in a `Processor` app that received a response from the remote HTTP server.

The Exception and stack trace is as follows: 

```
com.fasterxml.jackson.databind.JsonMappingException: Type [simple type, class java.lang.Enum] not Java Enum type
 at [Source: (byte[])"["GET","HEAD","OPTIONS"]"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:306) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4190) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4009) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3091) ~[jackson-databind-2.9.8.jar!/:2.9.8]
	at org.springframework.cloud.stream.binder.kafka.BinderHeaderMapper.lambda$toHeaders$1(BinderHeaderMapper.java:268) ~[spring-cloud-stream-binder-kafka-2.1.1.RELEASE.jar!/:2.1.1.RELEASE]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.cloud.stream.binder.kafka.BinderHeaderMapper.toHeaders(BinderHeaderMapper.java:251) ~[spring-cloud-stream-binder-kafka-2.1.1.RELEASE.jar!/:2.1.1.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$5.toHeaders(KafkaMessageChannelBinder.java:727) ~[spring-cloud-stream-binder-kafka-2.1.1.RELEASE.jar!/:2.1.1.RELEASE]
	at org.springframework.kafka.support.converter.MessagingMessageConverter.toMessage(MessagingMessageConverter.java:109) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.toMessagingMessage(MessagingMessageListenerAdapter.java:264) ~[spring-kafka-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:420) ~[spring-integration-kafka-3.1.0.RELEASE.jar!/:3.1.0.RELEASE]
```

**Comment by artembilan** [comment]
Hm. Looks like it is just a general `enum` (de)serialization problem in JSON: https://www.baeldung.com/jackson-serialize-enums.
Feels like such a `Set` has to be converted into a `StringUtils.collectionToCommaDelimitedString()`. As well as a single `enum` value. Only the question when and where...
Fortunately `DefaultHttpHeaderMapper` can deal with that comma-delimited string for population.

**Comment by artembilan** [comment]
Closed as `Out-dated`.
Feel free to raise a new one, but rather with newer version of all the dependencies.
Might be even fact that this concern has been fixed somewhere in between.
Doesn't look Spring for Apache Kafka has done anything on the matter even if that `BinderHeaderMapper` is an extension of the `AbstractKafkaHeaderMapper`.
