### ISSUE TITLE
package java.net should be included in the DEFAULT_TRUSTED_PACKAGES

### ISSUE THREAD

**Issue by hanishi** [spring-projects/spring-kafka#1176]
**Affects Version(s):** 2.2.4

The value for the `Location` key is deserialized as `java.net.URI` but since it is not included in the `DEFAULT_TRUSTED_PACKAGES` following exception is thrown when `DefaultHttpHeaderMapper` tries to handle the message received in its `setHttpHeader` method.

```
java.lang.IllegalArgumentException: Expected URI or String value for 'Location' header value, but received: class org.springframework.cloud.stream.binder.kafka.BinderHeaderMapper$NonTrustedHeaderType
	at org.springframework.integration.http.support.DefaultHttpHeaderMapper.setHttpHeader(DefaultHttpHeaderMapper.java:916) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	at org.springframework.integration.http.support.DefaultHttpHeaderMapper.fromHeaders(DefaultHttpHeaderMapper.java:434) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	at org.springframework.integration.http.support.DefaultHttpHeaderMapper.fromHeaders(DefaultHttpHeaderMapper.java:74) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
	at org.springframework.integration.http.inbound.HttpRequestHandlingEndpointSupport.setupResponseAndConvertReply(HttpRequestHandlingEndpointSupport.java:407) ~[spring-integration-http-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]

```

This issue was moved from https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/707

**Comment by garyrussell** [comment]
Cherry-picked to 2.2.x as f1662eb88b0721b2d547bd985a3133ba022c0f1c

**Comment by hanishi** [comment]
👍
