### ISSUE TITLE
Springboot Application run failed.ThreadPoolTaskExecutor,mongo,rabbitmq,tomcat were all closed,but kafka is still alive.

### ISSUE THREAD

**Issue by strugglekian** [spring-projects/spring-kafka#1179]
application.properties

spring.kafka.bootstrap-servers=xxx
spring.kafka.consumer.group-id=xxx
No more setting.

2019-07-23 20:25:35 [org.springframework.context.support.AbstractApplicationContext:554] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.kafka.config.internalKafkaListenerEndpointRegistry'; nested exception is org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
2019-07-23 20:25:35 [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:208] INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
2019-07-23 20:25:35 [org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer:1190] INFO  org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer - Shutdown ignored - container is not active already
2019-07-23 20:25:35 [com.mongodb.diagnostics.logging.SLF4JLogger:71] INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:4}] to mongos-svc:27017 because the pool has been closed.
2019-07-23 20:25:35 [com.mongodb.diagnostics.logging.SLF4JLogger:71] INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:2}] to mongos-svc:27017 because the pool has been closed.
2019-07-23 20:25:35 [org.apache.juli.logging.DirectJDKLog:173] INFO  org.apache.catalina.core.StandardService - Stopping service [Tomcat]
2019-07-23 20:25:35 [org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:142] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-07-23 20:25:35 [org.springframework.boot.SpringApplication:858] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.kafka.config.internalKafkaListenerEndpointRegistry'; nested exception is org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.h3c.iot.IotsdkservermgrApplication.main(IotsdkservermgrApplication.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
2019-07-23 21:04:04 [org.apache.kafka.clients.FetchSessionHandler:383] INFO  org.apache.kafka.clients.FetchSessionHandler - [Consumer clientId=consumer-6, groupId=iotsdkservermgr] Node 0 was unable to process the fetch request with (sessionId=2075377223, epoch=4257): INVALID_FETCH_SESSION_EPOCH.
2019-07-23 21:07:41 [org.apache.kafka.clients.FetchSessionHandler:383] INFO  org.apache.kafka.clients.FetchSessionHandler - [Consumer clientId=consumer-2, groupId=iotsdkservermgr] Node 0 was unable to process the fetch request with (sessionId=609016071, epoch=4700): INVALID_FETCH_SESSION_EPOCH.
2019-07-23 21:20:34 [org.apache.kafka.clients.FetchSessionHandler:383] INFO  org.apache.kafka.clients.FetchSessionHandler - [Consumer clientId=consumer-8, groupId=iotsdkservermgr] Node 1 was unable to process the fetch request with (sessionId=1414506249, epoch=6592): INVALID_FETCH_SESSION_EPOCH.

**Comment by garyrussell** [comment]
It's not clear what you are asking here. Please provide more details about your issue.

The Kafka client is notorious about hanging when it can't talk to the broker.

You can make it more responsive by reducing `max.block.ms`.

**Comment by strugglekian** [comment]
thanks for your reply.I mean when SpringApplication is initializing，there is a TimeoutException here.I thought the java process should be finished.now,because of kafka thread is still alive,the process cannot finish.it not happen every times,i am not sure if this is a issue,maybe I should close this ?

**Comment by strugglekian** [comment]
> It's not clear what you are asking here. Please provide more details about your issue.
> 
> The Kafka client is notorious about hanging when it can't talk to the broker.
> 
> You can make it more responsive by reducing `max.block.ms`.

thanks for your reply.I mean when SpringApplication is initializing，there is a TimeoutException here.I thought the java process should be finished.now,because of kafka thread is still alive,the process cannot finish.it not happen every times,i am not sure if this is a issue,maybe I should close the issue?
