### ISSUE TITLE
Coordinator selected invalid assignment protocol: null 

### ISSUE THREAD

**Issue by sairamlrg** [spring-projects/spring-kafka#1230]
we are using spring-kafka 1.3.9 version and 0.11.0.2 kafka client in our application.
we have observed the **below mentioned error** and got flooded with logs in **crores**.
How can we handle this error , Do we have any **exception handler**  in spring for this ?

In our application, We have spring.kafka.listener.concurrency = 16 and we launch 4 instances of such that. Totally we have 16*4 = 64 consumers with same group id.  We also have 64 partitions in kafka topic.  From logs we have observered that the error is logged only on one consumer repeatedly **consumer -1(thread: 1-c-1)**

We encountered this issue thrice till now. 

Error Log:
----------
java.lang.IllegalStateException: Coordinator selected invalid assignment protocol: null
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:218)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:367)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:316)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:297)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1078)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1043)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:646)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

But we are not able to reproduce the issue again ? 
First would like to know ,what are the possibilities of this error ?
How can we handle this error , Do we have any **exception handler**  in spring for this ?

Please help us on this. Thank you.

**Comment by sairamlrg** [comment]
Thank you for your time @artembilan . I am closing this issue.
