### ISSUE TITLE
WakeupException after calling KafkaListenerEndpointRegistry#stop

### ISSUE THREAD

**Issue by PawelAdamski** [spring-projects/spring-kafka#1247]
My situation is following, I have a Kafka listener which performs long operation. While it is processing a message I'm calling KafkaListenerEndpointRegistry#stop. It correctly waits until the processing is finished and sends acknowledgment but after that WakeupException is thrown.

```
org.apache.kafka.common.errors.WakeupException: null
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:498)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:284)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:218)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:692)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1416)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1377)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.ackCurrent(KafkaMessageListenerContainer.java:1356)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:1257)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1217)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1198)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1118)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:933)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:749)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:698)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Example:**
Put something to the topic and call `KafkaRestController#stop`. 

My Kafka config looks like that:
```
@EnableKafka
@Configuration
public class KafkaConfig {

  @Value(value = "${spring.kafka.bootstrap-servers}")
  private String bootstrapServers;

  @Value(value = "${spring.kafka.consumer.group-id}")
  private String groupId;

  @Bean
  public ProducerFactory<String, PostingEventDTO> producerFactory(ObjectMapper objectMapper) {
    Map<String, Object> producerConfig = Map.of(
        ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
    return new DefaultKafkaProducerFactory<>(producerConfig, new StringSerializer(), new JsonSerializer<>(objectMapper));
  }

  @Bean
  public KafkaTemplate<String, PostingEventDTO> kafkaTemplate(ProducerFactory<String, PostingEventDTO> producerFactory) {
    return new KafkaTemplate<>(producerFactory);
  }

  @Bean
  public ConsumerFactory<String, Event> consumerFactory(ObjectMapper objectMapper) {
    Map<String, Object> consumerConfig = Map.of(
        ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers,
        ConsumerConfig.GROUP_ID_CONFIG, groupId,
        ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false
    );

    return new DefaultKafkaConsumerFactory<>(consumerConfig,
        new ErrorHandlingDeserializer2<>(new StringDeserializer()),
        new ErrorHandlingDeserializer2<>(new CustomKafkaJsonDeserializer<>(Event.class, objectMapper)));
  }

  @Bean
  public ConcurrentKafkaListenerContainerFactory<String, Event> eventsListenerContainerFactory(ObjectMapper objectMapper) {
    ConcurrentKafkaListenerContainerFactory<String, Event> factory = new ConcurrentKafkaListenerContainerFactory<>();
    factory.setConsumerFactory(consumerFactory(objectMapper));
    factory.getContainerProperties().setAckMode(AckMode.RECORD);
    return factory;
  }

}
```

Here is the consumer:
```
public class KafkaConsumer {

  @KafkaListener(topics = "${kafka.topic}", groupId = "${spring.kafka.consumer.group-id}", containerFactory = "eventsListenerContainerFactory")
  public void receive(Event event) throws IOException, InterruptedException {
    log.info("Sleep started");
   TimeUnit.SECONDS.sleep(20l);
    log.info("Sleep finished");
  }

}
```

I use this class to stop/start listeners:
```
@RestController
@RequestMapping("/api/kafka")
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
public class KafkaRestController {

  @Autowired
  private KafkaListenerEndpointRegistry registry;

  @PostMapping(path = {"stop"})
  public void stop() {
    registry.stop(() -> log.info("Processing is finished"));
  }

  @PostMapping(path = {"start"})
  public void start() {
    registry.start();
  }

}
```

**Comment by garyrussell** [comment]
We should only wake the consumer in stop() if it is currently in the `poll()` method.

**Comment by garyrussell** [comment]
It looks like it's somewhat benign and just noise in the log.

I just tested it and the offset was successfully committed before the exception is thrown.

However, commit callbacks and consumer interceptors are not invoked in this case, so it needs to be fixed.
