### ISSUE TITLE
RuntimeExceptions do not cause a reseek and retry as they used to do in previous version

### ISSUE THREAD

**Issue by dimovelev** [spring-projects/spring-kafka#1274]
I upgraded one of our applications to spring boot 2.2 and spring-kafka 2.3.1. We have the following listener:
```
@KafkaListener(...)
public void onMessage(ConsumerRecord<...> record, final Acknowledgment ack) {
        throw new IllegalStateException("retry");
}
```
and the following consumer factory:
```
@Bean(name = "kafkaListenerContainerFactory")
public ConcurrentKafkaListenerContainerFactory kafkaListenerContainerFactory(final ConsumerFactory consumerFactory) {
    final ConcurrentKafkaListenerContainerFactory result = new ConcurrentKafkaListenerContainerFactory();
    result.setConcurrency(1);
    result.setErrorHandler(new SeekToCurrentErrorHandler(-1));
    result.setConsumerFactory(consumerFactory);
    final ContainerProperties containerProperties = result.getContainerProperties();
    containerProperties.setAckOnError(false);
    containerProperties.setAckMode(MANUAL_IMMEDIATE);
    containerProperties.setGroupId(properties.getApplicationName());

    return result;
}
```

With the previous spring-kafka version (2.2.8.RELEASE), this would have caused a re-seek and a retry (in an endless loop if need be).

With the new version the record is acknowledged in kafka and no retry takes place.

I am reporting this as a bug because I expect that the same configuration after the upgrade (despite using deprecated constructor) should still behave the same. We found the issue because we had a test that verified that a retry happens in this scenario but that was kind of lucky on our side.

Our work-around right now is to do this:
```
        final SeekToCurrentErrorHandler errorHandler = new SeekToCurrentErrorHandler( //
            new FixedBackOff(1000L, FixedBackOff.UNLIMITED_ATTEMPTS) //
        );
        errorHandler.setClassifications(Collections.singletonMap(Exception.class, true), true);
```
I am also unsure what the default value in classifications is supposed to do - even if it is `true` the unknown exception (`IllegalStateException`) was not retried.

**Comment by garyrussell** [comment]
The default classifier is this...

```java
	private static BinaryExceptionClassifier configureDefaultClassifier() {
		Map<Class<? extends Throwable>, Boolean> classified = new HashMap<>();
		classified.put(DeserializationException.class, false);
		classified.put(MessageConversionException.class, false);
		classified.put(MethodArgumentResolutionException.class, false);
		classified.put(NoSuchMethodException.class, false);
		classified.put(ClassCastException.class, false);
		return new ExtendedBinaryExceptionClassifier(classified, true);
	}
```

Which means all exceptions except these are retryable so it's not clear why you would see this behavior.

I just tested with `IllegalStateException` and it worked fine.

>With the previous spring-kafka version (2.2.8.RELEASE), this would have caused a re-seek and a retry (in an endless loop if need be).

No; with 2.2.x the error handler would only try 10 times by default; you had to set `maxAttempts` to `-1` for infinite retries.

Please attach a trace log for your test case (as well as the test itself).

**Comment by garyrussell** [comment]
Here's my test app...

```java
@SpringBootApplication
public class Kgh1274Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh1274Application.class, args);
	}

	@KafkaListener(id = "kgh1274", topics = "kgh1274")
	public void listen(String in) {
		System.out.println(in);
		throw new IllegalStateException();
	}

	@Bean
	public SeekToCurrentErrorHandler eh() {
		return new SeekToCurrentErrorHandler();
	}

	@Bean
	public NewTopic topic() {
		return TopicBuilder.name("kgh1274").partitions(1).replicas(1).build();
	}

	@Bean
	public ApplicationRunner runner(KafkaTemplate<String, String> template) {
		return args -> template.send("kgh1274", "foo");
	}

}
```

```
spring.kafka.consumer.auto-offset-reset=earliest
```
and

```
foo
2019-10-18 11:33:51.245  INFO 67143 --- [  kgh1274-0-C-1] o.a.k.clients.consumer.KafkaConsumer     : [Consumer clientId=consumer-1, groupId=kgh1274] Seeking to offset 1 for partition kgh1274-0
2019-10-18 11:33:51.246 ERROR 67143 --- [  kgh1274-0-C-1] essageListenerContainer$ListenerConsumer : Error handler threw an exception

org.springframework.kafka.KafkaException: Seek to current after exception; nested exception is org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void com.example.demo.Kgh1274Application.listen(java.lang.String)' threw exception; nested exception is java.lang.IllegalStateException; nested exception is java.lang.IllegalStateException
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:182) ~[spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:1626) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1546) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1487) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1401) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1165) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:949) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:884) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
Caused by: org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void com.example.demo.Kgh1274Application.listen(java.lang.String)' threw exception; nested exception is java.lang.IllegalStateException; nested exception is java.lang.IllegalStateException
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:1641) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 10 common frames omitted
Caused by: java.lang.IllegalStateException: null
	at com.example.demo.Kgh1274Application.listen(Kgh1274Application.java:24) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:48) ~[spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:304) ~[spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:86) ~[spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:51) ~[spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:1592) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:1575) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1534) [spring-kafka-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 8 common frames omitted
```
x9

and 


>foo
2019-10-18 11:33:54.788 ERROR 67143 --- [  kgh1274-0-C-1] o.s.k.l.SeekToCurrentErrorHandler        : Backoff FixedBackOff{interval=0, currentAttempts=10, maxAttempts=9} exhausted for

**Comment by dimovelev** [comment]
As you can see, we were passing -1 to the constructor which according to javadoc is interpreted as infinity so the number of retries was no limited.

I just reverted to the old Seek configuration and that is the exception:
```
19:06:13,289 ERROR [icm-workorder-status-updated-v1-0-C-1] SeekToCurrentErrorHandler - Backoff none exhausted for ConsumerRecord(topic = icmWorkOrderStatusUpdatedV1, partition = 1, leaderEpoch = 0, offset = 18, CreateTime = 1571418373269, serialized key size = 38, serialized value size = 59, headers = RecordHeaders(headers = [RecordHeader(key = rcid, value = [57, 52, 52, 97, 50, 56, 48, 100, 45, 57, 97, 101, 55, 45, 52, 55, 57, 54, 45, 56, 50, 52, 49, 45, 50, 50, 55, 101, 100, 48, 48, 51, 55, 51, 97, 98]), RecordHeader(key = tenant, value = [120, 120])], isReadOnly = false), key = WO9bf44c8a-b6ce-40f4-9115-a2fd312a3867, value = {"timestamp": 2019-10-18T17:06:13.268Z, "workOrderId": "WO9bf44c8a-b6ce-40f4-9115-a2fd312a3867", "source": "BEAST", "status": "SUCCESS", "message": null, "code": null}) 
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void net.payback.icm.metrics.workorder.kafka.KafkaWorkOrderStatusUpdatedV1Consumer.onWorkOrderStatusUpdatedV1Received(org.apache.kafka.clients.consumer.ConsumerRecord<java.lang.String, net.payback.commonapi.avro.icmworkorderstatusupdatedv1.IcmWorkOrderStatusUpdatedV1>,org.springframework.kafka.support.Acknowledgment)' threw exception; nested exception is java.lang.IllegalStateException: Work-order with id [WO9bf44c8a-b6ce-40f4-9115-a2fd312a3867] not found. Not acknowledging to give the other work-order created consumer time to consume the work-order; nested exception is java.lang.IllegalStateException: Work-order with id [WO9bf44c8a-b6ce-40f4-9115-a2fd312a3867] not found. Not acknowledging to give the other work-order created consumer time to consume the work-order
```

**Comment by garyrussell** [comment]
Ah, right thanks - yes that's a bug the deprecated CTOR should still work as before.

Sorry for the inconvenience.

**Comment by dimovelev** [comment]
Wow, great response time! Thank you for the great work on spring!
