### ISSUE TITLE
"Could not decode json type" exception when a string property has empty value

### ISSUE THREAD

**Issue by mingliangguo** [spring-projects/spring-kafka#1294]
We've started seeing exceptions related to empty string values for kafka headers. It looks like the `DefaultKafkaHeaderMapper` treated the `String` type properties as json and tried to deserialize it as json string and then threw exceptions as it's not a valid json string.

By digging the code, it seems related to the check here: https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java#L296-L298 where for empty string values it will be treated as json type in https://github.com/spring-projects/spring-kafka/blob/0e039f130225293f0ffc15f17d5b3a01bc605e55/spring-kafka/src/main/java/org/springframework/kafka/support/DefaultKafkaHeaderMapper.java#L302 

If I understand the logic correctly, I think we might want to change the check to (which I tested locally and seems having fixed the issue, though I am not sure if it's the right logic for other cases):
```java
		if (String.class.equals(type) && (header.value().length == 0 || header.value()[0] != '"')) {
			headers.put(header.key(), new String(header.value(), getCharset()));
		}
```

Here is a sample stacktrace:

```bash
ERROR [messageListenerContainer-0-C-1] LogAccessor.java:254 - Could not decode json type:  for key: traceId
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.10.0.jar!/:2.10.0]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344) ~[jackson-databind-2.10.0.jar!/:2.10.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189) ~[jackson-databind-2.10.0.jar!/:2.10.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3266) ~[jackson-databind-2.10.0.jar!/:2.10.0]
	at org.springframework.kafka.support.DefaultKafkaHeaderMapper.decodeValue(DefaultKafkaHeaderMapper.java:320) ~[spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.support.DefaultKafkaHeaderMapper.populateJsonValueHeader(DefaultKafkaHeaderMapper.java:302) ~[spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.support.DefaultKafkaHeaderMapper.lambda$toHeaders$2(DefaultKafkaHeaderMapper.java:275) ~[spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.support.DefaultKafkaHeaderMapper$$Lambda$1847.00000000282B3590.accept(Unknown Source) ~[?:?]
	at java.lang.Iterable.forEach(Unknown Source) [?:2.9 (11-06-2018)]
	at org.springframework.kafka.support.DefaultKafkaHeaderMapper.toHeaders(DefaultKafkaHeaderMapper.java:271) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.support.converter.MessagingMessageConverter.toMessage(MessagingMessageConverter.java:110) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.toMessagingMessage(MessagingMessageListenerAdapter.java:285) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:435) [spring-integration-kafka-3.2.0.RELEASE.jar!/:3.2.0.RELEASE]
	at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:417) [spring-integration-kafka-3.2.0.RELEASE.jar!/:3.2.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:1592) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:1575) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1534) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1487) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1401) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1165) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:949) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:884) [spring-kafka-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0]
	at java.lang.Thread.run(Unknown Source) [?:2.9 (11-06-2018)]
```

Please let me know if any additional information is needed. Thanks!

**Comment by garyrussell** [comment]
Yes; thanks; your fix is correct.

**Comment by garyrussell** [comment]
However, see [the documentation](https://docs.spring.io/spring-kafka/docs/2.3.2.RELEASE/reference/html/#headers).

Specifically the notes at the bottom about compatibility with older versions.

>Starting with version 2.3, handling of String-valued headers is simplified. Such headers are no longer JSON encoded, by default (i.e. they do not have enclosing "…​" added). The type is still added to the JSON_TYPES header so the receiving system can convert back to a String (from byte[]). The mapper can handle (decode) headers produced by older versions (it checks for a leading "); in this way an application using 2.3 can consume records from older versions.

>To be compatible with earlier versions, set encodeStrings to true, if records produced by a version using 2.3 might be consumed by applications using earlier versions. When all applications are using 2.3 or higher, you can leave the property at its default value of false.

**Comment by mingliangguo** [comment]
@garyrussell Thanks for the quick fix!! You guys are awesome! Thanks again!

**Comment by garyrussell** [comment]
@mingliangguo Unfortunately, I had just built/released 2.3.2 when this came in. Can you live with your work-around for a while? 

I would expect to release 2.3.3 in mid-December, unless we expedite it.

**Comment by mingliangguo** [comment]
@garyrussell right, I noticed that `2.3.2` has just been released. Those errors are not harmful but polluted our logs. It would be nice if this could be released sooner, if not, we will have to live with it..

**Comment by mingliangguo** [comment]
@garyrussell this is awesome! We really appreciate this! Yes, we do use Spring Boot and are using the latest version, we will figure it out how to pull the build with the fix (if it's not in by default) Thanks again!

**Comment by garyrussell** [comment]
Just override the dependency in your POM; I use a boot app to smoke test new releases.

		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
			<version>2.3.3.RELEASE</version>
		</dependency>

If you use `spring-kafka-test`; you should override its version too.

**Comment by mingliangguo** [comment]
Thanks! I just tested with our services by using `2.3.3.RELEASE` and it works well! (btw, We are using gradle). Thanks again! 👍
