### ISSUE TITLE
NullPointerException in CommitSync class through SeekToCurrentErrorHandler

### ISSUE THREAD

**Issue by justpolidor** [spring-projects/spring-kafka#1309]
**Affects Version(s):** 2.3.3-RELEASE

Hi there, 

when using SeekToCurrentErrorHandler to achieve a DLQ mechanism, I found that there is a NullPointerException after a message fails to process so during a retry from the deadLetterPublishingRecoverer hence the message is never committed to Kafka leading to consume it every time after the application is restarted.

This is the stacktrace:

```
2019-11-13 11:44:57,760 ERROR [org.springframework.kafka.KafkaListenerEndpointContainer#3-0-C-1] o.s.k.l.KafkaMessageListenerContainer$ListenerConsumer: Error handler threw an exception
java.lang.NullPointerException: null
        at org.apache.kafka.common.utils.Time.timer(Time.java:86)
        at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1454)
        at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:209)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:1674)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1591)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1532)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1446)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1196)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:955)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:890)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
```
So I went in debug in the class KafkaConsumer and I found that the timeout parameter here is null:

```
@Override
    public void commitSync(final Map<TopicPartition, OffsetAndMetadata> offsets, final Duration timeout) {
        acquireAndEnsureOpen();
        try {
            maybeThrowInvalidGroupIdException();
            offsets.forEach(this::updateLastSeenEpochIfNewer);
            if (!coordinator.commitOffsetsSync(new HashMap<>(offsets), time.timer(timeout))) {
                throw new TimeoutException("Timeout of " + timeout.toMillis() + "ms expired before successfully " +
                        "committing offsets " + offsets);
            }
        } finally {
            release();
        }
    }
```

At the moment I solved this by setting the SyncCommitTimeout on the containerListenerFactory.

Here is my full Consumer Kafka configuration:

```
@Bean(name = "deadLetterPublishingRecovererForPrizes")
    public DeadLetterPublishingRecoverer deadLetterPublishingRecovererForPrizes(KafkaTemplate<Object, Object> template) {
        return new DeadLetterPublishingRecoverer(template, (context, exception) -> new TopicPartition(prizesTopic.concat(".DLT"), -1));
    }

    @Bean(name = "seekToCurrentErrorHandlerForPrizes")
    public SeekToCurrentErrorHandler seekToCurrentErrorHandlerForPrizes(@Qualifier("deadLetterPublishingRecovererForPrizes") DeadLetterPublishingRecoverer deadLetterPublishingRecoverer) {
        SeekToCurrentErrorHandler seekToCurrentErrorHandler = new SeekToCurrentErrorHandler(deadLetterPublishingRecoverer, new FixedBackOff(3000L, 3));
        seekToCurrentErrorHandler.setCommitRecovered(true);
        Logger.info(KafkaConsumerConfiguration.class, "seekToCurrentErrorHandlerForPrizes", LogSection.of(LogSectionParam.of("isAckAfterHandle", seekToCurrentErrorHandler.isAckAfterHandle())));
        return seekToCurrentErrorHandler;
    }

    @Bean(name = "kafkaListenerForPrizesContainerFactoryDefault")
    public KafkaListenerContainerFactory<?> kafkaListenerForPrizesContainerFactoryDefault(@Qualifier("seekToCurrentErrorHandlerForPrizes") SeekToCurrentErrorHandler seekToCurrentErrorHandler) {
        final ConcurrentKafkaListenerContainerFactory<String, Object> listenerFactory = new ConcurrentKafkaListenerContainerFactory<>();
        listenerFactory.setConsumerFactory(consumerFactory(kafkaConsumerConfigurationPropertiesForPrizes()));
        listenerFactory.setConcurrency(listenerConcurrency);
        listenerFactory.setStatefulRetry(true);
        listenerFactory.setAutoStartup(listenerAutoStartup);
        listenerFactory.getContainerProperties().setSyncCommits(listenerSyncronousCommits);
        listenerFactory.setBatchListener(listenerBatch);
        listenerFactory.getContainerProperties().setSyncCommitTimeout(Duration.ofMillis(5000));
        listenerFactory.getContainerProperties().setAckMode(ContainerProperties.AckMode.valueOf(ackMode));
        listenerFactory.getContainerProperties().setCommitLogLevel(LogIfLevelEnabled.Level.valueOf(listenerCommitLogLevel));
        listenerFactory.setErrorHandler(seekToCurrentErrorHandler);

        return listenerFactory;
    }

protected Map<String, Object> kafkaConsumerConfigurationPropertiesForPrizes() {
        final Map<String, Object> consumerConfigurationProperties = new HashMap<>();
        consumerConfigurationProperties.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
        consumerConfigurationProperties.put(ConsumerConfig.RECONNECT_BACKOFF_MS_CONFIG, reconnectBackoffMs);
        consumerConfigurationProperties.put(ConsumerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG, reconnectBackoffMaxMs);
        consumerConfigurationProperties.put(ConsumerConfig.RETRY_BACKOFF_MS_CONFIG, kafkaRetryBackoffMs);
        consumerConfigurationProperties.put(ConsumerConfig.GROUP_ID_CONFIG, consumerGroupId);
        consumerConfigurationProperties.put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, consumerMaxPollIntervalInMs);
        consumerConfigurationProperties.put(ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG, consumerHeartbeatIntervalInMs);
        consumerConfigurationProperties.put(ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG, consumerFetchMaxWaitInMs);
        consumerConfigurationProperties.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, consumerEnableAutoCommit);
        consumerConfigurationProperties.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, consumerAutoOffsetReset);
        consumerConfigurationProperties.put(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, consumerMaxPollRecords);
        consumerConfigurationProperties.put(JsonDeserializer.TRUSTED_PACKAGES, consumerJsonTrustedPackages);
        consumerConfigurationProperties.put(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, consumerSessionTimeoutInMs);
        consumerConfigurationProperties.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, ErrorHandlingDeserializer2.class);
        consumerConfigurationProperties.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, ErrorHandlingDeserializer2.class);
        consumerConfigurationProperties.put(ErrorHandlingDeserializer2.KEY_DESERIALIZER_CLASS, StringDeserializer.class);
        consumerConfigurationProperties.put(ErrorHandlingDeserializer2.VALUE_DESERIALIZER_CLASS, JsonDeserializer.class);
        return consumerConfigurationProperties;
    }

    protected ConsumerFactory<String, Object> consumerFactory(Map<String, Object> properties) {
        return new DefaultKafkaConsumerFactory<>(properties);
    }
```

**Comment by garyrussell** [comment]
Thanks; we need to move the code (currently in the container) that falls back to a default when `null`.

**Comment by garyrussell** [comment]
Strange; I can't reproduce the issue; we already have this code in the listener container...

```java
if (this.containerProperties.getSyncCommitTimeout() == null) {
	// update the property so we can use it directly from code elsewhere
	this.containerProperties.setSyncCommitTimeout(this.syncCommitTimeout);
}
```

It's in the constructor of the listener consumer so I can't see how this can happen.

I am still investigating, but if you have a small sample app that exhibits this behavior that would help.

**Comment by garyrussell** [comment]
Never mind; I found it - the container passed in is the outer container, which has not had it's copy of the properties updated.
