### ISSUE TITLE
【Enhancement】start ConcurrentMessageListenerContainer in a seperated thread and keep retrying.

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [spring-projects/spring-kafka#1313]
**Affects Version(s):** 2.2.7.RELEASE

Currently if network between application and brokers are down, the whole application wont start. But in our case most of our service didnt depend on kafka messages and those depend on kafka are okay to work with stale state as long as when network are fixed they will receive missing messages.

```
2019-11-14 10:43:40.219 ERROR 60048 --- [           main] o.s.b.SpringApplication                  : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.kafka.config.internalKafkaListenerEndpointRegistry'; nested exception is org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at com.huawei.ivcs.vehicle.VehicleServiceMain.main(VehicleServiceMain.java:40) [classes/:?]
Caused by: org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata
```

**Comment by garyrussell** [comment]
Please don't truncate stack traces when reporting problems; the full stack trace is always required.

Set the container property `missingTopicsFatal` to `false`.

We have been considering making this `false` by default because it seems to affect a lot of users.

Since Kafka is a high-availability platform, we did not consider that so many users would start apps with the broker(s) not running.

**Comment by Nick-The-Uncharted** [comment]
@garyrussell Thank you for your reply and it works, but it wasnt me whole truncated stack trace, its org.apache.kafka.clients.consumer.internals.Fetcher#getTopicMetadata eat the stacks.

**Comment by garyrussell** [comment]
@Nick-The-Uncharted Sorry about that - you'd be surprised how many people think they are doing a favor by "shortening" a long stack trace 😦 

Glad it worked for you.

**Comment by Nick-The-Uncharted** [comment]
Lol，I can feel your pain. Our tester rarely send me a complete stack trace when error occurs. No matter how many times I told them to do that.



发自我的iPhone


------------------ Original ------------------
