### ISSUE TITLE
EmbeddedKafka - multiple embedded topics

### ISSUE THREAD

**Issue by DawidSwinoga** [spring-projects/spring-kafka#1352]
Hi,

I added two topics to EmbeddedKafka annotation in this test https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/master/producer_kafka/src/test/java/com/example/BaseClass.java.

```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@AutoConfigureMessageVerifier
@EmbeddedKafka(topics = {"topic1", "topic2"}, partitions = 1)
@ActiveProfiles("test")
public abstract class BaseClass {
```

After adding, I get the following error during startup:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.contract.verifier.messaging.MessageVerifier]: Factory method 'contractVerifierKafkaMessageExchange' threw exception; nested exception is org.opentest4j.AssertionFailedError: [Failed to be assigned partitions from the embedded topics] 
Expecting:
 <false>
to be equal to:
 <true>
but was not.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 43 common frames omitted
Caused by: org.opentest4j.AssertionFailedError: [Failed to be assigned partitions from the embedded topics] 
Expecting:
 <false>
to be equal to:
 <true>
```

Previous logs:
```
2020-01-14 15:37:17.769  INFO 10767 --- [           main] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-2, groupId=groupId] (Re-)joining group
2020-01-14 15:37:17.770  INFO 10767 --- [quest-handler-1] k.coordinator.group.GroupCoordinator     : [GroupCoordinator 0]: Preparing to rebalance group groupId in state PreparingRebalance with old generation 1 (__consumer_offsets-3) (reason: Adding new member consumer-2-830f17be-477e-4fab-8fa0-d8b394a745c9 with group instanceid None)
2020-01-14 15:37:20.790  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:37:21.085  INFO 10767 --- [er-event-thread] kafka.controller.KafkaController         : [Controller id=0] Processing automatic preferred replica leader election
2020-01-14 15:37:23.806  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:37:26.821  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:37:29.834  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:37:32.857  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:37:35.872  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:37:38.885  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:37:41.899  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:37:44.912  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:37:47.924  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:37:50.938  INFO 10767 --- [hread | groupId] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=groupId] Attempt to heartbeat failed since group is rebalancing
2020-01-14 15:38:18.080  WARN 10767 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contractVerifierKafkaMessageExchange' defined in class path resource [org/springframework/cloud/contract/verifier/messaging/kafka/ContractVerifierKafkaConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.contract.verifier.messaging.MessageVerifier]: Factory method 'contractVerifierKafkaMessageExchange' threw exception; nested exception is org.opentest4j.AssertionFailedError: [Failed to be assigned partitions from the embedded topics] 
Expecting:
 <false>
to be equal to:
 <true>
but was not.
```

This method is used to initialize consumer:
ContractVerifierKafkaStubMessagesInitializer.prepareListener

```
private Consumer prepareListener(EmbeddedKafkaBroker broker, String destination, KafkaProperties kafkaProperties) {
        Map<String, Object> consumerProperties = KafkaTestUtils.consumerProps(kafkaProperties.getConsumer().getGroupId(), "false", broker);
        consumerProperties.put("auto.offset.reset", "earliest");
        DefaultKafkaConsumerFactory<String, String> consumerFactory = new DefaultKafkaConsumerFactory(consumerProperties);
        Consumer<String, String> consumer = consumerFactory.createConsumer();
        broker.consumeFromAnEmbeddedTopic(consumer, destination);
        if (log.isDebugEnabled()) {
            log.debug("Prepared consumer for destination [" + destination + "]");
        }

        return consumer;
    }
```

In EmbeddedKafkaBroker class in method consumeFromEmbeddedTopics "onPartitionsAssigned" listener is never called for second topic to consume (topic2).

```
public void consumeFromEmbeddedTopics(Consumer<?, ?> consumer, String... topicsToConsume) {
		HashSet<String> diff = new HashSet<>(Arrays.asList(topicsToConsume));
		diff.removeAll(new HashSet<>(this.topics));
		assertThat(this.topics)
				.as("topic(s):'" + diff + "' are not in embedded topic list")
				.containsAll(new HashSet<>(Arrays.asList(topicsToConsume)));
		final AtomicBoolean assigned = new AtomicBoolean();
		consumer.subscribe(Arrays.asList(topicsToConsume), new ConsumerRebalanceListener() {

			@Override
			public void onPartitionsRevoked(Collection<TopicPartition> partitions) {
			}

			@Override
			public void onPartitionsAssigned(Collection<TopicPartition> partitions) {
				assigned.set(true);  // <----- it is never called for second topic (topic2) 
				logger.debug(() -> "partitions assigned: " + partitions);
			}

		});
		ConsumerRecords<?, ?> records = null;
		int n = 0;
		while (!assigned.get() && n++ < 600) { // NOSONAR magic #
			records = consumer.poll(Duration.ofMillis(100)); // force assignment NOSONAR magic #
		}
		if (records != null && records.count() > 0) {
			final ConsumerRecords<?, ?> theRecords = records;
			logger.debug(() -> "Records received on initial poll for assignment; re-seeking to beginning; "
					+ theRecords.partitions().stream()
					.flatMap(p -> theRecords.records(p).stream())
					// map to same format as send metadata toString()
					.map(r -> r.topic() + "-" + r.partition() + "@" + r.offset())
					.collect(Collectors.toList()));
			consumer.seekToBeginning(records.partitions());
		}
		assertThat(assigned.get())
				.as("Failed to be assigned partitions from the embedded topics")
				.isTrue();
		logger.debug("Subscription Initiated");
	}
```

**Comment by garyrussell** [comment]
Please don't use GitHub issues to ask questions; they are for reporting bugs and asking for new features.

Since you only have one partition, you can only have one consumer, unless you put the second consumer in a different `group.id`.

**Comment by artembilan** [comment]
Because you call `consumeFromEmbeddedTopics(Consumer<?, ?> consumer, String... topicsToConsume)` only with a single destination:
```
broker.consumeFromAnEmbeddedTopic(consumer, destination);
```

How that ` prepareListener(EmbeddedKafkaBroker broker, String destination, KafkaProperties kafkaProperties)` is called by the way?

More over it looks like a [Spring Cloud Contract](https://spring.io/projects/spring-cloud-contract) question than Spring for Apache Kafka...

**Comment by DawidSwinoga** [comment]
@garyrussell 
I have one partition per topic. Sa I should be able to create one consumer for topic1 and one consumer for topic2.

@artembilan 
The destinations are different. One of them is topic1 another is topic2.

prepareListener is called once per available topic at EmbeddedKafkaBroker.
```
    public Map<String, Consumer> initialize(EmbeddedKafkaBroker broker, KafkaProperties kafkaProperties) {
        Map<String, Consumer> map = new HashMap();
        Iterator var4 = broker.getTopics().iterator();

        while(var4.hasNext()) {
            String topic = (String)var4.next();
            map.put(topic, this.prepareListener(broker, topic, kafkaProperties));
        }

        return map;
    }
```

**Comment by artembilan** [comment]
> once per available topic

That's something wrong. When we have designed `@KafkaListener` for multi-topics, we definitely wanted to have a single `Consumer` for all the topics.
I think that ` initialize()` logic is wrong. You should call `prepareListener()` only once for all the topics configured on the `@KafkaListener`.
When you have several consumers in the same group, there is really no guarantee that all of them are going to be assigned with some partitions. Therefore a chance to have `onPartitionsAssigned()` not to be called.

**Comment by garyrussell** [comment]
Using the same group causes an unnecessary rebalance on the first consumer. I have seen problems and delays using the same group for different topics. It is easier and more reliable to use discrete groups for such tests.

**Comment by garyrussell** [comment]
Closing due to inactivity.
