### ISSUE TITLE
Meta-Annotation support at class level for KafkaListener

### ISSUE THREAD

**Issue by adnanhb** [spring-projects/spring-kafka#1487]
I have a Meta-Annotation for KafkaListener defined at the class level. I have annotated the handler method with @KafkaHandler annotation. The code is roughly like this:

```
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.ANNOTATION_TYPE})
@KafkaListener
public @interface MyKafkaListener {

    String cluster();

    @AliasFor(annotation = KafkaListener.class, attribute = "id")
    String id() default "";

    String containerFactory() default "";

    @AliasFor(annotation = KafkaListener.class, attribute = "topics")
    String[] topics() default {}
```

```@Component
@MyKafkaListener(cluster = "abc", topics = "my-topic", groupId = "my-consumer-group")

public class MyListener {
    @KafkaHandler
    public void listen(String message) {
        System.out.println("MESSAGE: " + message);
    }
```

This code results in an exception:
```java.lang.IllegalStateException: topics, topicPattern, or topicPartitions must be provided
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.<init>(AbstractMessageListenerContainer.java:138)
	at org.springframework.kafka.listener.ConcurrentMessageListenerContainer.<init>(ConcurrentMessageListenerContainer.java:71)
```

I see a similar issue was raised but it was for defining Meta-Annotation at the method level. And the issue was subsequently fixed.
https://github.com/spring-projects/spring-kafka/issues/919

I have the above meta annotation working at the method level but not at the class level. Is that something not supported in spring kafka?

**Affects Version(s):** 2.2.6

**Comment by garyrussell** [comment]
This is a bug; it should work at the class level too.
