### ISSUE TITLE
DeadLetterPublishingRecoverer fails with NPE that causes infinite loop when message value is null

### ISSUE THREAD

**Issue by joenmoreno** [spring-projects/spring-kafka#1494]
Affects Version(s): 2.5.0.RELEASE

🐞 Bug report
When a message is sent to a topic with the value as null, `DeadLetterPublishingRecoverer` fails with NPE and causes an infinite loop. 

What I noticed from the stacktrace is that `DeadLetterPublishingRecoverer` assumes that value from the record is NOT null. Specifically, from the method below where it tries to find the class of the value:
```
	private KafkaOperations<Object, Object> findTemplateForValue(Object value) {
		if (this.template != null) {
			return this.template;
		}
		Optional<Class<?>> key = this.templates.keySet()
			.stream()
			.filter((k) -> k.isAssignableFrom(value.getClass()))
			.findFirst();
		if (key.isPresent()) {
			return (KafkaOperations<Object, Object>) this.templates.get(key.get());
		}
		LOGGER.warn(() -> "Failed to find a template for " + value.getClass() + " attempting to use the last entry");
		return (KafkaOperations<Object, Object>) this.templates.values()
				.stream()
				.reduce((first,  second) -> second)
				.get();
	}

```

Here is my `kafkacat` script I used to send a null value to the topic:

```
topic="my.topic"
echo 'abc:' | \
kafkacat \
    -P \
    -b localhost:9092 \
    -t ${topic} \
    -Z \
    -K:
```

Here is my configuration (in Groovy)
```
    @Bean
    DeadLetterPublishingRecoverer deadLetterPublishingRecoverer(KafkaTemplate<String, byte[]> bytArrayTemplate, KafkaTemplate<String, MyBean> myBeanKafkaTemplate) {
        return new DeadLetterPublishingRecoverer([
                (byte[].class)                    : bytArrayTemplate,
                (MyBean)                  : myBeanKafkaTemplate,
        ])
    }

    @Bean
    Deserializer<MyBean> myBeanDeserializer(ObjectMapper objectMapper) {
        return new JsonDeserializer<MyBean>(MyBean, objectMapper)
    }

    @Bean
    ConsumerFactory<String, MyBean> myBeanConsumerFactory(Deserializer<MyBean> deserializer) {
        ErrorHandlingDeserializer<MyBean> errorHandlingDeserializer = new ErrorHandlingDeserializer<>(deserializer)
        return new DefaultKafkaConsumerFactory<String, MyBean>(
                consumerConfigs,
                new StringDeserializer(),
                errorHandlingDeserializer
        )
    }

    @Bean
    ConcurrentKafkaListenerContainerFactory<String, MyBean> myBeanKafkaListenerContainerFactory(
            DeadLetterPublishingRecoverer deadLetterPublishingRecoverer,
            ConsumerFactory<String, MyBean> kafkaConsumerFactory) {

        ConcurrentKafkaListenerContainerFactory<String, MyBean> factory = new ConcurrentKafkaListenerContainerFactory<>()
        factory.getContainerProperties().setAckMode(ContainerProperties.AckMode.RECORD)
        factory.setErrorHandler(new SeekToCurrentErrorHandler(deadLetterPublishingRecoverer, new FixedBackOff(1000l, 2l)))
        factory.setConsumerFactory(kafkaConsumerFactory)
        return factory
    }
```

And here is the stacktrace that repeats infinitely:
```
2020-05-27 15:44:34 - [/] ERROR [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] o.s.k.l.SeekToCurrentErrorHandler - Failed to determine if this record (ConsumerRecord(topic = ws.gap.policy, partition = 0, leaderEpoch = 18, offset = 338, CreateTime = 1590609319152, serialized key size = -1, serialized value size = 4, headers = RecordHeaders(headers = [RecordHeader(key = kafka_correlationId, value = [101, 97, 98, 98, 97, 53, 48, 100, 100, 102, 102, 56, 99, 49, 51, 100])], isReadOnly = false), key = null, value = null)) should be recovererd, including in seeks
java.lang.NullPointerException: null
	at org.springframework.kafka.listener.DeadLetterPublishingRecoverer.lambda$findTemplateForValue$4(DeadLetterPublishingRecoverer.java:192) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[na:na]
	at org.springframework.kafka.listener.DeadLetterPublishingRecoverer.findTemplateForValue(DeadLetterPublishingRecoverer.java:193) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.DeadLetterPublishingRecoverer.accept(DeadLetterPublishingRecoverer.java:173) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.DeadLetterPublishingRecoverer.accept(DeadLetterPublishingRecoverer.java:53) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.FailedRecordTracker.skip(FailedRecordTracker.java:106) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.SeekUtils.lambda$doSeeks$2(SeekUtils.java:84) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
	at org.springframework.kafka.listener.SeekUtils.doSeeks(SeekUtils.java:81) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:156) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:103) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:1867) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1773) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1701) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1599) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1330) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1062) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:970) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2020-05-27 15:44:34 - [/] INFO  [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] o.a.k.c.c.KafkaConsumer - [Consumer clientId=consumer-comp-policy-acl-gsap-1, groupId=comp-policy-acl-gsap] Seeking to offset 338 for partition ws.gap.policy-0
2020-05-27 15:44:34 - [/] ERROR [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] o.s.k.l.KafkaMessageListenerContainer$ListenerConsumer - Error handler threw an exception
org.springframework.kafka.KafkaException: Seek to current after exception; nested exception is org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void com.mutualofomaha.gifs.policy.comppolicyaclgsap.policy.kafka.PolicyUpsertConsumer.upsertPolicy(org.apache.kafka.clients.consumer.ConsumerRecord<java.lang.String, com.mutualofomaha.gap.api.common.viewbean.agreement.PolicyViewBean>)' threw exception; nested exception is java.lang.NullPointerException: Cannot get property 'agreementRequests' on null object; nested exception is java.lang.NullPointerException: Cannot get property 'agreementRequests' on null object
	at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:157) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:103) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:1867) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1773) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1701) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1599) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1330) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1062) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:970) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void com.mutualofomaha.gifs.policy.comppolicyaclgsap.policy.kafka.PolicyUpsertConsumer.upsertPolicy(org.apache.kafka.clients.consumer.ConsumerRecord<java.lang.String, com.mutualofomaha.gap.api.common.viewbean.agreement.PolicyViewBean>)' threw exception; nested exception is java.lang.NullPointerException: Cannot get property 'agreementRequests' on null object; nested exception is java.lang.NullPointerException: Cannot get property 'agreementRequests' on null object
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:1879) ~[spring-kafka-2.5.0.RELEASE.jar!/:2.5.0.RELEASE]
	... 10 common frames omitted

```

**Comment by garyrussell** [comment]
This is clearly a bug, but I am curious as to why a tombstone record (`null` value) would end up going to the error handler.

**Comment by joenmoreno** [comment]
> This is clearly a bug, but I am curious as to why a tombstone record (`null` value) would end up going to the error handler.

First of all, thanks for the quick response. To answer your question, it's because the consumer itself throws an exception when it tried to process the message.

```
    @KafkaListener(topics = "my.topic", containerFactory = 'myBeanKafkaListenerContainerFactory')
    void upsertPolicy(ConsumerRecord<String, MyBean> record) {
        .....
        methodCallThatCallsAnException(record.value())
        ....
    }
```
