### ISSUE TITLE
Spring boot 2.3.0.RELEASE did not work with spring-kafka 2.5.0 on java 11

### ISSUE THREAD

**Issue by deleSerna** [spring-projects/spring-kafka#1537]
Hi, 

 I was using a sample **spring boot (2.3.0.RELEASE ) kafka (2.5.0) sample application** with **java 11** and it throwed following exception
Caused by: java.lang.ClassNotFoundException: org.springframework.kafka.listener.RecordInterceptor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]

Then I changed  s**pring-kafka to 2.3.1.RELEASE** and it worked. But according to the page **https://spring.io/projects/spring-kafka#overview** Spring boot 2.3.0.RELEASE must work with spring-kafka 2.5.0

Please see my pom.xml file

```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.0.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>kafkademo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>kafkademo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
				<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
<dependency>
    <groupId>org.springframework.kafka</groupId>
    <artifactId>spring-kafka</artifactId>
    <version>2.3.1.RELEASE</version>
</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>


```

my **module-info.java** file

```
open module kafkademo {
	requires spring.boot.autoconfigure;
	requires spring.context;
	requires spring.boot;
	requires spring.web;
	requires spring.core;
	requires spring.beans;
	requires org.slf4j;
	requires java.net.http;
	requires spring.kafka;
	requires kafka.clients;
	requires java.instrument;
	requires spring.messaging;
}

```

Please let me know what am I doing wrong with Spring boot 2.3.0.RELEASE , spring-kafka 2.5.0 on  java 11

**Comment by garyrussell** [comment]
There is something very odd with your situation; spring-kafka 2.3 will not work with Boot 2.3.

Perhaps your 2.5.0 jar is corrupted.

Try using Boot 2.3.1, which will bring in spring-kafka 2.5.2.

If that doesn't work, please provide a small project that exhibits this behavior. I have many, many Spring Boot 2.3 apps working with spring-kafka 2.5.

**Comment by deleSerna** [comment]
@garyrussell  Something is very odd. Now it does not work with spring-kafka 2.3 spring  Boot 2.3. Even Spring boot **2.3.1** is **not working** with **spring-kafka 2.5.2**. I think it has something to do with java 11. My code is at  **https://github.com/deleSerna/springbootkafkademo**

Current error is 
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.kafka.KafkaAnnotationDrivenConfiguration': Unexpected exception during bean creation; nested exception is java.lang.TypeNotPresentException: Type org.springframework.kafka.listener.RecordInterceptor not present
	at spring.beans@5.2.7.RELEASE/org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:530) ~[spring-beans-5.2.7.RELEASE.jar:na]
	at spring.beans@5.2.7.RELEASE/org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.7.RELEASE.jar:na]
	at spring.beans@5.2.7.RELEASE/org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.7.RELEASE.jar:na]
	at spring.beans@5.2.7.RELEASE/org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.7.RELEASE.jar:na]
	at spring.beans@5.2.7.RELEASE/org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.7.RELEASE.jar:na]
	at spring.beans@5.2.7.RELEASE/org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893) ~[spring-beans-5.2.7.RELEASE.jar:na]
	at spring.context@5.2.7.RELEASE/org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.7.RELEASE.jar:na]
	at spring.context@5.2.7.RELEASE/org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.7.RELEASE.jar:na]
	at spring.boot@2.3.1.RELEASE/org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.1.RELEASE.jar:na]
	at spring.boot@2.3.1.RELEASE/org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.1.RELEASE.jar:na]
	at spring.boot@2.3.1.RELEASE/org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.1.RELEASE.jar:na]
	at spring.boot@2.3.1.RELEASE/org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.1.RELEASE.jar:na]
	at spring.boot@2.3.1.RELEASE/org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.1.RELEASE.jar:na]
	at spring.boot@2.3.1.RELEASE/org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.1.RELEASE.jar:na]
	at spring.boot@2.3.1.RELEASE/org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.1.RELEASE.jar:na]
	at kafkademo/com.example.demo.KafkademoApplication.main(KafkademoApplication.java:12) ~[classes/:na]
Caused by: java.lang.TypeNotPresentException: Type org.springframework.kafka.listener.RecordInterceptor not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[na:na]
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[na:na]
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[na:na]
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:na]
	at java.base/sun.reflect.generics.repository.ConstructorRepository.computeParameterTypes(ConstructorRepository.java:111) ~[na:na]
	at java.base/sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:87) ~[na:na]
	at java.base/java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:279) ~[na:na]
	at java.base/java.lang.reflect.Constructor.getGenericParameterTypes(Constructor.java:281) ~[na:na]
	at spring.core@5.2.7.RELEASE/org.springframework.core.MethodParameter.getGenericParameterType(MethodParameter.java:513) ~[spring-core-5.2.7.RELEASE.jar:na]
	at spring.core@5.2.7.RELEASE/org.springframewor
```

**Comment by deleSerna** [comment]
@garyrussell I tried  springboot **2.1.5.RELEASE** and spring-kafka**2.2.6** and it worked with java 11.
I updated the pom.xml and module-info.java here **https://github.com/deleSerna/springbootkafkademo**
I hope that you could shed more light into the issue Thanks

**Comment by garyrussell** [comment]
The problem is your `module-info.java`. I can't even get it to compile with that there.

Spring uses automatic modules...

```
Manifest-Version: 1.0
Implementation-Title: spring-kafka
Automatic-Module-Name: spring.kafka
Implementation-Version: 2.5.2.RELEASE
Implementation-Vendor-Id: org.springframework.kafka
Created-By: JDK 1.8.0_232 (Oracle Corporation)
Implementation-URL: https://github.com/spring-projects/spring-kafka
Implementation-Vendor: Pivotal Software, Inc.
```

**Comment by deleSerna** [comment]
@garyrussell  May be issue due to maven version you have?
I added a docker file  to the project [](https://github.com/deleSerna/springbootkafkademo/blob/master/Dockerfile)
Then I built the docker image and run it locally
**docker build -t kafkademo:v1 --rm=true .
docker run  -p 9000:9000 -name kafkademo kafkademo:v1**

Then it started fine
```

2020-07-20 16:12:23.135  INFO 19 --- [           main] com.example.demo.KafkademoApplication    : Starting KafkademoApplication on 192e5a063868 with PID 19 (/usr/src/app/target/classes started by root in /usr/src/app)
2020-07-20 16:12:23.143  INFO 19 --- [           main] com.example.demo.KafkademoApplication    : No active profile set, falling back to default profiles: default
2020-07-20 16:12:24.439  INFO 19 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.kafka.annotation.KafkaBootstrapConfiguration' of type [org.springframework.kafka.annotation.KafkaBootstrapConfiguration$$EnhancerBySpringCGLIB$$ef34607c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-20 16:12:24.925  INFO 19 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9000 (http)
2020-07-20 16:12:25.001  INFO 19 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-07-20 16:12:25.002  INFO 19 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.19]
2020-07-20 16:12:25.153  INFO 19 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-07-20 16:12:25.153  INFO 19 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1911 ms
2020-07-20 16:12:25.573  INFO 19 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-07-20 16:12:26.006  INFO 19 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9000 (http) with context path ''
2020-07-20 16:12:26.014  INFO 19 --- [           main] com.example.demo.KafkademoApplication    : Started KafkademoApplication in 3.764 seconds (JVM running for 9.729)
2020-07-20 16:12:39.077  INFO 19 --- [nio-9000-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-07-20 16:12:39.079  INFO 19 --- [nio-9000-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-07-20 16:12:39.093  INFO 19 --- [nio-9000-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 14 ms
2020-07-20 16:12:39.155  INFO 19 --- [nio-9000-exec-2] producer.Producer                        : $$ -> Producing message --> Hello from G
```

**Comment by garyrussell** [comment]
Regardless; try removing the module-info.java - I believe that's the root cause (but I am no expert on Java modules).
