### ISSUE TITLE
KafkaListeners with defined partition number is not working together with listeners with defined topic name

### ISSUE THREAD

**Issue by RuslanHryn** [spring-projects/spring-kafka#1583]
### Description
The issue occurs when the app has listeners with specific partitions. 
For example
` @KafkaListener(topicPartitions = @TopicPartition(topic = "TestTopic", partitions = "0"))`

Also, there are other listeners which don't specified partition. They just have the name of the topic. 
From example
`@KafkaListener(topics = "AnotherTopic")`

When we send a message to KafkaListener with a specific partition. The listener received this message successfully.
But the listener can't commit offset after processing the record.

We get the following error in logs:
<pre><code> 
java.lang.IllegalStateException: This error handler cannot process 'org.apache.kafka.clients.consumer.CommitFailedException's; no record information is available
	at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:151) ~[spring-kafka-2.5.5.RELEASE.jar:2.5.5.RELEASE]
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:103) ~[spring-kafka-2.5.5.RELEASE.jar:2.5.5.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.handleConsumerException(KafkaMessageListenerContainer.java:1265) [spring-kafka-2.5.5.RELEASE.jar:2.5.5.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1022) [spring-kafka-2.5.5.RELEASE.jar:2.5.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_265]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_265]
Caused by: org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:1213) ~[kafka-clients-2.5.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:1140) ~[kafka-clients-2.5.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:1096) ~[kafka-clients-2.5.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:1076) ~[kafka-clients-2.5.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:204) ~[kafka-clients-2.5.1.jar:na]
</code></pre>

### App to reproduce the issue
Please check out the simple app to reproduce this issue https://github.com/RuslanHryn/issue-kafka-partition-listener
You need to run the test class `DemoApplicationTests`. After that, you will see the exception in logs.

**Comment by garyrussell** [comment]
You should use a different group for the listener that is using group management (automatic partition assignment).

You can't use the same group in this context; it's advisable to not use the same group across listeners at all.

```java
@Component
@Slf4j
public class TestKafkaListener {

    @KafkaListener(topicPartitions = @TopicPartition(topic = "TestTopic", partitions = "0"))
    public void handleFirstPartition(String message) {
        log.info("received partition 0: " + message);
    }

    @KafkaListener(topicPartitions = @TopicPartition(topic = "TestTopic", partitions = "1"))
    public void handleSecondPartition(String message) {
        log.info("received partition 1: " + message);
    }

    @KafkaListener(topics = "AnotherTopic", groupId = "autoAssign)
    public void handleAnotherTopic(String message) {
        log.info("received AnotherTopic: " + message);
    }
}
```

If you have multiple llisteners with automatic assignment, I recommend using a different group for each. Otherwise a rebalance on one topic will cause an unnecessary rebalance on the other.

**Comment by RuslanHryn** [comment]
Thank you!
Another group id fixed this issue.
