### ISSUE TITLE
IllegalArgumentException: Payload must not be null

### ISSUE THREAD

**Issue by daroo** [spring-projects/spring-kafka#160]
Current implementation (1.0.2.RELEASE) of `KafkaListener` doesn't handle messages with null payload correctly. When a message with null payload comes in following exception is thrown:
```
java.lang.IllegalArgumentException: Payload must not be null
	at org.springframework.util.Assert.notNull(Assert.java:115)
	at org.springframework.messaging.support.MessageBuilder.createMessage(MessageBuilder.java:191)
	at org.springframework.kafka.support.converter.MessagingMessageConverter.toMessage(MessagingMessageConverter.java:78)
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.toMessagingMessage(MessagingMessageListenerAdapter.java:105)
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:97)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:597)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.access$1800(KafkaMessageListenerContainer.java:222)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$ListenerInvoker.run(KafkaMessageListenerContainer.java:778)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

This happens even if the payload is marked as a `@Payload(required = false)`. 

Currently the only way to handle such messages is to create and register own implementation of a message converter. 
However messages with null payload are completely valid in Kafka world (for example with a topic compaction enabled a message with a key and a null payload is treated as a delete from the log). Also `KafkaTemplate` support them correctly.

So, either remove `notNull` check for payload or use different converters depending on `@Payload(required = true/false)` flag... or at least provide a message converter implementation which accepts null payload.

**Comment by garyrussell** [comment]
Thanks; this is a bug - we're all at SpringOne Platform this week.

[Contributions](https://github.com/spring-projects/spring-kafka/blob/master/CONTRIBUTING.adoc) are always welcome 😄

**Comment by artembilan** [comment]
Looks like we can overcome (fix) the problem with empty string or `byte[]` - `PayloadArgumentResolver`:
```
if (isEmptyPayload(payload)) {
			if (ann == null || ann.required()) {
				String paramName = getParameterName(parameter);
				BindingResult bindingResult = new BeanPropertyBindingResult(payload, paramName);
				bindingResult.addError(new ObjectError(paramName, "Payload value must not be empty"));
				throw new MethodArgumentNotValidException(message, parameter, bindingResult);
			}
			else {
				return null;
			}
		}
...
	protected boolean isEmptyPayload(Object payload) {
		if (payload == null) {
			return true;
		}
		else if (payload instanceof byte[]) {
			return ((byte[]) payload).length == 0;
		}
		else if (payload instanceof String) {
			return !StringUtils.hasText((String) payload);
		}
		else {
			return false;
		}
	}
```
Although that solution in Spring Framework looks a bit clumsy for me...

**Comment by daroo** [comment]
I'd rather go with something like this - `MessagingMessageConverter#toMessage`:

`return new GenericMessage<>(extractAndConvertValue(record, type), kafkaMessageHeaders);`
together with null check also in `StringJsonMessageConverter#extractAndConvertValue`

I'd gladly contribute a code but I need a ticket in your bug tracking system I guess :smile: 

BTW. I hope you guys enjoyed the conference. :smile:

**Comment by artembilan** [comment]
Yeah! I think I can agree with you about "null-aware" `KafkaMessage`.

Yes, we are always open for contribution.
Yes, this issue is exactly a ticket in our system.
So, GH-160 is the best name for branch to Pull Request eventually.

Thank you for catching that up and for considering contribution!

**Comment by daroo** [comment]
I've created PR: https://github.com/spring-projects/spring-kafka/pull/163
