### ISSUE TITLE
Scala lib version mismatch in Spring Kafka

### ISSUE THREAD

**Issue by lukas-krecan** [spring-projects/spring-kafka#1604]
Scala lib version mismatch in Spring Kafka in Spring Boot 2.3.5

Frankly I do not know if this is Spring Boot bug or Spring Kafka Bug. After upgrading to Spring Boot 2.3.5, we started to get following error when starting embedded Kafka Test

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedKafka': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:406)
	at org.springframework.kafka.test.context.EmbeddedKafkaContextCustomizer.customizeContext(EmbeddedKafkaContextCustomizer.java:116)
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextCustomizerAdapter.initialize(SpringBootContextLoader.java:302)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 50 more
Caused by: java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7
	at kafka.api.ApiVersion$.orderingByVersion(ApiVersion.scala:45)
	at kafka.api.ApiVersion.compare(ApiVersion.scala:139)
	at kafka.api.ApiVersion.compare$(ApiVersion.scala:138)
	at kafka.api.KAFKA_2_5_IV0$.compare(ApiVersion.scala:339)
	at kafka.api.KAFKA_2_5_IV0$.compare(ApiVersion.scala:339)
	at scala.math.Ordered.$greater$eq(Ordered.scala:91)
	at scala.math.Ordered.$greater$eq$(Ordered.scala:91)
```

It's caused by scala library mismatch which is caused by Jackson library upgrade as shown here:

```
|    +--- org.apache.kafka:kafka_2.12:2.5.1
|    |    +--- org.apache.kafka:kafka-clients:2.5.1 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.10.2 -> 2.11.3 (*)
|    |    +--- com.fasterxml.jackson.module:jackson-module-scala_2.12:2.10.2 -> 2.11.3
|    |    |    +--- org.scala-lang:scala-library:2.12.12
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.11.3
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.3
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.3 (*)
|    |    |    \--- com.fasterxml.jackson.module:jackson-module-paranamer:2.11.3
|    |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.11.3 (*)
|    |    |         \--- com.thoughtworks.paranamer:paranamer:2.8
|    |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-csv:2.10.2 -> 2.11.3
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.3 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.3
|    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.11.3
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.10.2 -> 2.11.3 (*)
|    |    +--- net.sf.jopt-simple:jopt-simple:5.0.4
|    |    +--- com.yammer.metrics:metrics-core:2.2.0
|    |    |    \--- org.slf4j:slf4j-api:1.7.2 -> 1.7.30
|    |    +--- org.scala-lang.modules:scala-collection-compat_2.12:2.1.3
|    |    |    \--- org.scala-lang:scala-library:2.12.8 -> 2.12.12
|    |    +--- org.scala-lang.modules:scala-java8-compat_2.12:0.9.0
|    |    |    \--- org.scala-lang:scala-library:2.12.4 -> 2.12.12
|    |    +--- org.scala-lang:scala-library:2.12.10 -> 2.12.12
|    |    +--- org.scala-lang:scala-reflect:2.12.10 -> 2.12.11
|    |    |    \--- org.scala-lang:scala-library:2.12.11 -> 2.12.12
|    |    +--- com.typesafe.scala-logging:scala-logging_2.12:3.9.2
|    |    |    +--- org.scala-lang:scala-library:2.12.7 -> 2.12.12
|    |    |    +--- org.scala-lang:scala-reflect:2.12.7 -> 2.12.11 (*)
|    |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
```

It seems that `jackson-databind` version is overriden by Spring Boot which in turn introduces newer version of `jackson-module-scala` which in turn introduces `org.scala-lang:scala-library:2.12.12` which is not compatible with 2.12.11 because Scala.

Excluding jackson-module-scala_2.12 from spring kafka dependencies helps. The project is built by Gradle.

Reported in Spring Boot as https://github.com/spring-projects/spring-boot/issues/23979

**Comment by garyrussell** [comment]
Unfortunately, the Scala guys made some severe incompatibility changes in a point release, which is very bad practice - they don't seem to consider compatibility.

See the discussion in the boot issue.

We had to override those jar versions in the project itself.

https://github.com/spring-projects/spring-kafka/blob/ab6a1fd44841df1450c33a2ba3ecc1da2b275539/build.gradle#L65

and

https://github.com/spring-projects/spring-kafka/blob/ab6a1fd44841df1450c33a2ba3ecc1da2b275539/build.gradle#L302-L303

You should do something similar.

I'll keep this open and use it to add a not to the reference manual.

**Comment by lukas-krecan** [comment]
Thanks, we did exactly that. I just thought we will not be the only one having the same issue.

**Comment by garyrussell** [comment]
Alternatively, you could upgrade all the spring-kafka and associated jars to 2.6.2, which is used by the upcoming Boot 2.4 release, but works with 2.3.

https://docs.spring.io/spring-kafka/docs/2.6.2/reference/html/#update-deps
