### ISSUE TITLE
Throw ArrayIndexOutOfBoundsException when consuming messages

### ISSUE THREAD

**Issue by SunJiFengPlus** [spring-projects/spring-kafka#1624]
This is an occasional exception.

**Affects Version(s):** spring-kafka: 2.3.10.RELEASE, kafka-client: 2.0.0, spring-boot:2.2.9.RELEASE

error log:
```txt
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void EventBus.notify(java.util.List<org.apache.kafka.clients.consumer.ConsumerRecord<?, byte[]>>)' threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1; nested exception is java.lang.ArrayIndexOutOfBoundsException: 1
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:1842)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchErrorHandler(KafkaMessageListenerContainer.java:1564)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeBatchListener(KafkaMessageListenerContainer.java:1442)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeBatchListener(KafkaMessageListenerContainer.java:1327)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1310)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1044)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:958)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
```

Signature of the consume method:
```java
    @KafkaListener(topics = "${spring.kafka.template.default-topic}")
    public void notify(List<ConsumerRecord<?, byte[]>> consumerRecords) {
     
    }
```

application.yml
```yml
  kafka:
    bootstrap-servers: xxx:xxxx
    listener:
      type: batch
    consumer:
      group-id: xxxx
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="xxx" password="xxx";
      # dummy url
      schema.registry.url: http://localhost:8081
    template:
      default-topic: xxx
```

It does not seem to be the exception caused by the consume method, and the exception is thrown before the consume method is executed. 

Will this problem cause some messages to be lost? How can i fix this?

**Comment by garyrussell** [comment]
It appears that an exception that is being thrown by your listener has some problem in its `getCause()` method, which we are calling from `KafkaMessageListenerContainer.java:1842`.

>Caused by: java.lang.ArrayIndexOutOfBoundsException: 1

Please show the rest of the stack trace so we can see the actual problem.

**Comment by SunJiFengPlus** [comment]
This is an exception caused by my consume method 😅
