### ISSUE TITLE
MessageConversionException when using specific Avro reader

### ISSUE THREAD

**Issue by filipovskid** [spring-projects/spring-kafka#1665]
Hi, 

I have a `@KafkaListener` that accepts POJOs generated via `avro-maven-plugin` using Avro schema. The problem seems to be that the consumed message cannot be converted to an avro-generated record type. This seems to be due to converter's inability to infer whether the received message can be assigned to the record type. 

`MessageConversionException` trace:

```
Caused by: org.springframework.messaging.converter.MessageConversionException: Cannot convert from [com.filipovski.drboson.sharedkernel.integration.avro.UserCreatedRecord] to [com.filipovski.drboson.sharedkernel.integration.avro.UserCreatedRecord] for GenericMessage [payload={"user_id": "3bd91cfe-9abc-448f-a4a4-271cc25b73d5", "username": "abc", "password": "$2a$10$WExOzHHm.0axjRW.sjIgaepS8E/5O2F2zT27yZP835lOn4xAFeZ.q", "email": "abc@filipovski.com", "timestamp": 1609712955}, headers={kafka_offset=17, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@60a00f5, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=0, kafka_receivedMessageKey=3bd91cfe-9abc-448f-a4a4-271cc25b73d5, kafka_receivedTopic=users, kafka_receivedTimestamp=1609712955705, kafka_groupId=user-auth}]
	at org.springframework.messaging.handler.annotation.support.PayloadMethodArgumentResolver.resolveArgument(PayloadMethodArgumentResolver.java:145) ~[spring-messaging-5.3.2.jar:5.3.2]
	at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor$KafkaNullAwarePayloadArgumentResolver.resolveArgument(KafkaListenerAnnotationBeanPostProcessor.java:926) ~[spring-kafka-2.6.4.jar:2.6.4]
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117) ~[spring-messaging-5.3.2.jar:5.3.2]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:148) ~[spring-messaging-5.3.2.jar:5.3.2]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116) ~[spring-messaging-5.3.2.jar:5.3.2]
	at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:48) ~[spring-kafka-2.6.4.jar:2.6.4]
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:329) ~[spring-kafka-2.6.4.jar:2.6.4]
	... 14 common frames omitted
```

Consumer configuration: 

```
spring.kafka.bootstrap-servers=kafka-broker:9092
spring.kafka.properties.schema.registry.url=http://schema-registry:8081
spring.kafka.properties.specific.avro.reader=true
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
```

@KafkaListener: 

```
@KafkaListener(topics = "#{'${kafka.users.topic}'}", groupId = "user-auth")
public void onUserCreatedEvent(UserCreatedRecord user) { .. } 
```

**Affects Version(s):** 2.6.4

**Comment by garyrussell** [comment]
>Caused by: org.springframework.messaging.converter.MessageConversionException: Cannot convert from [com.filipovski.drboson.sharedkernel.integration.avro.UserCreatedRecord] to [com.filipovski.drboson.sharedkernel.integration.avro.UserCreatedRecord] ...

This is generally caused by a class loader problem, with the deserializer being loaded by a different class loader to the listener.

Are you using Spring DevTools? Or some other unusual class loader configuration.

If so, either fix the class loader problem, or pass the deserializer directly into the `DefaultKafkaConsumerFactory` (via a constructor or setter) so that the deserializer (and `UserCreatedRecord`) are loaded by the same class loader as the listener.

**Comment by garyrussell** [comment]
If you want to stick with Boot's factory, use something like...

```java
@Component
class Customizer {

    Customizer(DefaultKafkaConsumerFactory<?, UserCreatedRecord > cf) {
        cf.setValueDeserializer(...);
    }

}
```

**Comment by filipovskid** [comment]
Thank you ! The class was indeed loaded by the DevTools `RestartClassLoader`.

**Comment by schowdiah** [comment]
> Thank you ! The class was indeed loaded by the DevTools `RestartClassLoader`.

@filipovskid, how do you resolve the issue🥸

**Comment by filipovskid** [comment]
@schowdiah I had DevTools dependency included, but I wasn't using it, thus I removed it. If you are using DevTools or the classes are being loaded with a completely different ClassLoader I would recommend going with the solution suggested by @garyrussell of defining a factory 

 

> If you want to stick with Boot's factory, use something like...
> 
> ```java
> @Component
> class Customizer {
> 
>     Customizer(DefaultKafkaConsumerFactory<?, UserCreatedRecord> cf) {
>         cf.setValueDeserializer(...);
>     }
> 
> }
> ```

**Comment by lamoboos223** [comment]
@garyrussell you are amazing!

how did you know it was from a class loader?

**Comment by garyrussell** [comment]
It's pretty obvious from the error message:

>Caused by: org.springframework.messaging.converter.MessageConversionException: Cannot convert from [com.filipovski.drboson.sharedkernel.integration.avro.UserCreatedRecord] to [com.filipovski.drboson.sharedkernel.integration.avro.UserCreatedRecord] ...

The from and to classes are identical, so they must have been loaded by different class loaders to get that error.

**Comment by xchopin** [comment]
Hi, I still have the same issue on 3.x Spring

- Java classes generated via Avro 
- Produce a message in Kafka with an Avro generated class
- Read the message 

Get the  `org.springframework.messaging.converter.MessageConversionException: Cannot convert from` error

Removing Spring Dev Tools from the dependencies fixed the issue (thanks for the solution!) however I think that's a bit of a drastic measure for a fix 😅 

Any news about this? Thank you

**Comment by sobychacko** [comment]
@xchopin We will need to look more into it to understand what's going on, but we will let you know soon. Thanks!

**Comment by garyrussell** [comment]
@sobychacko @xchopin There's really nothing more to "look into". The problem is that Kafka uses its own classloader; to solve the problem you must use the same classloader as Spring to load the deserializer (when using DevTools), as I explained above.

I believe there is no other solution (aside from the brute force of not using DevTools).

Given that there is a reasonable work around, I would not waste any more time on this.

Of course, since I am no longer involved with the project, you should make your own determination; just my 2¢.

**Comment by sobychacko** [comment]
@garyrussell Great to hear from you! It's always a pleasure when we hear from you. And thanks for jumping into this issue. This issue has come up in a discussion we had today, and I suggested commenting here so that we can triage it further. But now that I went back through the issue log and comments, what you said makes absolute sense. 

@xchopin Please see Gary's comments above. If you don't want to remove the devtools, try to use the same classloader for the deserializer. The straightforward fix is to pass the deserializer directly to the consumer factory. I am closing this issue since there is nothing more to be done from the framework perspective. Hope it resolves your issue.
