### ISSUE TITLE
@RetryableTopic Fails with "Another endpoint is already registered with id"

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#1715]
```java
@SpringBootApplication
public class Kgh920Application {

	public static void main(String[] args) {
		SpringApplication.run(Kgh920Application.class, args);
	}

	@RetryableTopic(attempts = 5, backoff = @Backoff(delay = 1000, multiplier = 2.0), kafkaTemplate = "kafkaTemplate")
	@KafkaListener(id = "kgh920", topics = "kgh920", containerFactory = "kafkaListenerContainerFactory")
	public void listen(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		System.out.println(in + " from " + topic);
		throw new RuntimeException("test");
	}

	@DltHandler
	public void dlt(String in, @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
		System.out.println(in + " from " + topic);
	}

}
```
```properties
spring.kafka.consumer.auto-offset-reset=earliest
```
```
2021-02-25 14:46:38.078 ERROR 66259 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Another endpoint is already registered with id 'kgh920'
	at org.springframework.util.Assert.state(Assert.java:76) ~[spring-core-5.3.4.jar:5.3.4]
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.registerListenerContainer(KafkaListenerEndpointRegistry.java:177) ~[spring-kafka-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.registerListenerContainer(KafkaListenerEndpointRegistry.java:152) ~[spring-kafka-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at org.springframework.kafka.config.KafkaListenerEndpointRegistrar.registerAllEndpoints(KafkaListenerEndpointRegistrar.java:196) ~[spring-kafka-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at org.springframework.kafka.config.KafkaListenerEndpointRegistrar.afterPropertiesSet(KafkaListenerEndpointRegistrar.java:186) ~[spring-kafka-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor.afterSingletonsInstantiated(KafkaListenerAnnotationBeanPostProcessor.java:279) ~[spring-kafka-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:963) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) ~[spring-boot-2.5.0-SNAPSHOT.jar:2.5.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.5.0-SNAPSHOT.jar:2.5.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.5.0-SNAPSHOT.jar:2.5.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1299) ~[spring-boot-2.5.0-SNAPSHOT.jar:2.5.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1288) ~[spring-boot-2.5.0-SNAPSHOT.jar:2.5.0-SNAPSHOT]
	at com.example.demo.Kgh920Application.main(Kgh920Application.java:16) ~[classes/:na]
```

cc/ @tomazfernandes

**Comment by garyrussell** [comment]
Only occurs with explicit IDs - need to qualify the id with the retry suffix.

**Comment by tomazfernandes** [comment]
Hi @garyrussell! I'm glad you're looking into this, keep those nasty ones coming, I just hope there aren't too many of them 😄 

Yeah, the problem is that I'm actually registering the main endpoint twice, courtesy of my last minute refactoring of the RetryTopicConfigurer in the last PR. Should not be difficult to solve, I'm on it.

DYW a separate PR for each of the issues, or is it better to solve them all in one PR?

**Comment by garyrussell** [comment]
Thanks. Separate PRs are best, unless the fixes have a lot of collisions.
