### ISSUE TITLE
Upgrade to Kafka 2.8.0

### ISSUE THREAD

**Issue by carlspring** [spring-projects/spring-kafka#1792]
The current version of `spring-kafka` uses Kafka 2.7.0. There is now a vesion 2.8.0 which, among other things, introduces support for KRraft (Kafka RAFT). I'm interested in experimenting with this in Spring. Simply switching the Kafka dependencies to 2.8.0 and adding dependency excludes where necessary is not enough. I tried playing with the `spring-kafka` codebase and upgrading the dependencies, but this breaks the `KafkaStreamBrancherTests` and it's not quite straight-forward for me what  need to be fixed and how, as there are breaking changes with the deprecation of `KStream.branch` and using `split()` instead. It doesn't look like a massive amount of work, but it would be better to have someone more experienced with Kafka upgrading this.

Are there any plans to upgrade to 2.8.0 any time soon?

**Comment by carlspring** [comment]
(Closed it accidentally)...

**Comment by garyrussell** [comment]
We can’t change versions in a patch release. The next minor release will use the 2.8.x clients.

2.7.1 (May 17, currently) will work with the 2.8.0 clients. See https://docs.spring.io/spring-kafka/docs/2.7.1-SNAPSHOT/reference/html/#update-deps and https://github.com/spring-projects/spring-kafka/pull/1775

**Comment by carlspring** [comment]
I have experimented and tried it. In my tests I am using `@EmbeddedKafka` and when i switch to the latest snapshot with a `pom.xml` that looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.carlspring.hello</groupId>
    <artifactId>hello-spring-kafka</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>Hello Spring Kafka</name>
    <description>Intro to Kafka with Spring</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <version.spring.boot>2.4.3</version.spring.boot>
        <version.spring.kafka>2.7.1-SNAPSHOT</version.spring.kafka>
        <version.jackson>2.11.1</version.jackson>
        <version.kafka>2.8.0</version.kafka>
        <version.testcontainers>1.15.0</version.testcontainers>
        <version.junit>5.4.2</version.junit>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>5.3.6</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>${version.spring.boot}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
            <version>${version.spring.kafka}</version>

            <exclusions>
                <exclusion>
                    <groupId>org.apache.kafka</groupId>
                    <artifactId>kafka-clients</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>${version.kafka}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>5.3.6</version>
            <scope>test</scope>
            
            <exclusions>
                <exclusion>
                    <groupId>org.apache.kafka</groupId>
                    <artifactId>kafka-clients</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <version>2.4.5</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka-test</artifactId>
            <version>${version.spring.kafka}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>1</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${version.jackson}</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${version.junit}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>${version.junit}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${version.junit}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers</artifactId>
            <version>${version.testcontainers}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${version.testcontainers}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>kafka</artifactId>
            <version>${version.testcontainers}</version>
            <scope>test</scope>

            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.19.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>spring-snapshots</id>
            <url>https://repo.spring.io/snapshot/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

</project>
```

I get:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedKafka': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/apache/kafka/common/record/BufferSupplier
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:413)
	at org.springframework.kafka.test.context.EmbeddedKafkaContextCustomizer.customizeContext(EmbeddedKafkaContextCustomizer.java:116)
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextCustomizerAdapter.initialize(SpringBootContextLoader.java:277)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:635)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:390)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:123)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 63 more
Caused by: java.lang.NoClassDefFoundError: org/apache/kafka/common/record/BufferSupplier
	at kafka.log.Cleaner.<init>(LogCleaner.scala:492)
	at kafka.log.LogCleaner$CleanerThread.<init>(LogCleaner.scala:306)
	at kafka.log.LogCleaner.$anonfun$startup$2(LogCleaner.scala:155)
	at kafka.log.LogCleaner.startup(LogCleaner.scala:154)
	at kafka.log.LogManager.startup(LogManager.scala:435)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:291)
	at kafka.utils.TestUtils$.createServer(TestUtils.scala:161)
	at kafka.utils.TestUtils$.createServer(TestUtils.scala:152)
	at kafka.utils.TestUtils.createServer(TestUtils.scala)
	at org.springframework.kafka.test.EmbeddedKafkaBroker.afterPropertiesSet(EmbeddedKafkaBroker.java:337)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 72 more
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.record.BufferSupplier
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 84 more
```

You can ignore the `testcontainers` dependencies. I am experimenting with both the `@EmbeddedKafka` and running it via `testcontainers`.

If I remove all the dependency exclusions and revert to `spring-kafka:2.7.0`, my tests work, but they are not using the latest kafka. (While we're on it, perhaps you might be able to tell me where I can find an official Docker image that includes the latest Kafka? The ones from Confluent are using Kafka 2.5.x).

Thanks for your help!

**Comment by garyrussell** [comment]
You didn't follow the instructions that I pointed you to; you also have to override the kafka broker jar versions:

```xml
<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>kafka_2.13</artifactId>
    <version>{kafka-version}</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>kafka_2.13</artifactId>
    <version>{kafka-version}</version>
    <classifier>test</classifier>
    <scope>test</scope>
</dependency>
```

Otherwise, Boot will pull in the 2.7.0 jars.

**Comment by garyrussell** [comment]
2.8.0-RC1 (release candidate) was released Monday - it now uses the 3.0.0 clents (we switched to 2.8.1 after M3 but then 3.0.0 was released so we jumped to that version).

Spring for Apache Kafka 2.8.0 will be released next month.

You can override the clients to 2.8.1 with the current 2.7.8 release; see [the docs](https://docs.spring.io/spring-kafka/docs/current/reference/html/#update-deps)

**Comment by AdiWehrli** [comment]
Oh, thanks very much. That's good news, indeed.
