### ISSUE TITLE
Fix Flaky Retry Topic Configurer Test

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-kafka#1830]
```
RetryTopicConfigurerTests > shouldLogConsumerRecordMessage() FAILED
    org.mockito.exceptions.verification.NeverWantedButInvoked: 
    consumerRecordMessage.topic();
    Never wanted here:
    -> at org.springframework.kafka.retrytopic.RetryTopicConfigurerTests.shouldLogConsumerRecordMessage(RetryTopicConfigurerTests.java:363)
    But invoked here:
    -> at org.springframework.kafka.listener.ListenerUtils.recordToString(ListenerUtils.java:133) with arguments: []
        at org.springframework.kafka.retrytopic.RetryTopicConfigurerTests.shouldLogConsumerRecordMessage(RetryTopicConfigurerTests.java:363)
```

**Comment by garyrussell** [comment]
I had DEBUG logging enabled.
