### ISSUE TITLE
message not consumer if exception happen inside deserializer 

### ISSUE THREAD

**Issue by sdhjl2000** [spring-projects/spring-kafka#208]
hi guys,in my application if error happen  inside custom deserializer , the message was not consumer and offset not change, any method to handle this situation.should i handle exception inside  deserializer .
the config is:
`  @Bean
    public ConcurrentKafkaListenerContainerFactory kafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory factory = new ConcurrentKafkaListenerContainerFactory<>();
        ContainerProperties props = factory.getContainerProperties();
        props.setAckOnError(true);
        props.setSyncCommits(true);
        props.setAckMode(AbstractMessageListenerContainer.AckMode.BATCH);
        factory.setAutoStartup(true);
        factory.setConcurrency(3);
        factory.setConsumerFactory(consumerFactory());
        return factory;
    }`
StackTrace:
016-11-29 11:30:49 ERROR NetworkClient:276 - Uncaught error in request completion:
org.apache.kafka.common.KafkaException: Error deserializing key/value for partition leadsServer.test-0 at offset 0
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:628)
	at org.apache.kafka.clients.consumer.internals.Fetcher.handleFetchResponse(Fetcher.java:566)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$000(Fetcher.java:69)
	at org.apache.kafka.clients.consumer.internals.Fetcher$1.onSuccess(Fetcher.java:139)
	at org.apache.kafka.clients.consumer.internals.Fetcher$1.onSuccess(Fetcher.java:136)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:133)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:107)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.onComplete(ConsumerNetworkClient.java:380)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:274)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:320)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:213)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:193)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:908)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:853)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:408)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Reading from a byte array threw an IOException (should never happen).
	at io.protostuff.IOUtil.mergeFrom(IOUtil.java:54)
	at io.protostuff.ProtostuffIOUtil.mergeFrom(ProtostuffIOUtil.java:104)
	at com.autohome.dealer.advjobapi.api.order.ProtoDeserializer.deserialize(ProtoDeserializer.java:37)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:622)
	... 17 more
Caused by: io.protostuff.ProtobufException: Protocol message contained an invalid tag (zero).
	at io.protostuff.ProtobufException.invalidTag(ProtobufException.java:106)
	at io.protostuff.ByteArrayInput.readFieldNumber(ByteArrayInput.java:253)
	at io.protostuff.runtime.RuntimeSchema.mergeFrom(RuntimeSchema.java:457)
	at io.protostuff.IOUtil.mergeFrom(IOUtil.java:45)
	... 20 more

**Comment by garyrussell** [comment]
Unfortunately, that all happens before Spring gets the data so we have no control over it - that's a function of the Apache Kafka consumer code; you need to ask over there.

In the meantime, you could catch the exception in the deserializer and return a "special value" that tells your application there was a deserialization error and the offset will then be committed ok.

**Comment by garyrussell** [comment]
Closed with no response.
