### ISSUE TITLE
Warning in application logs with Spring Kafka when Kafka topic is not configured properly

### ISSUE THREAD

**Issue by stepio** [spring-projects/spring-kafka#211]
Dear @artembilan and @garyrussell ,

First of all thank you for your job, hope you do well.

As of now I use Spring Boot v.1.4.2.RELEASE with Spring Kafka v.1.0.5.RELEASE. And I have next code block for consuming messages from Kafka:
```java
@KafkaListener(containerFactory = "emailContainerFactory", topics = "${kafka.topic.email}")
public void onMessage(MessageTO request) throws NotificationException {
    // some processing here
}
```

When I've missed "kafka.topic.email" in my property file (have not defined this variable properly), I've started getting next warning in log:
```java
2016-12-05T12:02:15,407 WARN  [o.a.k.c.NetworkClient] (org.springframework.kafka.KafkaListenerEndpointContainer#1-0-kafka-consumer-1) - Error while fetching metadata with correlation id 303 : {${kafka.topic.email}=INVALID_TOPIC_EXCEPTION}
2016-12-05T12:02:15,574 WARN  [o.a.k.c.NetworkClient] (org.springframework.kafka.KafkaListenerEndpointContainer#1-0-kafka-consumer-1) - Error while fetching metadata with correlation id 305 : {${kafka.topic.email}=INVALID_TOPIC_EXCEPTION}
2016-12-05T12:02:15,741 WARN  [o.a.k.c.NetworkClient] (org.springframework.kafka.KafkaListenerEndpointContainer#1-0-kafka-consumer-1) - Error while fetching metadata with correlation id 307 : {${kafka.topic.email}=INVALID_TOPIC_EXCEPTION}
2016-12-05T12:02:15,908 WARN  [o.a.k.c.NetworkClient] (org.springframework.kafka.KafkaListenerEndpointContainer#1-0-kafka-consumer-1) - Error while fetching metadata with correlation id 309 : {${kafka.topic.email}=INVALID_TOPIC_EXCEPTION}
2016-12-05T12:02:16,075 WARN  [o.a.k.c.NetworkClient] (org.springframework.kafka.KafkaListenerEndpointContainer#1-0-kafka-consumer-1) - Error while fetching metadata with correlation id 311 : {${kafka.topic.email}=INVALID_TOPIC_EXCEPTION}
```
First of all, I'd expect that if property looks like variable and is not resolved properly, there should be a startup exception and application should fail. Just warning is not enough. So I've decided to investigate the code and followed the given `org.springframework.kafka.KafkaListenerEndpointContainer` assuming that it's some class. But not, no such class, I've only managed to find next code:
```java
private String getEndpointId(KafkaListener kafkaListener) {
	if (StringUtils.hasText(kafkaListener.id())) {
		return resolve(kafkaListener.id());
	}
	else {
		return "org.springframework.kafka.KafkaListenerEndpointContainer#" + this.counter.getAndIncrement();
	}
}
```
So I have two questions:
1. What do you think about checking if the topic name resolved properly before passing it to Kafka client? Most probably the behavior should be as in Spring Framework itself - if property is not resolved (and no default value), throw exception to fail the application.
2. What is the idea behind this naming, which looks like a class, but not a class?

**Comment by garyrussell** [comment]
Hi @stepio 

1. Yes, we could (and perhaps should) add a check to see if the annotation attributes still contain a placeholder after the resolution attempt.

2. That was simply copied/pasted from Spring AMQP  `@RabbitListner` which has a similar (non-existent "class") name (same thing with `@JmsListener`).

I generally prefer to give my listeners useful `id`s but I can see this "class-like" default naming could be confusing.

While it wouldn't hurt to change it to a real class name, we can't do that in an 1.0.x release because it would be a breaking change.

**Comment by artembilan** [comment]
@stepio , hello again!

Always glad to see you feedback and valuable contribution to our projects.

What confuses me with your issue is this.

My test case looks like:
```
@Bean
public static PropertySourcesPlaceholderConfigurer ppc() {
	return new PropertySourcesPlaceholderConfigurer();
}
...
@KafkaListener(id = "foo", topics = "${topicOne}")
public void listen1(String foo) {
	this.latch1.countDown();
}
```
and I end up with this:
```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'topicOne' in string value "${topicOne}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:219)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:193)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:172)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:813)
	at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor.resolve(KafkaListenerAnnotationBeanPostProcessor.java:604)
```

You see no any raw value passing to the Kafka Client.

Check that your `PropertySourcesPlaceholderConfigurer` isn't configure with the `ignoreUnresolvablePlaceholders = true`:
```
	/**
	 * Set whether to ignore unresolvable placeholders.
	 * <p>Default is "false": An exception will be thrown if a placeholder fails
	 * to resolve. Switch this flag to "true" in order to preserve the placeholder
	 * String as-is in such a case, leaving it up to other placeholder configurers
	 * to resolve it.
	 */
	public void setIgnoreUnresolvablePlaceholders(boolean ignoreUnresolvablePlaceholders) {
```
Otherwise it isn't clear how your application is able to pass unresolved placeholder as is...

**Comment by stepio** [comment]
@artembilan 

Thanks, you're right. Sorry for disturbing you, guys.

I have not defined `PropertySourcesPlaceholderConfigurer` myself, but after checking `/beans` endpoint found next part:
```json
{
    "bean":"swaggerProperties",
    "scope":"singleton",
    "type":"org.springframework.context.support.PropertySourcesPlaceholderConfigurer",
    "resource":"springfox.documentation.swagger.configuration.SwaggerCommonConfiguration",
    "dependencies":[]
},
```

Then I've checked the code of Swagger tool and found the above mentioned configuration:
```java
public class SwaggerCommonConfiguration {
    public SwaggerCommonConfiguration() {
    }

    @Bean
    public static PropertySourcesPlaceholderConfigurer swaggerProperties() {
        PropertySourcesPlaceholderConfigurer propertySourcesPlaceholderConfigurer = new PropertySourcesPlaceholderConfigurer();
        propertySourcesPlaceholderConfigurer.setIgnoreUnresolvablePlaceholders(true);
        return propertySourcesPlaceholderConfigurer;
    }
}
```

So no issues with your code, just a minor conflict with Swagger.

**Comment by stepio** [comment]
Hi @garyrussell 

Thanks for the detailed explanation, got your idea. You had to implement some default naming and I do agree that yours looks nice. And I'm not sure that real class name would not confuse someone else in some other way.

**Comment by artembilan** [comment]
The name like `return "org.springframework.kafka.KafkaListenerEndpointContainer#" + this.counter.getAndIncrement();` is the standard name strategy in Srping Framework when we declare `<bean>` without `id` - `BeanDefinitionReaderUtils.generateBeanName()`.

So, to be consistent the same strategy has been selected here for "anonymous" listener definitions.

If that makes sense for you, let's consider an issue as fixed 😄

**Comment by stepio** [comment]
Sure, thanks, closed :)
