### ISSUE TITLE
How to send message from customSeekToCurrentErrorHandler class to my error topics

### ISSUE THREAD

**Issue by harisatyanarayana-php** [spring-projects/spring-kafka#2228]
@Override
	public  void handle(Exception exception, List<ConsumerRecord<?, ?>> records, Consumer<?, ?> consumer,
			MessageListenerContainer container) {
		try {
			if (!records.isEmpty()) {
				logger.warn("Exception: {} occurred with message: {}", exception, exception.getMessage());

				super.handle(exception, records, consumer, container);
				
				System.out.println("Error Handle ===\n"+records.get(0).value());
				
				template.send(ApplicationConstant.ERROR_TOPIC, records.get(0).value());
				
				
			}
			
		
		} catch (SerializationException e) {
			logger.warn("Exception: {} occurred with message: {}", e, e.getMessage());
		}
	}

error message : 

org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void com.loblaw.cpack.exceptionhandler.consumer.KafkaConsumer.receivedMessage(java.lang.String,org.apache.kafka.clients.consumer.ConsumerRecord<java.lang.String, java.lang.String>)' threw exception; nested exception is com.loblaw.cpack.exceptionhandler.exception.SixException: Routed To Retry Topic 6
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:302) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:80) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:51) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1141) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1115) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1057) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:903) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:753) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.loblaw.cpack.exceptionhandler.exception.SixException: Routed To Retry Topic 6
	at com.loblaw.cpack.exceptionhandler.consumer.KafkaConsumer.receivedMessage(KafkaConsumer.java:46) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-messaging-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:48) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:283) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	... 10 common frames omitted

hellloooo ===
{
"num":"6"
}
2022-04-11 18:15:36.218 ERROR 13688 --- [ntainer#0-0-C-1] essageListenerContainer$ListenerConsumer : Error handler threw an exception

java.lang.NullPointerException: null
	at com.loblaw.cpack.exceptionhandler.exception.CustomSeekToCurrentErrorHandler.handle(CustomSeekToCurrentErrorHandler.java:46) ~[classes/:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1178) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1115) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1057) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:903) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:753) ~[spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by harisatyanarayana-php** [comment]
@garyrussell  Can you please guide me , i have requirement , when i need to send to error topic from CustomSeekToCurrentErrorHandler class which extends SeekToCurrentErrorHandler. when i try to use the kafka template i am getting null pointer exception.

**Comment by harisatyanarayana-php** [comment]
i have done the changes
