### ISSUE TITLE
EmbeddedKafkaRule isn't compatible with Kafka client 3.2.0

### ISSUE THREAD

**Issue by cykl** [spring-projects/spring-kafka#2272]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.8.5 (affects 2.8.3 too)

**Describe the bug**

While updating an internal fork of https://github.com/opentracing-contrib/java-kafka-client (upstream doesn't seems maintained anymore) I noticed that EmbeddedKafkaRule based tests fail when Kafka client version is 3.2.0. Using 3.1.0 with 2.8.5 with fine.

I'm not a direct user of spring-kafka and according to https://spring.io/projects/spring-kafka 2.8x doesn't claim to be compatible with 3.2 but this might be a useful information to also support 3.2 in 2.8.x or plan next version.

**To Reproduce**

```java
public class TracingKafkaTest {

  @ClassRule
  public static EmbeddedKafkaRule embeddedKafka = new EmbeddedKafkaRule(2, true, 2, "messages");

[...]
}
```

Run test and observe following stack trace

```
kafka.common.KafkaException: 
	at org.springframework.kafka.test.EmbeddedKafkaBroker.createTopics(EmbeddedKafkaBroker.java:466)
	at org.springframework.kafka.test.EmbeddedKafkaBroker.lambda$createKafkaTopics$6(EmbeddedKafkaBroker.java:453)
	at org.springframework.kafka.test.EmbeddedKafkaBroker.doWithAdmin(EmbeddedKafkaBroker.java:549)
	at org.springframework.kafka.test.EmbeddedKafkaBroker.createKafkaTopics(EmbeddedKafkaBroker.java:452)
	at org.springframework.kafka.test.EmbeddedKafkaBroker.afterPropertiesSet(EmbeddedKafkaBroker.java:365)
	at org.springframework.kafka.test.rule.EmbeddedKafkaRule.before(EmbeddedKafkaRule.java:113)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
	at org.springframework.kafka.test.EmbeddedKafkaBroker.createTopics(EmbeddedKafkaBroker.java:463)
	... 29 more
```

**Expected behavior**

Test should start as before updating to Kafka 3.2.0.

**Sample**

Unlikely useful here. Please let me know if I'm wrong.

**Comment by artembilan** [comment]
Spring for Apache Kafka `2.8.x` has never claimed to be compatible with future version of Apache Kafka. 
And that's exactly what we have over here. The version `3.2.0` is tagged in Maven Central as this May 9th: https://mvnrepository.com/artifact/org.apache.kafka/kafka_2.12/3.2.0. Less than week ago.

Therefore we cannot treat your report as a bug.
We can reconsider it in favor of `Feature Request` if you change your mind, but no promises: too much reflection to support all the versions.

Better to test against external Kafka broker.
I'm not sure that there is already a respective Docker image for Apache Kafka `3.2.0` to be able to test through Testcontainers...

**Comment by cykl** [comment]
I agree with all your points. 

> We can reconsider it in favor of Feature Request if you change your mind, but no promises: too much reflection to support all the versions.

This is a feature request and I don't really expect 2.8 to be compatible with Kafka client 3.2.  

For what it worth, I share your pain regarding multiple versions (one level up the stack) :upside_down_face:
 
> Better to test against external Kafka broker.

I do agree and that's what I usually do. Unfortunately I inherited of opentracing-contrib/java-kafka-client maintenance which  use EmbeddedKafkaBroker and I'm reluctant to massively invest on its maintenance as Opentracing contrib ecosystem is almost dead. 

Do you have a rough  idea of when Kafka >= 3.2.0 might be supported by future release? I'm in no hurry, just trying to figure out an adoption plan and identify potential blockers.

**Comment by artembilan** [comment]
We `2.9.0` planning soon enough. This is based on Apache Kafka `3.1.0` at the moment. We indeed may reconsider that in favor of `3.2.0` and therefore fix `EmbeddedKafkaBroker`, respectively.

Plus: this is a concern only of the `EmbeddedKafkaBroker` which uses an Apache Kafka Broker API directly. Apache Kafka does not claim that API to be backward compatible. It is treated as internal and only for broker. 
This must not affect a production code anyhow since that one is based only on the Apache Kafka Client library which they do claim to be compatible with different broker versions.
Therefore I wouldn't update that "almost dead" opentracing-contrib to new minor/major versions: just patch releases!

On the other hand, re. versions compatibility. It really might be better for you to start a new minor version to justify an update to new Spring for Apache Kafka minor version (see that `2.9.0`), which is going to be based on a new minor Apache Kafka already.
Otherwise it may lead to pain like this ticket 😄

**Comment by garyrussell** [comment]
>We indeed may reconsider...

My intention was always to move 2.9.0 to 3.2.0 when it is available - even though the date in maven central is a week old, it is not officially released yet...

https://kafka.apache.org/downloads

>3.1.1 is the latest release. The current stable version is 3.1.1.

I am expecting it early next week according to the dialog on the mailing list.

**Comment by garyrussell** [comment]
I will release a new milestone of 2.9.x as soon as it is upgraded; I expect GA to be some time in June.

**Comment by garyrussell** [comment]
FYI, I had no problems moving 2.9.0 from 3.1.0 to 3.2.0 - no changes to the embedded broker were required - and I already tested 2.8.x against the 3.1.0 client, so I think the timeout above might have been a sporadic glitch. I will investigate further on Monday.

**Comment by garyrussell** [comment]
My 2.8.x smoke test app's test suite runs fine with the 3.2.0 clients and broker.

**Comment by cykl** [comment]
Thanks @garyrussell for the prompt feed back. Tests based on EmbeddedKafkaRule failed every time I ran them locally or on CI with aforementioned exception. I will try to create a reproducer and troubleshoot that next week.

**Comment by cykl** [comment]
I will provide a standalone reproducer ASAP but I have a lead on what might trigger a TimeoutException. Using `new EmbeddedKafkaRule(<anyInt>)` or any other overload is fine unless I set at least one topic. As soon as I add a topic parameter, I start observing TimeoutException. Changing value of count, controlledShutdown or partitions doesn't seem to matter, as long as their is a topic startup fails on TimeoutException.

**Comment by cykl** [comment]
https://github.com/cykl/spring-kafka-issues-2272-reproducer

**Comment by cykl** [comment]
> It's pulling in the wrong version of kafka-metadata (3.0.1).

Oops, I missed that! It works as expected with matching kafka-metadata. Thanks for the clarification about spring-kafka plans and my apologizes for the noise.
