### ISSUE TITLE
java.lang.IllegalStateException: Another endpoint is already registered with id

### ISSUE THREAD

**Issue by srikant-mvs** [spring-projects/spring-kafka#236]
Hi Team,
 I am have configured spring-kafka version 1.1.2 and using jetty server to run locally.
 
When I start my server, I see the below issue 

java.lang.IllegalStateException: Another endpoint is already registered with id 'KPOC'
	at org.springframework.util.Assert.state(Assert.java:392)
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.registerListenerContainer(KafkaListenerEndpointRegistry.java:152)
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.registerListenerContainer(KafkaListenerEndpointRegistry.java:128)
	at org.springframework.kafka.config.KafkaListenerEndpointRegistrar.registerAllEndpoints(KafkaListenerEndpointRegistrar.java:138)
	at org.springframework.kafka.config.KafkaListenerEndpointRegistrar.afterPropertiesSet(KafkaListenerEndpointRegistrar.java:132)
	at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor.afterSingletonsInstantiated(KafkaListenerAnnotationBeanPostProcessor.java:224)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:792)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at net.sourceforge.eclipsejetty.starter.embedded.JettyEmbeddedAdapter.start(JettyEmbeddedAdapter.java:67)
	at net.sourceforge.eclipsejetty.starter.common.AbstractJettyLauncherMain.launch(AbstractJettyLauncherMain.java:84)
	at net.sourceforge.eclipsejetty.starter.embedded.JettyEmbeddedLauncherMain.main(JettyEmbeddedLauncherMain.java:42)
2017-02-07 11:47:21.926:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8081

Here is my Listener Class

@Service
public class KafkaOrderListener {
	
	public final CountDownLatch countDownLatch = new CountDownLatch(1);
	
	@KafkaListener(id="KPOC", topics = "OrderTopic", group = "OrderGroup")
	public void listen(ConsumerRecord<String,KafkaPayload> record, Acknowledgment acknowledgment) {
		countDownLatch.countDown();		
		consumeKafkaMessage(record);		
		acknowledgment.acknowledge();
		
	}

}

I tried changing the ID value still it was throwing the same exception.

Here is the spring-kafka code that is internally throwing the error

Class Name : KafkaListenerEndpointRegistrar

protected void registerAllEndpoints() {
		synchronized (this.endpointDescriptors) {
			for (KafkaListenerEndpointDescriptor descriptor : this.endpointDescriptors) {
				this.endpointRegistry.registerListenerContainer(
						descriptor.endpoint, resolveContainerFactory(descriptor));
			}
			this.startImmediately = true;  // trigger immediate startup
		}
	}

Class Name : KafkaListenerEndpointRegistry

synchronized (this.listenerContainers) {
			Assert.state(!this.listenerContainers.containsKey(id),
					"Another endpoint is already registered with id '" + id + "'");
			MessageListenerContainer container = createListenerContainer(endpoint, factory);
			this.listenerContainers.put(id, container);
			if (StringUtils.hasText(endpoint.getGroup()) && this.applicationContext != null) {
				List<MessageListenerContainer> containerGroup;
				if (this.applicationContext.containsBean(endpoint.getGroup())) {
					containerGroup = this.applicationContext.getBean(endpoint.getGroup(), List.class);
				}
				else {
					containerGroup = new ArrayList<MessageListenerContainer>();
					this.applicationContext.getBeanFactory().registerSingleton(endpoint.getGroup(), containerGroup);
				}
				containerGroup.add(container);
			}
			if (startImmediately) {
				startIfNecessary(container);
			}
		}
I observed that my listener is trying to get added again and throws error at Assert.state.

Due to this issue, I am unable to run my project with version 1.1.2 and switching back to 1.0.4. 

Please let me know if I need to configure something to resolve this issue.

-Thanks
Srikant

**Comment by srikant-mvs** [comment]
I removed the @Service and it was working. Thanks

**Comment by artembilan** [comment]
Glad to hear!

I think your problem that you use `@ComponentScan` and also register that `KafkaOrderListener` as a `@Bean`.

**Comment by srikant-mvs** [comment]
I haven't used this annotation @ComponentScan, but yes have declared KafkaOrderListener as @Bean inside the KafkaConsumerConfig something like this 

@Bean
	public KafkaOrderListener listener() {
		return new KafkaOrder();
	}
But, this never threw the exception untill I added an @Service annotation.

Thanks for the response, Its fixed now.

**Comment by garyrussell** [comment]
You don't need the `@Bean`; that will actually do nothing except take up a bit more memory.

**Comment by srikant-mvs** [comment]
Oh, But i see this code snippet in the latest documentation of 1.1.2 version

@Bean
    public Listener listener() {
        return new Listener();
    }

Also, When I removed this @Bean, my listener didn't get called. Can you suggest how to configure this without using @Bean.

**Comment by garyrussell** [comment]
Sorry - my mistake - I misread your comment; you don't need the `@Bean` if you use `@ComponentScan` but you need it if not.

**Comment by artembilan** [comment]
Look, that `Listener` in the Reference Manual is without `@Service`.
So, we need `@Bean` for the instance to make it available in the application context.
