### ISSUE TITLE
Don't set JsonSerializer

### ISSUE THREAD

**Issue by KirillKurdyukov** [spring-projects/spring-kafka#2469]
2.8.2

Between 2.7.0 and 2.8.2

**Describe the bug**

Caused by: java.lang.ClassCastException: class example.kafka.model.ProcessingEvent cannot be cast to class java.lang.String (ru.yandex.fintech.kafka.model.ProcessingEvent is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at org.apache.kafka.common.serialization.StringSerializer.serialize(StringSerializer.java:29)
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:929)
	... 29 common frames omitted

data class ProcessingEvent(
    val cardId: String,
)

@Configuration
@EnableConfigurationProperties(KafkaProperties::class)
class ProducerKafkaProcessingEventConfiguration {

    @Bean
    fun producerFactory(
        kafkaProperties: KafkaProperties,
        objectMapper: ObjectMapper,
    ): ProducerFactory<String, ProcessingEvent> {
        val props = mapOf(
            ProducerConfig.BOOTSTRAP_SERVERS_CONFIG to kafkaProperties.bootstrapService,
            ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG to StringSerializer::class.java,
            ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG to JsonSerializer::class.java,
        )

        return DefaultKafkaProducerFactory(props)
    }

    @Bean
    fun kafkaTemplate(
        producerFactory: ProducerFactory<String, ProcessingEvent>
    ) = KafkaTemplate(producerFactory)
}

 kafkaTemplate.send(ProducerRecord(KAFKA_TOPIC, ProcessingEvent("asd")))

In the debugger I see that why valueSerializer remained StringSerializer
Why?

**Comment by KirillKurdyukov** [comment]
![image](https://user-images.githubusercontent.com/62187122/199523778-5094fa12-4d01-45a3-8b23-012eb7083fdf.png)

**Comment by KirillKurdyukov** [comment]
![image](https://user-images.githubusercontent.com/62187122/199524064-21b4519c-bd5c-45ae-8889-d4e51fa67ad8.png)
