### ISSUE TITLE
DEBUG org.apache.kafka.common.network.Selector - Connection with /10.4.100.206 disconnected

### ISSUE THREAD

**Issue by deatharvest** [spring-projects/spring-kafka#252]
hi, when I start my program with spring kafka,I failed to create connect.

the kafka server is start,where should i check for my code?

the debug log
```
20:21:44.111 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-kafka-consumer-1] DEBUG org.apache.kafka.clients.NetworkClient - Node -1 disconnected.
20:21:44.114 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-kafka-consumer-1] DEBUG org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient - Cancelled GROUP_COORDINATOR request ClientRequest(expectResponse=true, callback=org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler@b03e9f, request=RequestSend(header={api_key=10,api_version=0,correlation_id=0,client_id=consumer-1}, body={group_id=helloworld}), createdTimeMs=1489321283073, sendTimeMs=0) with correlation id 0 due to node -1 being disconnected
20:21:44.115 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-kafka-consumer-1] DEBUG org.apache.kafka.clients.NetworkClient - Give up sending metadata request since no node is available
20:21:44.216 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-kafka-consumer-1] DEBUG org.apache.kafka.clients.NetworkClient - Initialize connection to node -1 for sending metadata request
20:21:44.216 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-kafka-consumer-1] DEBUG org.apache.kafka.clients.NetworkClient - Initiating connection to node -1 at 10.4.100.206:9092.
20:22:05.217 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-kafka-consumer-1] DEBUG org.apache.kafka.common.network.Selector - Connection with /10.4.100.206 disconnected
java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:744)
	at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:51)
	at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:73)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:323)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:291)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:260)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:209)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:148)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:136)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:197)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:248)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1013)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:979)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:532)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by deatharvest** [comment]
I change kafka server to my computer,it's work well. maybe my server has some problem

**Comment by artembilan** [comment]
Looks like the question (or maybe problem?)  is out of Spring Kafka responsibility:
```
Give up sending metadata request since no node is available
```
Your application just can't see the Kafka Broker.

Please, ask the question in the Apache Kafka community.
