### ISSUE TITLE
Offset commit failed on partition WEBSITE-0 at offset 3: The server experienced an unexpected error when processing the request 

### ISSUE THREAD

**Issue by Zb1649129135** [spring-projects/spring-kafka#2774]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.4.4

**Describe the bug**

Exception thrown by springboot2.1.5
`2023-08-11 13:31:36,756 [Consumer clientId=consumer-5, groupId=WEBSITE] Offset commit failed on partition WEBSITE-0 at offset 3: The server experienced an unexpected error when processing the request 
2023-08-11 13:31:36,759 [Consumer clientId=consumer-5, groupId=WEBSITE] Offset commit with offsets {WEBSITE-0=OffsetAndMetadata{offset=3, metadata=''}, WEBSITE-3=OffsetAndMetadata{offset=2, metadata=''}, WEBSITE-4=OffsetAndMetadata{offset=3, metadata=''}, WEBSITE-1=OffsetAndMetadata{offset=3, metadata=''}, WEBSITE-2=OffsetAndMetadata{offset=3, metadata=''}} failed 
org.apache.kafka.common.KafkaException: Unexpected error in commit: The server experienced an unexpected error when processing the request 
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:874) 
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:821) 
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:894) 
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:874) 
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:204) 
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:167) 
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:127) 
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:586) 
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:400) 
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:303) 
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242) 
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1247) 
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1187) 
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154) 
	at com.supwisdom.message.center.consumer.Consumer.run(Consumer.java:96) 
	at java.lang.Thread.run(Thread.java:748) `

**Comment by garyrussell** [comment]
This has nothing to do with Spring - all communication with Kafka is via the kafka-clients. You should probably look at the server logs to see if there are any clues there.

Furthermore, Boot 2.1.x and Spring for Apache Kafka 2.4.x are no longer supported.

https://spring.io/projects/spring-boot#support

https://spring.io/projects/spring-kafka#support
