### ISSUE TITLE
Hung Thread - org.springframework.kafka.KafkaException

### ISSUE THREAD

**Issue by sujithramanathan** [spring-projects/spring-kafka#2999]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

2.5.3.RELEASE

**Describe the bug**
We are using ConcurrentMessageListenerContainer where we have a single pod and all our concurrent threads are running in the same pod. We have a maintenance period daily around 1 - 2 hrs in the midnight where internet may go down on all of our backend POS machines. 
We observed that java.net.UnknownHostException thrown due to Internet outage. Once the internet is restored mostly all of our consumers are started working but unluckily one of consumer thread is failed to seek a message (Happens intermittently) and throws

org.springframework.kafka.KafkaException: Seek to current after exception; nested exception is org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before successfully committing offsets {yuvees.pricetag.discount.store2435-4=OffsetAndMetadata{offset=549147, leaderEpoch=null, metadata=''}}, 

Lets say i have topic called purchase with 5 partitions and my consumer group called yuvees with 5 concurrent threads.

Lets assume now the internet has been restored so all my 5 threads will connect to all 5 partitions. unfortunately my 5th thread is seeking for a offset and timed out after 60000ms, Within that 60000ms the heart beat is failed for the thread-5 and it is kicked out of the consumer group, Once hearbeat is failed rebalance will happen and my thread-4 will connect to the 5th partition. 

Now lets assume 60000ms is completed and thread-5 is thrown with TimeoutException. Here the thread-5 is not killed in 
ConcurrentMessageListenerContainer but the thread-5 is not active in the kafka consumer group and thread-5 is trying seek the same offset again and again. 

Observations.

1.  thread-5 with throw org.apache.kafka.common.errors.TimeoutException and keep on running after every 1 minute, Even we have seen it is trying to seek the offset which are already expired in kafka topic.
2. If the thread-5 is keep on running then CPU is 100% utilized and it is impacting other applications.

**To Reproduce**

Unable to reproduce in any of the test environments.

**Expected behavior**

The thread should get killed and a new thread created and join to the active consumer group.

**Sample**

StackTrace.

org.springframework.kafka.KafkaException: Seek to current after exception; nested exception is org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before successfully committing offsets {yuvees.pricetag.discount.store2435-4=OffsetAndMetadata{offset=549147, leaderEpoch=null, metadata=''}}
	at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:157)
	at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:103)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:1897)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1796)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1723)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1620)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1350)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1066)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:974)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before successfully committing offsets {yuvees.pricetag.discount.store2435-4=OffsetAndMetadata{offset=549147, leaderEpoch=null, metadata=''}}
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:1912)
	... 10 common frames omitted
Caused by: org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before successfully committing offsets {yuvees.pricetag.discount.store2435-4=OffsetAndMetadata{offset=549147, leaderEpoch=null, metadata=''}}

**Comment by sobychacko** [comment]
@sujithramanathan `2.5.3.RELEASE` is a very old release that is entirely out of both [OSS and commercial support](https://spring.io/projects/spring-kafka/#support) at this point. Could you upgrade to the latest GA or one of the OSS-supported versions and try this again?

**Comment by sobychacko** [comment]
@sujithramanathan, Any updates on this?

**Comment by sobychacko** [comment]
Closing the issue due to lack of activity. If there is any new development, feel free to re-open.
