### ISSUE TITLE
GraalVM compiled version of Spring Kafka with Protobuf send a invalid Protobuf to Kafka

### ISSUE THREAD

**Issue by mmuniz75** [spring-projects/spring-kafka#3098]
**Spring Kafka 3.1**

In the JVM version everything works fine, the issue is just in compiled version.

The code example with all prereqs steps are in :  https://github.com/mmuniz75/producer_poc_graalvm

ps : You need a local Kafka and Schema Registry server before run the steps, all is explained in code example.

Steps to reproduce the issue:

 -  git clone https://github.com/mmuniz75/producer_poc_graalvm.git
 - cd producer_poc_graalvm
 - sudo chmod +x gradlew
 - ./gradlew nativeCompile
 -  ./plates-producer/build/native/nativeCompile/./plates-producer

The issue is not in consumer is in the producer. Because producer not send the correct protobuf to Kafka consumer it will throw this error :

```
java.lang.IllegalStateException: This error handler cannot process 'SerializationException's directly; please consider configuring an 'ErrorHandlingDeserializer' in the value and/or key deserializer
        at org.springframework.kafka.listener.DefaultErrorHandler.handleOtherException(DefaultErrorHandler.java:192) ~[na:na]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.handleConsumerException(KafkaMessageListenerContainer.java:1943) ~[na:na]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1374) ~[na:na]
        at java.base@17.0.9/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
        at java.base@17.0.9/java.lang.Thread.run(Thread.java:842) ~[plates-producer.exe:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807) ~[plates-producer.exe:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:179) ~[na:na]
Caused by: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition plates-0 at offset 660. If needed, please seek past the record to continue consumption.
        at org.apache.kafka.clients.consumer.internals.CompletedFetch.parseRecord(CompletedFetch.java:309) ~[na:na]
        at org.apache.kafka.clients.consumer.internals.CompletedFetch.fetchRecords(CompletedFetch.java:263) ~[na:na]
        at org.apache.kafka.clients.consumer.internals.AbstractFetch.fetchRecords(AbstractFetch.java:340) ~[plates-producer.exe:na]
        at org.apache.kafka.clients.consumer.internals.AbstractFetch.collectFetch(AbstractFetch.java:306) ~[plates-producer.exe:na]
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1235) ~[plates-producer.exe:na]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1186) ~[plates-producer.exe:na]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1159) ~[plates-producer.exe:na]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollConsumer(KafkaMessageListenerContainer.java:1658) ~[na:na]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doPoll(KafkaMessageListenerContainer.java:1633) ~[na:na]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1430) ~[na:na]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1322) ~[na:na]
        ... 4 common frames omitted
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Protobuf message for id 1
        at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:228) ~[plates-producer.exe:na]
        at io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer.deserialize(KafkaProtobufDeserializer.java:84) ~[plates-producer.exe:na]
        at io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer.deserialize(KafkaProtobufDeserializer.java:28) ~[plates-producer.exe:na]
        at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:73) ~[plates-producer.exe:na]
        at org.apache.kafka.clients.consumer.internals.CompletedFetch.parseRecord(CompletedFetch.java:300) ~[na:na]
        ... 14 common frames omitted
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value java.lang.reflect.InvocationTargetException for configuration Not a valid protobuf builder
        at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:196) ~[plates-producer.exe:na]
        ... 18 common frames omitted

```

**Comment by artembilan** [comment]
@mmuniz75 ,

Please, consider to edit your comment the way that stack trace becomes readable.

See GH Markdown formatting rules: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by sobychacko** [comment]
@mmuniz75 I followed your instructions after cloning the sample app repo, and I see that the native executable works as expected. 

Here is more information:
```
java -version
openjdk version "17.0.9" 2023-10-17 LTS
OpenJDK Runtime Environment GraalVM 22.3.4 (build 17.0.9+11-LTS)
OpenJDK 64-Bit Server VM GraalVM 22.3.4 (build 17.0.9+11-LTS, mixed mode, sharing)
```
```
/gradlew nativeCompile
./plates-producer/build/native/nativeCompile/./plates-producer
```
and I see the following output:
```
2024-03-05T17:59:58.172-05:00  INFO 74270 --- [   scheduling-1] l.p.p.producer.PlatesCheckerProducer     : Sending 5 plates to topic
Received plate: SIE7D3K
Received plate: SIE7D4K
Received plate: SIE7D5K
Received plate: SIE7D6K
Received plate: SIE7D7K
2024-03-05T18:00:08.174-05:00  INFO 74270 --- [   scheduling-1] l.p.p.producer.PlatesCheckerProducer     : Sending 5 plates to topic
Received plate: SIE7D3K
Received plate: SIE7D4K
Received plate: SIE7D5K
Received plate: SIE7D6K
Received plate: SIE7D7K
...
...
```


The only change I made in the app was to replace where I run Kafka locally (`localhost:9092`). 

I wonder if you are running into some config issues causing the error.

**Comment by sobychacko** [comment]
I was running these: https://github.com/spring-cloud/spring-cloud-stream/tree/main/tools/kafka/docker-compose

**Comment by artembilan** [comment]
> at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:179)

So, that's on Windows. 
Perhaps there is some discrepancy how Protobuf is compiled to native image on different platforms.
I mean I have an experience building native images on Windows, but it always worked same way as on Linux or MacOS.

I'll play with your sample application today.

Note: doesn't look like the problem comes from Spring at all.
We are looking into this just for an academic purpose to learn something ourselves.

Thanks

**Comment by mmuniz75** [comment]
My dev machine is Windows , sometimes I test in a MACOS and in Ubuntu inside Linux, I will try that.
In fact the our enviroment is Linux so I hope it works well in the real enviriment, going to test that too soon
Thanks for all this tries

**Comment by artembilan** [comment]
Works for me on Windows as well:
```
2024-03-06T11:55:50.609-05:00  INFO 14796 --- [ntainer#0-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : muniz_local: partitions assigned: [plates-0]
Received plate: SIE7D3K
Received plate: SIE7D4K
Received plate: SIE7D5K
Received plate: SIE7D6K
Received plate: SIE7D7K
2024-03-06T11:56:00.433-05:00  INFO 14796 --- [   scheduling-1] l.p.p.producer.PlatesCheckerProducer     : Sending 5 plates to topic
Received plate: SIE7D3K
Received plate: SIE7D4K
Received plate: SIE7D5K
Received plate: SIE7D6K
Received plate: SIE7D7K
2024-03-06T11:56:10.428-05:00  INFO 14796 --- [   scheduling-1] l.p.p.producer.PlatesCheckerProducer     : Sending 5 plates to topic
Received plate: SIE7D3K
Received plate: SIE7D4K
Received plate: SIE7D5K
Received plate: SIE7D6K
Received plate: SIE7D7K
```

**Comment by mmuniz75** [comment]
I tested in Ubuntu and it works , I have the same issue in GRPC just works in Linux, but thats ok this is our env.
Closing the issue, thank you for the effort
