### ISSUE TITLE
[Question] KafkaMessageListenerContainer: Deserialization exception results in ListenerConsumer stuck in loop

### ISSUE THREAD

**Issue by murphd40** [spring-projects/spring-kafka#316]
## Description

We are using Kafka and Avro send messages between microservices. After a change to the avro schema, a microservice using an older version of the schema was unable to deserialize a message:

````log
2017-05-15 14:27:55.816 ERROR 6860 --- [afka-consumer-1] essageListenerContainer$ListenerConsumer : Container exception

org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition abcd-2 at offset 22
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 41
Caused by: org.apache.avro.AvroTypeException: Found TestPayload, expecting union
	at org.apache.avro.io.ResolvingDecoder.doAction(ResolvingDecoder.java:292) ~[avro-1.7.7.jar:1.7.7]
	at org.apache.avro.io.parsing.Parser.advance(Parser.java:88) ~[avro-1.7.7.jar:1.7.7]
	at org.apache.avro.io.ResolvingDecoder.readIndex(ResolvingDecoder.java:267) ~[avro-1.7.7.jar:1.7.7]
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:155) ~[avro-1.7.7.jar:1.7.7]
	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:193) ~[avro-1.7.7.jar:1.7.7]
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:183) ~[avro-1.7.7.jar:1.7.7]
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151) ~[avro-1.7.7.jar:1.7.7]
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:142) ~[avro-1.7.7.jar:1.7.7]
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:131) ~[kafka-avro-serializer-3.0.1.jar:na]
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:104) ~[kafka-avro-serializer-3.0.1.jar:na]
````

The issue is that the microservice was unable to move past this message and was stuck in a loop trying to deserialize. It seems that the offset is not being updated after a failure at this level.

## Question

* Is this expected behaviour?
* If so, is there a way to move past failing messages such as these so that the microservice can continue?

Thanks

**Comment by garyrussell** [comment]
This is a question for kafka itself - Spring doesn't see the message until after it has been deserialized so there' nothing it can do to update the offset.

You could put a wrapper around the Avro deserializer and catch the exception - and deserialize to some "special" value to the listener to indicate there was a deserialization problem.

**Comment by murphd40** [comment]
Okay that makes sense. Thanks for the response :+1: 

Feel free to close issue
