### ISSUE TITLE
Embedded Kafka throws NoSuchFileException 

### ISSUE THREAD

**Issue by danroxha** [spring-projects/spring-kafka#3225]
## In what version(s) of Spring for Apache Kafka are you seeing this issue?

Spring 3.2.5 ~  3.2.6-SNAPSHOT

## Describe the bug
EmbeddedKafka throws an IO exception

## Reproduce

- Create a new project  3.2.6 (https://start.spring.io) [JDK 17, Kotlin, Gradle - Groovy ]
- Add org.springframework.kafka:spring-kafka dependecy (Spring for Apache Kafka)
- Configure ```@EmbeddedKafka```, Inject KafkaTemplate property
- Run ./gradlew test

## Demo :
- https://github.com/danroxha/spring-test-kafka

## Sample
```sh
2024-04-29T22:45:40.223-03:00  INFO 1781 --- [error] [-raft-io-thread] k.raft.KafkaRaftManager$RaftIoThread     : [kafka-0-raft-io-thread]: Stopped
2024-04-29T22:45:40.223-03:00  INFO 1781 --- [error] [-kit-executor-1] k.raft.KafkaRaftManager$RaftIoThread     : [kafka-0-raft-io-thread]: Shutdown completed
2024-04-29T22:45:40.229-03:00  INFO 1781 --- [error] [-kit-executor-1] kafka.raft.RaftSendThread                : [kafka-0-raft-outbound-request-thread]: Shutting down
2024-04-29T22:45:40.230-03:00  INFO 1781 --- [error] [-request-thread] kafka.raft.RaftSendThread                : [kafka-0-raft-outbound-request-thread]: Stopped
2024-04-29T22:45:40.230-03:00  INFO 1781 --- [error] [-kit-executor-1] kafka.raft.RaftSendThread                : [kafka-0-raft-outbound-request-thread]: Shutdown completed
2024-04-29T22:45:40.234-03:00 ERROR 1781 --- [error] [-kit-executor-1] o.a.k.s.i.log.LogDirFailureChannel       : Error while renaming dir for __cluster_metadata-0 in dir /tmp/kafka-11774975837212516610/controller_0

java.nio.file.NoSuchFileException: /tmp/kafka-11774975837212516610/controller_0/__cluster_metadata-0/00000000000000000013.snapshot
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181) ~[na:na]
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298) ~[na:na]
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357) ~[na:na]
        at org.apache.kafka.storage.internals.log.ProducerStateManager.writeSnapshot(ProducerStateManager.java:717) ~[kafka-storage-3.6.2.jar:na]
        at org.apache.kafka.storage.internals.log.ProducerStateManager.takeSnapshot(ProducerStateManager.java:472) ~[kafka-storage-3.6.2.jar:na]
        at kafka.log.UnifiedLog.$anonfun$close$3(UnifiedLog.scala:657) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.log.UnifiedLog.close(UnifiedLog.scala:1845) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.raft.KafkaMetadataLog.close(KafkaMetadataLog.scala:505) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.raft.KafkaRaftManager.$anonfun$shutdown$7(RaftManager.scala:203) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:66) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.raft.KafkaRaftManager.shutdown(RaftManager.scala:203) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.server.SharedServer.$anonfun$ensureNotRaftLeader$2(SharedServer.scala:321) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:66) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.server.SharedServer.$anonfun$ensureNotRaftLeader$1(SharedServer.scala:321) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.server.SharedServer.$anonfun$ensureNotRaftLeader$1$adapted(SharedServer.scala:320) ~[kafka_2.13-3.6.2.jar:na]
        at scala.Option.foreach(Option.scala:437) ~[scala-library-2.13.11.jar:na]
        at kafka.server.SharedServer.ensureNotRaftLeader(SharedServer.scala:320) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.server.ControllerServer.shutdown(ControllerServer.scala:422) ~[kafka_2.13-3.6.2.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

2024-04-29T22:45:40.235-03:00  WARN 1781 --- [error] [-kit-executor-1] kafka.utils.CoreUtils$                   : Error while renaming dir for __cluster_metadata-0 in dir /tmp/kafka-11774975837212516610/controller_0

org.apache.kafka.common.errors.KafkaStorageException: Error while renaming dir for __cluster_metadata-0 in dir /tmp/kafka-11774975837212516610/controller_0
Caused by: java.nio.file.NoSuchFileException: /tmp/kafka-11774975837212516610/controller_0/__cluster_metadata-0/00000000000000000013.snapshot
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181) ~[na:na]
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298) ~[na:na]
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357) ~[na:na]
        at org.apache.kafka.storage.internals.log.ProducerStateManager.writeSnapshot(ProducerStateManager.java:717) ~[kafka-storage-3.6.2.jar:na]
        at org.apache.kafka.storage.internals.log.ProducerStateManager.takeSnapshot(ProducerStateManager.java:472) ~[kafka-storage-3.6.2.jar:na]
        at kafka.log.UnifiedLog.$anonfun$close$3(UnifiedLog.scala:657) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.log.UnifiedLog.close(UnifiedLog.scala:1845) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.raft.KafkaMetadataLog.close(KafkaMetadataLog.scala:505) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.raft.KafkaRaftManager.$anonfun$shutdown$7(RaftManager.scala:203) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:66) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.raft.KafkaRaftManager.shutdown(RaftManager.scala:203) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.server.SharedServer.$anonfun$ensureNotRaftLeader$2(SharedServer.scala:321) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:66) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.server.SharedServer.$anonfun$ensureNotRaftLeader$1(SharedServer.scala:321) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.server.SharedServer.$anonfun$ensureNotRaftLeader$1$adapted(SharedServer.scala:320) ~[kafka_2.13-3.6.2.jar:na]
        at scala.Option.foreach(Option.scala:437) ~[scala-library-2.13.11.jar:na]
        at kafka.server.SharedServer.ensureNotRaftLeader(SharedServer.scala:320) ~[kafka_2.13-3.6.2.jar:na]
        at kafka.server.ControllerServer.shutdown(ControllerServer.scala:422) ~[kafka_2.13-3.6.2.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

2024-04-29T22:45:40.241-03:00  INFO 1781 --- [error] [-kit-executor-1] kafka.network.SocketServer               : [SocketServer listenerType=CONTROLLER, nodeId=0] Stopping socket server request processors
2024-04-29T22:45:40.248-03:00  INFO 1781 --- [error] [-kit-executor-1] kafka.network.SocketServer               : [SocketServer listenerType=CONTROLLER, nodeId=0] Stopped socket server request processors

```

**Comment by sobychacko** [comment]
@danroxha We also noticed this issue in some of our builds. We will investigate further and let you know.

**Comment by artembilan** [comment]
When I added `@DirtiesContext` into your `ErrorApplicationTests` the mentioned error is gone.
I see similar error even with `@EmbeddedKafka(kraft = false)`:
```
2024-04-30T11:08:29.404-04:00 ERROR 33104 --- [error] [e-shutdown-hook] org.apache.kafka.test.TestUtils          : Error deleting C:\Users\abilan\AppData\Local\Temp\kafka-1671540982703755288
java.nio.file.FileSystemException: C:\Users\abilan\AppData\Local\Temp\kafka-1671540982703755288\version-2\log.1: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92) ~[na:na]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[na:na]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275) ~[na:na]
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105) ~[na:na]
	at java.base/java.nio.file.Files.delete(Files.java:1152) ~[na:na]
	at org.apache.kafka.common.utils.Utils$1.visitFile(Utils.java:910) ~[kafka-clients-3.6.2.jar:na]
	at org.apache.kafka.common.utils.Utils$1.visitFile(Utils.java:899) ~[kafka-clients-3.6.2.jar:na]
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811) ~[na:na]
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882) ~[na:na]
	at org.apache.kafka.common.utils.Utils.delete(Utils.java:899) ~[kafka-clients-3.6.2.jar:na]
	at org.apache.kafka.test.TestUtils.lambda$tempDirectory$0(TestUtils.java:256) ~[kafka-clients-3.6.2-test.jar:na]
```

So, apparently the alive application context keeps Kafka clients opened which prevents the broker to be stopped properly.
The error is gone with the mentioned `@DirtiesContext` even in ZK mode.

Sounds like we need to come up with the solution what to do with embedded Kafka brokers when there is no `@DirtiesContext`.
Or another idea is to mark `@EmbeddedKafka` with this `@DirtiesContext` to always close application contexts under testing when we deal with an embedded Kafka...

**Comment by artembilan** [comment]
So, after some digging I see what is going.
(At least that is for me on Windows).
Spring and Kafka register `Runtime.getRuntime().addShutdownHook()` which are performed in parallel, when JVM exits.
And apparently some files in Kafka are still busy by the clients in the application. Therefore I got the `Error deleting`.
Your error is different, however I still see that it comes on shutdown:
```
2024-04-29T22:45:40.223-03:00  INFO 1781 --- [error] [-raft-io-thread] k.raft.KafkaRaftManager$RaftIoThread     : [kafka-0-raft-io-thread]: Stopped
2024-04-29T22:45:40.223-03:00  INFO 1781 --- [error] [-kit-executor-1] k.raft.KafkaRaftManager$RaftIoThread     : [kafka-0-raft-io-thread]: Shutdown completed
2024-04-29T22:45:40.229-03:00  INFO 1781 --- [error] [-kit-executor-1] kafka.raft.RaftSendThread                : [kafka-0-raft-outbound-request-thread]: Shutting down
2024-04-29T22:45:40.230-03:00  INFO 1781 --- [error] [-request-thread] kafka.raft.RaftSendThread                : [kafka-0-raft-outbound-request-thread]: Stopped
2024-04-29T22:45:40.230-03:00  INFO 1781 --- [error] [-kit-executor-1] kafka.raft.RaftSendThread                : [kafka-0-raft-outbound-request-thread]: Shutdown completed
2024-04-29T22:45:40.234-03:00 ERROR 1781 --- [error] [-kit-executor-1] o.a.k.s.i.log.LogDirFailureChannel       : Error while renaming dir for __cluster_metadata-0 in dir /tmp/kafka-11774975837212516610/controller_0
```

So, might be the fact of similar parallel shutdowns.

I don't think we need to do anything since it happens only once in the end when JVM dies and therefore all those tmp files are void for subsequent runs.

**Comment by sobychacko** [comment]
@danroxha, did you verify Artem's suggestion on your end? Can we close the issue? We cleaned up our internal test, throwing this warning with this same fix, which resolved it.

**Comment by danroxha** [comment]
Yes, Artem's suggestion was effective, but I think it would be interesting to update the documentation and add a warning about this. As the error returns an error code in the terminal, some builds may fail even if the build + tests are OK.

**Comment by sobychacko** [comment]
Good point - we can add a note in the docs.
