### ISSUE TITLE
Authorization via keyTab file in Windows (absolute windows file path)

### ISSUE THREAD

**Issue by almirus** [spring-projects/spring-kafka#3274]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**
3.1.5

**Describe the bug**

When specifying the keyTab parameter (in sasl.jaas.config) containing an absolute (normalized) path to a file "`C:\ra_projects\Java\apache-tomcat-10.1.10\conf\keystore\tkafka.keytab`" in the **Windows operating system**, after parsing the parameters, this file path becomes broken and starts containing the string "`C:a_projectsJavapache-tomcat-10.1.10confkeystore	kafka.keytab`". After attempting to send a message to Kafka, the NetworkClient attempts to authenticate, but since the file with keys has not been loaded (no any errors about the keyTab file is not found!), I get an exception:

`Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user`

**To Reproduce**
```
@Bean
public ProducerFactory<String, String> producerFactory() {
// for Windows instance C:\ra_projects\Java\apache-tomcat-10.1.10\conf\keystore\tkafka.keytab
String keyTabFile = Paths.get(environment.getProperty("catalina.base") + jmServiceDao.getKafkaKeytabLocation()).toAbsolutePath().normalize().toString(); 
String principal=  jmServiceDao.getKafkaPrincipal()
....
props.put("sasl.jaas.config", """
                    com.sun.security.auth.module.Krb5LoginModule required serviceName="kafka"
                    useKeyTab=true debug=true useTicketCache=false storeKey=true keyTab="%s" principal="%s";
                    """.formatted(keyTabFile, principal));
return new DefaultKafkaProducerFactory<>(props);
```
**Expected behavior**

Sent message to Kafka

**Comment by almirus** [comment]
Okay, I found the place where the string destruction occurs (in the parameter sasl.jaas.config), which contains the path to the keyTab file - here [    public JaasConfig(String loginContextName, String jaasConfigParams) {](https://github.com/apache/kafka/blob/d585a494a4871eaecdddf98f8655b8f30c5bd834/clients/src/main/java/org/apache/kafka/common/security/JaasConfig.java#L52)

After parsing the string, the path 'C:\ra_projects\Java\apache-tomcat-10.1.10\conf\keystore\tkafka.keytab' turns into 'C:a_projectsJava�pache-tomcat-10.1.10confkeystore	kafka.keytab'. This happens without warnings or errors; the keyTab field simply starts containing the incorrect path.

This is not a problem with SpringKafka; it's an issue with Apache Kafka. However, there is no warning control anywhere stating that the path to the keyTab for Windows paths should be escaped; otherwise, there will be an error, as shown below. However, it doesn't indicate anything about the file being unreadable because the path to it has become incorrect.
```
rg.apache.kafka.common.KafkaException: Failed to construct kafka producer
            at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:459)
            at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:287)
            at org.springframework.kafka.core.DefaultKafkaProducerFactory.createRawProducer(DefaultKafkaProducerFactory.java:913)
            at org.springframework.kafka.core.DefaultKafkaProducerFactory.createKafkaProducer(DefaultKafkaProducerFactory.java:812)
            at org.springframework.kafka.core.DefaultKafkaProducerFactory.doCreateProducer(DefaultKafkaProducerFactory.java:779)
            at org.springframework.kafka.core.DefaultKafkaProducerFactory.createProducer(DefaultKafkaProducerFactory.java:754)
            at org.springframework.kafka.core.DefaultKafkaProducerFactory.createProducer(DefaultKafkaProducerFactory.java:748)
            at org.springframework.kafka.core.KafkaTemplate.getTheProducer(KafkaTemplate.java:941)
            at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:790)
            at org.springframework.kafka.core.KafkaTemplate.observeSend(KafkaTemplate.java:768)
            at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:551)
            at com.technology.scoring.jmessageservice.service.JMServiceImpl.sendMessage(JMServiceImpl.java:61)
            at com.technology.scoring.jmessageservice.controller.JMessageServiceController.sendMessage(JMessageServiceController.java:30)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:568)
            at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:254)
            at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:182)
            at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
            at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)
            at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)
            at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
            at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
            at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
            at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
            at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
            at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
            at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
            at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
            at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
            at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
            at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
            at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:124)
            at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:99)
            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
            at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:117)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
            at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
            at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
            at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
            at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
            at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
            at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
            at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
            at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
            at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
            at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
            at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
            at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
            at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
            at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
            at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
            at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
            at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
            at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.KafkaException: Failed to create new NetworkClient
            at org.apache.kafka.clients.ClientUtils.createNetworkClient(ClientUtils.java:245)
            at org.apache.kafka.clients.ClientUtils.createNetworkClient(ClientUtils.java:159)
            at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:507)
            at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:448)
            ... 69 common frames omitted
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user
            at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
            at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
            at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
            at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:117)
            at org.apache.kafka.clients.ClientUtils.createNetworkClient(ClientUtils.java:217)
            ... 72 common frames omitted
Caused by: javax.security.auth.login.LoginException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user. not available to garner  authentication information from the user
            at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:925)
            at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:745)
            at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:597)
            at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
            at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:679)
            at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:677)
            at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
            at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:677)
            at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:587)
            at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60)
            at org.apache.kafka.common.security.kerberos.KerberosLogin.login(KerberosLogin.java:103)
            at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
            at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
            at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
            ... 76 common frames omitted
```

**Comment by artembilan** [comment]
OK. Thanks for more details.
Can you open (or find) a respective ticket against Apache Kafka project by itself?
Does not look like Spring is some how involved in the problem.

>  there is no warning control anywhere stating that the path to the keyTab for Windows paths should be escaped

Again: this is not what Spring for Apache Kafka is responsible for.
If you wish for that warning, please, ask Apache Kafka project.
It would be a bit awkward to warn in Spring docs for something what better would be documented in the client library.
This way even non-Spring users of that library would benefit.

Closed as `Invalid`
