### ISSUE TITLE
use value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer occurs error

### ISSUE THREAD

**Issue by tjqiulu** [spring-projects/spring-kafka#333]
i  use value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer in my configer file and want to be consumer Json format data, it occurs error
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-06-03 23:36:38.507 ERROR 11964 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.kafka.config.internalKafkaListenerEndpointRegistry'; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.gemalto.wesim.RumConsumingApplication.main(RumConsumingApplication.java:10) [classes/:na]
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:717) ~[kafka-clients-0.10.2.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:566) ~[kafka-clients-0.10.2.0.jar:na]
	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createKafkaConsumer(DefaultKafkaConsumerFactory.java:106) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createKafkaConsumer(DefaultKafkaConsumerFactory.java:90) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createKafkaConsumer(DefaultKafkaConsumerFactory.java:95) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createConsumer(DefaultKafkaConsumerFactory.java:86) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.<init>(KafkaMessageListenerContainer.java:326) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer.doStart(KafkaMessageListenerContainer.java:193) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:202) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.kafka.listener.ConcurrentMessageListenerContainer.doStart(ConcurrentMessageListenerContainer.java:125) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:202) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.startIfNecessary(KafkaListenerEndpointRegistry.java:287) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.start(KafkaListenerEndpointRegistry.java:236) ~[spring-kafka-1.2.1.RELEASE.jar:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 12 common frames omitted
Caused by: org.apache.kafka.common.KafkaException: Could not instantiate class org.springframework.kafka.support.serializer.JsonDeserializer
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:340) ~[kafka-clients-0.10.2.0.jar:na]
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:203) ~[kafka-clients-0.10.2.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:645) ~[kafka-clients-0.10.2.0.jar:na]
	... 25 common frames omitted
Caused by: java.lang.IllegalAccessException: Class org.apache.kafka.common.utils.Utils can not access a member of class org.springframework.kafka.support.serializer.JsonDeserializer with modifiers "protected"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:109) ~[na:1.7.0_60]
	at java.lang.Class.newInstance(Class.java:368) ~[na:1.7.0_60]
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:338) ~[kafka-clients-0.10.2.0.jar:na]
	... 27 common frames omitted

but i use String Deserializer is ok.
i use springboot 1.5.3 with 1.2.1 spring kafka
my config snapshot:
spring:
  kafka:
    template:
      default-topic: MT_TOPIC
    bootstrap-servers: localhost:9092
    consumer:
      group-id: GTO
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

my consumer code snapshot:

```java
@KafkaListener(topics = "${kafka.topic.mo}")
	public void moreceive(MOReq message)  {
		LOGGER.info("received mo message='{}'", message);
```

**Comment by garyrussell** [comment]
The deserializer can't be used as a property; it needs to be constructed with a target type.

See [this sample - specifically app5](https://github.com/SpringOnePlatform2016/grussell-spring-kafka#app5 for an example of how to use it. The [consumer factory is configured here](https://github.com/SpringOnePlatform2016/grussell-spring-kafka/blob/master/s1p-kafka/src/main/java/org/s1p/JsonConfiguration.java#L66).

**Comment by garyrussell** [comment]
Also see app6 there - which uses a more flexible way to decode the JSON; in your case, the framework would infer the type to be `MOReq` from the method signature.
