### ISSUE TITLE
Consumer get stuck ocassionally on rebalancing

### ISSUE THREAD

**Issue by tomek0021** [spring-projects/spring-kafka#350]
Hi guys,

I think I might have found an issue with consumer, I have a test that is setting up 3 nodes embedded cluster, 10 producer threads, 2 consumer threads, after sending and receiving some messages I am bringing down 1 node and from time to time my consumers just stop receiving messages. I did thread dump and what I got on consumer threads is:

```
"transactional_1" #130 prio=5 os_prio=31 tid=0x00007fbbad7f7000 nid=0x13507 runnable [0x000070000dfcb000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006d88dbfb0> (a sun.nio.ch.Util$3)
	- locked <0x00000006d88dbfa0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006d88dbf50> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.apache.kafka.common.network.Selector.select(Selector.java:489)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:298)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:349)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:226)
	- locked <0x00000006d88dc068> (a org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:203)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:138)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:216)
	- locked <0x00000006d88dc0a0> (a org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:575)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1124)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.ackImmediate(KafkaMessageListenerContainer.java:702)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.processAck(KafkaMessageListenerContainer.java:683)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.handleAcks(KafkaMessageListenerContainer.java:675)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.processCommits(KafkaMessageListenerContainer.java:802)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:529)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

Looks like ConsumerRebalanceListener in KafkaMessageListenerContainer.ListenerConsumer is using non synchronised kafka's Consumer instance - my consumers are under heavy load so at the time of rebalancing (which is making commits) they are making consumption (poll/syncCommit) which might cause this issue. I have autoCommit disabled and using syncCommit.
I think usage of kafka's Consumer should be synchronised.
Please correct me if I'm wrong.
I'm using 1.2.0.RELEASE version

Thank you in advance.

**Comment by garyrussell** [comment]
>is using non synchronised kafka's Consumer instance

What version are you using?

The consumer is never invoked by anything other than the consumer thread. In the current architecture, the consumer hands messages over to the listener thread. All interactions with the consumer are queued back to the consumer thread.

Since KIP-62 has now been implemented, in 2.0 we only have the consumer thread since heatbeats are now handled by the client in the background.

**Comment by tomek0021** [comment]
Thank you for fast reply, I'm using 1.2.0.RELEASE version (few minutes ago bumped to 1.2.2). 
I'm not sure how it's done in kafka's client but looks like ConsumerRebalanceListener can be invoked by kafka's separate thread when rebalancing occurs. Don't see how ConsumerRebalanceListener could be in same thread as it is kafka's callback on rebalancing notification but maybe I'm wrong.

**Comment by tomek0021** [comment]
I had a look on apache's KafkaConsumer and all methods of it are guarded from multiple thread invocation and if one happens it throws ConcurrentModificationException. So it's not multithreading issue.
Still trying to work out actual root cause but I'm closing this issue. 
Sorry for inconvenience.
