### ISSUE TITLE
Issues : stack_trace":"javax.management.InstanceAlreadyExistsException:   kafka.consumer:type=app-info 

### ISSUE THREAD

**Issue by PoonamGargAgarwal** [spring-projects/spring-kafka#357]
We are consuming data for kafka topic . Our kafka consuming microservices running using docker container on kubernetes. We are running two replicas. We set client.id is our  kubernetes pod name . Still we are having Instance Already Exist Exception.

```
@Bean
public ConcurrentKafkaListenerContainerFactory<String, MoveTOLineItemMessageDTO> kafkaListenerContainerFactory() {
        logger.info("Creating ConcurrentKafkaListenerContainerFactory");
        ConcurrentKafkaListenerContainerFactory<String, MoveTOLineItemMessageDTO> factory =
                new ConcurrentKafkaListenerContainerFactory<>();

        factory.setConsumerFactory(consumerFactory());
        factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.MANUAL_IMMEDIATE);
        
        return factory;
    }
```

**Comment by garyrussell** [comment]
Is that your actual configuration? I would only expect to see that error if the `concurrency` is greater than 1.

That is fixed in 1.2.1 (current 1.2.x is 1.2.2) and 1.1.5 (current 1.1.x is 1.1.6), and 1.0.6.

See https://github.com/spring-projects/spring-kafka/pull/297.

If you are seeing this with the default concurrency (1), please attach a DEBUG log of the container initialization, including spring and kafka log categories.

**Comment by andrey-cabonline** [comment]
I'm having the same issue:

```bash
2017-07-28 09:45:56.629  WARN 6832 --- [           main] o.a.k.c.u.AppInfoParser                  : Error registering AppInfo mbean

javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=adapter-suti-02312f799333a046f05869d766ae80a3-0
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) ~[?:1.8.0_131]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898) ~[?:1.8.0_131]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966) ~[?:1.8.0_131]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) ~[?:1.8.0_131]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) ~[?:1.8.0_131]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[?:1.8.0_131]
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:58) [kafka-clients-0.11.0.0.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:757) [kafka-clients-0.11.0.0.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:602) [kafka-clients-0.11.0.0.jar!/:?]
	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createKafkaConsumer(DefaultKafkaConsumerFactory.java:106) [spring-kafka-1.2.2.RELEASE.jar!/:?]
	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createKafkaConsumer(DefaultKafkaConsumerFactory.java:101) [spring-kafka-1.2.2.RELEASE.jar!/:?]
	at org.springframework.kafka.core.DefaultKafkaConsumerFactory.createConsumer(DefaultKafkaConsumerFactory.java:86) [spring-kafka-1.2.2.RELEASE.jar!/:?]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.<init>(KafkaMessageListenerContainer.java:328) [spring-kafka-1.2.2.RELEASE.jar!/:?]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer.doStart(KafkaMessageListenerContainer.java:193) [spring-kafka-1.2.2.RELEASE.jar!/:?]
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:202) [spring-kafka-1.2.2.RELEASE.jar!/:?]
	at org.springframework.kafka.listener.ConcurrentMessageListenerContainer.doStart(ConcurrentMessageListenerContainer.java:125) [spring-kafka-1.2.2.RELEASE.jar!/:?]
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:202) [spring-kafka-1.2.2.RELEASE.jar!/:?]
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.startIfNecessary(KafkaListenerEndpointRegistry.java:287) [spring-kafka-1.2.2.RELEASE.jar!/:?]
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.start(KafkaListenerEndpointRegistry.java:236) [spring-kafka-1.2.2.RELEASE.jar!/:?]
```
That's config:
```bash
2017-07-28 09:45:56.624  INFO 6832 --- [           main] o.a.k.c.c.ConsumerConfig                 : ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = earliest
	bootstrap.servers = [localhost:9092]
	check.crcs = true
	client.id = adapter-suti-02312f799333a046f05869d766ae80a3-0
	connections.max.idle.ms = 540000
	enable.auto.commit = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = suti-service
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	internal.leave.group.on.close = true
	isolation.level = read_uncommitted
	key.deserializer = class com.cabonline.suti.service.bootstrap.mq.deser.UUIDDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 305000
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class com.cabonline.suti.service.bootstrap.mq.deser.EventWrapperDeserializer
```

and spring config:
```java
    @Bean
    KafkaListenerContainerFactory<ConcurrentMessageListenerContainer<UUID, EventWrapperDeserializer>>
    kafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<UUID, EventWrapperDeserializer> factory =
                new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(consumerFactory());
        factory.setConcurrency(1);
        factory.getContainerProperties().setPollTimeout(100);
        factory.setAutoStartup(true);

        return factory;
    }

    @Bean
    public ConsumerFactory<UUID, EventWrapperDeserializer> consumerFactory() {
        String clientId = applicationId.replaceAll("[^A-Za-z0-9]", "-");
        Map<String, Object> props = new HashMap<>();
        props.put(CommonClientConfigs.BOOTSTRAP_SERVERS_CONFIG, kafkaConfig.getBrokers());
        props.put(ConsumerConfig.GROUP_ID_CONFIG, CONSUMER_GROUP);
        props.put(ConsumerConfig.CLIENT_ID_CONFIG, clientId);
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, UUIDDeserializer.class);
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, EventWrapperDeserializer.class);
        props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");

        return new DefaultKafkaConsumerFactory<>(props);
    }
```
The same happens if I do `factory.setConcurrency(3);`

**Comment by artembilan** [comment]
```
  props.put(ConsumerConfig.CLIENT_ID_CONFIG, clientId);
```
And then I'm sure you have several `@KafkaListener` methods. 
Since all of them use the same `kafkaListenerContainerFactory` that is not a surprise that the target `client.id` is the same as well.

You may consider to disable JMX for Kafka or use different ` KafkaListenerContainerFactory` for different `@KafkaListener` with different `client.id`.

Looks like Apache Kafka didn't design `client.id` to be shared between several `Consumer`s...

**Comment by andrey-cabonline** [comment]
Yes, that makes sense - I do have multiple @KafkaListener methods. I'll try to use different kafkaListenerContainerFactoryies.

> You may consider to disable JMX for Kafka
Do you mean JMX in Kafka itself or in spring application? If second then we use spring-boot with `spring.jmx.enabled=false` so it should be disabled.

**Comment by artembilan** [comment]
The code
```
at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:58) [kafka-clients-0.11.0.0.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:757) [kafka-clients-0.11.0.0.jar!/:?]
```
is fully unrelated to the Spring JMX support. So, having `spring.jmx.enabled=false` doesn't help in your case.

Well, looks like `KafkaConsumer` perform JMX registration unconditionally:
```
AppInfoParser.registerAppInfo(JMX_PREFIX, clientId);
```
Where we have a code:
```
public static void registerAppInfo(String prefix, String id) {
        try {
            ObjectName name = new ObjectName(prefix + ":type=app-info,id=" + id);
            AppInfo mBean = new AppInfo();
            ManagementFactory.getPlatformMBeanServer().registerMBean(mBean, name);
        } catch (JMException e) {
            log.warn("Error registering AppInfo mbean", e);
        }
}
```

What I ca tell you that this exception is indeed a `WARN` log message. 

How about just make that `org.apache.kafka.common.utils` category on the `ERROR` level to forget about this message if you are not interested in the JMX?


Since there is nothing to do from Spring perspective and it's not an issue from our perspective because you simply can end up with the same result when you even just use raw Kafka Client, I'm closing this as *invalid*.

Thanks for your patience.
