### ISSUE TITLE
Spring kafka does not support LinkedIn large message consumers

### ISSUE THREAD

**Issue by hussein-joe** [spring-projects/spring-kafka#359]
I am using spring Kafka to consume message produced by [LinkedIn large message supported Kafka client](https://github.com/linkedin/li-apache-kafka-clients)

Given that this Kafka client always overrides AUTO_OFFSET_RESET_CONFIG to none as shown in its constructor.

```
private LiKafkaConsumerImpl(LiKafkaConsumerConfig configs,
		    Deserializer<K> keyDeserializer,
		    Deserializer<V> valueDeserializer,
		    Deserializer<LargeMessageSegment> largeMessageSegmentDeserializer,
		    Auditor<K, V> consumerAuditor) {
		        _kafkaConsumer = new KafkaConsumer<>(configs.configForVanillaConsumer(),
		        byteArrayDeserializer,
		        byteArrayDeserializer);
	}
Map<String, Object> configForVanillaConsumer() {
		Map<String, Object> newConfigs = new HashMap<>();
		newConfigs.putAll(this.originals());
		newConfigs.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false);
		newConfigs.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "none");
		return newConfigs;
	}
```

So Once I start using batch commit and setting the ENABLE_AUTO_COMMIT_CONFIG to false, it throws the following error:

```
[org.springframework.kafka.KafkaListenerEndpointContainer#0-1-C-1] ERROR o.a.k.c.c.i.ConsumerCoordinator - User provided listener com.linkedin.kafka.clients.consumer.LiKafkaConsumerRebalanceListener for group document-event-consumer failed on partition assignment org.apache.kafka.clients.consumer.NoOffsetForPartitionException: Undefined offset with no reset policy for partition: DocumentEvents-2 at org.apache.kafka.clients.consumer.internals.Fetcher.resetOffset(Fetcher.java:369) at org.apache.kafka.clients.consumer.internals.Fetcher.updateFetchPositions(Fetcher.java:247) at org.apache.kafka.clients.consumer.KafkaConsumer.updateFetchPositions(KafkaConsumer.java:1602) at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1265) at com.linkedin.kafka.clients.consumer.LiKafkaConsumerImpl.position(LiKafkaConsumerImpl.java:403) at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$1.onPartitionsAssigned(KafkaMessageListenerContainer.java:447) at com.linkedin.kafka.clients.consumer.LiKafkaConsumerRebalanceListener.onPartitionsAssigned(LiKafkaConsumerRebalanceListener.java:62) at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:255) at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:339) at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:303) at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:286) at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1030) at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:995) at com.linkedin.kafka.clients.consumer.LiKafkaConsumerImpl.poll(LiKafkaConsumerImpl.java:231) at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:558) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.lang.Thread.run(Thread.java:745)

```

This issue happens because it is the first time for this consumer group to consume messages from this topic, so it tries to use the offset reset policy.

Although I set it to "earliest", it got overridden to "none" by the underlying LinkedIn kafka client

I tried also to override ConsumerRebalanceListener to manually seek to the beginning in this case, but actually it does not come to this point.

The workaround I used here is to use the standard Kafka consumer to seek to the beginning for all partitions as shown bellow

```
@PostConstruct
public void initConsumerOffsets() {
        KafkaConsumer<Long, DocumentEvent> vanillaKafkaConsumer = new KafkaConsumer<>(consumerConfigs());
        List<PartitionInfo> partitionInfos = vanillaKafkaConsumer.partitionsFor(topicName);
        List<TopicPartition> topicPartitions = new ArrayList<>();
        partitionInfos.stream().forEach(p->topicPartitions.add(new TopicPartition(p.topic(), p.partition())));
        vanillaKafkaConsumer.assign(topicPartitions);
        AtomicInteger seekedTopicPartitionCount = new AtomicInteger(0);
        topicPartitions.forEach(t->{
            long position = vanillaKafkaConsumer.position(t);
            if ( position <= 0 ) {
                vanillaKafkaConsumer.seek(t, 0);
                seekedTopicPartitionCount.incrementAndGet();
            }
        });
        if ( seekedTopicPartitionCount.get() > 0 ) {
            vanillaKafkaConsumer.commitSync();
        }
        vanillaKafkaConsumer.close();
        LOGGER.info("Finished initializing consumer offsets, the total number of partitions got offset committed is {}", seekedTopicPartitionCount.get());
    }
```

**Comment by garyrussell** [comment]
@hussein-joe - there's nothing we can really do about this situation (except treat it as a fatal error and stop the container). Even if we catch it when trying to obtain the initial position, the same exception occurs when we poll the client...

```
09:06:34.061 ERROR [delegate-C-1][org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer] Container exception
org.apache.kafka.clients.consumer.NoOffsetForPartitionException: Undefined offset with no reset policy for partition: testTopic3-1
	at org.apache.kafka.clients.consumer.internals.Fetcher.resetOffset(Fetcher.java:369)
	at org.apache.kafka.clients.consumer.internals.Fetcher.resetOffsetsIfNeeded(Fetcher.java:227)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateFetchPositions(KafkaConsumer.java:1592)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1035)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:995)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:488)
```

It appears this is by design; for the `ConsumerConfig`...

```
<li>none: throw exception to the consumer if no previous offset is found for the consumer's group</li>
```

So it seems this is something you should talk to the LinkedIn folks about; to find out why they are forcing the policy to `none`.

**Comment by artembilan** [comment]
The related issue in the LinkedIn https://github.com/linkedin/li-apache-kafka-clients/issues/49
