### ISSUE TITLE
Kafka and Spring Boot JDK 23 - Caused by: java.lang.UnsupportedOperationException: getSubject is supported only if a security manager is allowed

### ISSUE THREAD

**Issue by drakgoku** [spring-projects/spring-kafka#3619]
Can you take a look at this problem with Kafka and Spring Boot JDK 23?
It seems others are stuck for this reason too.
```
java.io.IOException: Channel could not be created for socket java.nio.channels.SocketChannel[closed]
        at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:348) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.common.network.Selector.registerChannel(Selector.java:329) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.common.network.Selector.connect(Selector.java:256) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1052) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:310) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.sendEligibleCalls(KafkaAdminClient.java:1232) ~[kafka-clients-3.7.1.jar:?]     
        at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1492) ~[kafka-clients-3.7.1.jar:?]       
        at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1435) ~[kafka-clients-3.7.1.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator    
        at org.apache.kafka.common.network.SaslChannelBuilder.buildChannel(SaslChannelBuilder.java:239) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:338) ~[kafka-clients-3.7.1.jar:?]
        ... 8 more
Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
Caused by: java.lang.UnsupportedOperationException: getSubject is supported only if a security manager is allowed
        at java.base/javax.security.auth.Subject.getSubject(Subject.java:347) ~[?:?]
        at java.security.sasl/com.sun.security.sasl.ClientFactoryImpl.createSaslClient(ClientFactoryImpl.java:96) ~[?:?]
        at java.security.sasl/javax.security.sasl.Sasl.createSaslClient(Sasl.java:434) ~[?:?]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslClient$0(SaslClientAuthenticator.java:220) ~[kafka-clients-3.7.1.jar:?]
        at java.base/jdk.internal.vm.ScopedValueContainer.callWithoutScope(ScopedValueContainer.java:162) ~[?:?]
        at java.base/jdk.internal.vm.ScopedValueContainer.call(ScopedValueContainer.java:147) ~[?:?]
        at java.base/java.lang.ScopedValue$Carrier.call(ScopedValue.java:420) ~[?:?]
        at java.base/java.lang.ScopedValue.callWhere(ScopedValue.java:568) ~[?:?]
        at java.base/javax.security.auth.Subject.callAs(Subject.java:439) ~[?:?]
        at java.base/javax.security.auth.Subject.doAs(Subject.java:614) ~[?:?]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslClient(SaslClientAuthenticator.java:216) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.<init>(SaslClientAuthenticator.java:207) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.common.network.SaslChannelBuilder.buildClientAuthenticator(SaslChannelBuilder.java:285) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.common.network.SaslChannelBuilder.lambda$buildChannel$1(SaslChannelBuilder.java:228) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.common.network.KafkaChannel.<init>(KafkaChannel.java:143) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.common.network.SaslChannelBuilder.buildChannel(SaslChannelBuilder.java:236) ~[kafka-clients-3.7.1.jar:?]
        at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:338) ~[kafka-clients-3.7.1.jar:?]
        ... 8 more

2024-11-10T02:16:14.631+01:00  WARN 18168 --- [user] [ | user-admin-0] o.a.k.c.NetworkClient                    : [AdminClient clientId=user-admin-0] Error connecting to node 192.168.49.2:9092 (id: -1 rack: null)

```
`This happens because from JDK 17 onwards, the Security Manager is deprecated and in JDK 23 there are significant changes in how security is handled.`

https://github.com/quarkusio/quarkus/issues/39634#issuecomment-2466806266

My version of kafka is Bitnami's:
https://artifacthub.io/packages/helm/bitnami/kafka

Could you please send a request to Kafka to fix the issue as soon as possible? Thanks.

**Comment by artembilan** [comment]
The problem has nothing to do with Spring.
Looks like the concern is directly in Apache Kafka client by itself.
Which we really don't support here.
And we don't contribute to that project from here.
So, closing this as `Nothing to Fix` since really nothing in this project which could help us to mitigate the problem from Spring perspective.

@sobychacko ,

do you have an account in the https://issues.apache.org/jira/projects/KAFKA to help community with reporting this into the proper place?
According to the similar issue in Quarkus people are struggling to reach Apache Kafka team.
Thanks

**Comment by sobychacko** [comment]
@artembilan I do. But, I think its best for individual community members to file an issue directly on Kafka Jira.

**Comment by drakgoku** [comment]
> do you have an account in the https://issues.apache.org/jira/projects/KAFKA to help community with reporting this into the proper place?


If you are not a member of Apache I would say you have to ask the admins.
"[Not a member? To request an account, please contact your Jira administrators.](https://issues.apache.org/jira/secure/Dashboard.jspa)"

I don't have the time

**Comment by postalservice14** [comment]
Here's the issue to watch: https://issues.apache.org/jira/browse/KAFKA-15862
