### ISSUE TITLE
Kafkaconsumer is not safe for multi-threading access

### ISSUE THREAD

**Issue by ayush11-96** [spring-projects/spring-kafka#3655]
**In what version(s) of Spring for Apache Kafka are you seeing this issue?**

For example:

2.8.5

 

**Describe the bug**

 Caused by: java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
 at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2464)
 at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2448)
 at org.apache.kafka.clients.consumer.KafkaConsumer.subscribe(KafkaConsumer.java:950)
 at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.subscribeOrAssignTopics(KafkaMessageListenerContainer.java:1141)
 at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.<init>(KafkaMessageListenerContainer.java:784)
 at org.springframework.kafka.listener.KafkaMessageListenerContainer.doStart(KafkaMessageListenerContainer.java:350)
 at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:466)
 at org.springframework.kafka.listener.ConcurrentMessageListenerContainer.doStart(ConcurrentMessageListenerContainer.java:209)
 at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:466)

**To Reproduce**
During app startup

**Comment by sobychacko** [comment]
`2.8.x` is an older release and out of OSS support. See the support timeline: https://spring.io/projects/spring-kafka#support

Please update to a supported OSS version and see if the problem persists.

**Comment by ayush11-96** [comment]
currently we are on 3.0.1  for some components but still getting the same issues

**Comment by sobychacko** [comment]
Closing the issue due to no recent activity. Please feel free to reopen if needed.
