### ISSUE TITLE
spring-kafka-test doesn't work on Linux

### ISSUE THREAD

**Issue by enisher** [spring-projects/spring-kafka#461]
I stumbled upon very strange issue. I started using sprint-kafka test in my project and it works perfectly fine on my Mac, but when I run the same build on Linux it fails with the TimeoutException.

I was able to reproduce the issue on a tiny project with a single test that I took from the example in the documentation:
- link to the project https://github.com/enisher/spring-kafka-issue
- link to the reference documentation with the example https://docs.spring.io/spring-kafka/docs/2.0.0.RELEASE/reference/html/_reference.html#_example

With no modifications reproduces the behavior of my production build. On my Mac it is green but when I try to build on Linux it fails. 
I tried to build on a newly created AWS EC2 (m4.xlarge) instances with AWS Linux and Ubuntu set ups and the result is the same.

Java version:
openjdk version “1.8.0_131"

The exception:
```
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
13:38:39.350 [DEBUG] [TestEventLogger]         at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
13:38:39.354 [DEBUG] [TestEventLogger]         at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
13:38:39.354 [DEBUG] [TestEventLogger]         at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
13:38:39.354 [DEBUG] [TestEventLogger]         at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:213)
13:38:39.354 [DEBUG] [TestEventLogger]         at org.springframework.kafka.test.rule.KafkaEmbedded.before(KafkaEmbedded.java:213)
13:38:39.354 [DEBUG] [TestEventLogger]         at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
13:38:39.355 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:38:39.355 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:38:39.355 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:38:39.355 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
13:38:39.355 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
13:38:39.355 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:38:39.355 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:38:39.355 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:38:39.355 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
13:38:39.355 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
13:38:39.356 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
13:38:39.356 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
13:38:39.356 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
13:38:39.356 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
13:38:39.356 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
13:38:39.356 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
13:38:39.356 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:748)
13:38:39.356 [DEBUG] [TestEventLogger]
13:38:39.356 [DEBUG] [TestEventLogger]         Caused by:
13:38:39.356 [DEBUG] [TestEventLogger]         org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
13:38:39.356 [DEBUG] [TestEventLogger]
```

I tried to debug and found that when client requests api version of the server the server never gets this request and never responds. But I can’t find out what caused this.

This issue blocks me from starting using spring-kafka in my project. 
Could you help me to figure out how to fix that?

**Comment by artembilan** [comment]
Works well for me on Windows, as well as on our CI Bamboo server: https://build.spring.io/browse/INT-BSP32-42

There is logs like:
```
WRAPPER_OS=linux
...
build	20-Oct-2017 17:58:13	17:58:13.401 [DEBUG] [TestEventLogger] com.smartling.spring.kafka.test.KafkaTest > testTemplate STARTED
build	20-Oct-2017 17:58:13	17:58:13.987 [DEBUG] [TestEventLogger] 
build	20-Oct-2017 17:58:13	17:58:13.987 [DEBUG] [TestEventLogger] com.smartling.spring.kafka.test.KafkaTest > testTemplate STANDARD_OUT
build	20-Oct-2017 17:58:13	17:58:13.987 [DEBUG] [TestEventLogger]     ConsumerRecord(topic = templateTopic, partition = 1, offset = 0, CreateTime = 1508522293943, serialized key size = -1, serialized value size = 3, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = foo)
build	20-Oct-2017 17:58:13	17:58:13.998 [DEBUG] [TestEventLogger]     ConsumerRecord(topic = templateTopic, partition = 0, offset = 0, CreateTime = 1508522293990, serialized key size = 4, serialized value size = 3, headers = RecordHeaders(headers = [], isReadOnly = false), key = 2, value = bar)
build	20-Oct-2017 17:58:14	17:58:14.004 [DEBUG] [TestEventLogger]     ConsumerRecord(topic = templateTopic, partition = 0, offset = 1, CreateTime = 1508522293999, serialized key size = 4, serialized value size = 3, headers = RecordHeaders(headers = [], isReadOnly = false), key = 2, value = baz)
build	20-Oct-2017 17:58:14	17:58:14.009 [DEBUG] [TestEventLogger] 
build	20-Oct-2017 17:58:14	17:58:14.009 [DEBUG] [TestEventLogger] com.smartling.spring.kafka.test.KafkaTest > testTemplate PASSED
```

So, that confirm that we are in a good shape.

However pay attention that I use `--no-daemon` option to run Gradle there.
Maybe that is your bottleneck... 
Also you really show us stack trace after Gradle process. How does it work when you run the test directly in the IDE?

**Comment by enisher** [comment]
Thanks for the quick response.

Well may be the issue is specific to AWS instances. Or I just missing some important configuration...

Here is logs from my laptop:
https://gist.github.com/enisher/b1a2928ac689b7464dc0f6de0f1c3fac#file-spring-kafka-test-issue-macos-logs-L1
And here is logs from freshly launched AWS instance:
https://gist.github.com/enisher/b1a2928ac689b7464dc0f6de0f1c3fac#file-spring-kafka-test-issue-linux-log-L1

After starting the instance, I ran only following commands:
```
yum install java-1.8.0-devel
yum remove java-1.7.0
./gradlew clean build --no-daemon --debug
```

I think the main difference is here:
https://gist.github.com/enisher/b1a2928ac689b7464dc0f6de0f1c3fac#file-spring-kafka-test-issue-macos-logs-L1678
https://gist.github.com/enisher/b1a2928ac689b7464dc0f6de0f1c3fac#file-spring-kafka-test-issue-linux-log-L1502

Looks like on Linux the client never gets the version of the kafka and event sending fails by timeout because of this.

**Comment by garyrussell** [comment]
That is odd; someone else recently had some class path issues on AWS; I don't know what the resolution was.

Try running with the `-verbose` JVM arg and take a look at the class/jar loading messages to make sure the proper client jar (`kafka-clients.jar`) is being used.

**Comment by artembilan** [comment]
> Looks like on Linux the client never gets the version of the kafka and event sending fails by timeout because of this.

How is that related to Spring Kafka? Why are you seeking Apache Kafka support here, but not there?

You should be sure that you really have access there to the ` bootstrap.servers = [127.0.0.1:33419]`. Also someone recently reported the network problem with SASL and something about connection from Kubernetes. But again: all of that out of Spring Kafka scope....

Thanks for understanding

**Comment by artembilan** [comment]
Closing as non-related and without a timely-reasonable response.
