### ISSUE TITLE
producer transactions hanging sometimes

### ISSUE THREAD

**Issue by jorgheymans** [spring-projects/spring-kafka#513]
Hi,

I am trying to get an idea on how producer transactions work for a simple scenario: in a @Transactional service method we send a message to kafa topic and then do a database insert. We make the insert fail and expect that no messages have been sent to kafka. The setup is all on my local machine, zk 3.4.11 with a 2 node kafka 0.11.0.2 cluster, spring-kafka version 2.0.2.RELEASE

What is happening is that most of the times it works:

```
2017-12-11 11:17:33.703 DEBUG 21052 --- [nio-8080-exec-1] o.s.k.t.KafkaTransactionManager          : Creating new transaction with name [tx.TheService.doIt]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT; ''
2017-12-11 11:17:33.712  INFO 21052 --- [nio-8080-exec-1] o.a.k.clients.producer.ProducerConfig    : ProducerConfig values: 
	acks = 1
	batch.size = 16384
	bootstrap.servers = [localhost:9092, localhost:9093]
	buffer.memory = 33554432
	client.id = 
	compression.type = none
	connections.max.idle.ms = 540000
	enable.idempotence = true
	interceptor.classes = null
	key.serializer = class org.apache.kafka.common.serialization.IntegerSerializer
	linger.ms = 1
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 3
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = myID
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer

2017-12-11 11:17:33.721  INFO 21052 --- [nio-8080-exec-1] o.a.k.clients.producer.KafkaProducer     : Instantiated a transactional producer.
2017-12-11 11:17:33.721  INFO 21052 --- [nio-8080-exec-1] o.a.k.clients.producer.KafkaProducer     : Overriding the default max.in.flight.requests.per.connection to 1 since idempontence is enabled.
2017-12-11 11:17:33.722  INFO 21052 --- [nio-8080-exec-1] o.a.k.clients.producer.KafkaProducer     : Overriding the default acks to all since idempotence is enabled.
2017-12-11 11:17:33.739  INFO 21052 --- [nio-8080-exec-1] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 0.11.0.0
2017-12-11 11:17:33.740  INFO 21052 --- [nio-8080-exec-1] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId : cb8625948210849f
2017-12-11 11:17:33.741  INFO 21052 --- [nio-8080-exec-1] o.a.k.c.p.internals.TransactionManager   : [TransactionalId myID] ProducerId set to -1 with epoch -1
2017-12-11 11:17:34.013  INFO 21052 --- [ad | producer-1] o.a.k.c.p.internals.TransactionManager   : [TransactionalId myID] ProducerId set to 8002 with epoch 0
2017-12-11 11:17:34.014 TRACE 21052 --- [nio-8080-exec-1] .s.t.s.TransactionSynchronizationManager : Bound value [org.springframework.kafka.core.KafkaResourceHolder@550e85d3] for key [org.springframework.kafka.core.DefaultKafkaProducerFactory@efbbfef] to thread [http-nio-8080-exec-1]
2017-12-11 11:17:34.014 DEBUG 21052 --- [nio-8080-exec-1] o.s.k.t.KafkaTransactionManager          : Created Kafka transaction on producer [CloseSafeProducer [delegate=org.apache.kafka.clients.producer.KafkaProducer@4d7927b4]]
2017-12-11 11:17:34.014 TRACE 21052 --- [nio-8080-exec-1] o.s.t.i.TransactionInterceptor           : Getting transaction for [tx.TheService.doIt]
sending to kafka
2017-12-11 11:17:34.017 TRACE 21052 --- [nio-8080-exec-1] .s.t.s.TransactionSynchronizationManager : Retrieved value [org.springframework.kafka.core.KafkaResourceHolder@550e85d3] for key [org.springframework.kafka.core.DefaultKafkaProducerFactory@efbbfef] bound to thread [http-nio-8080-exec-1]
2017-12-11 11:17:34.018 TRACE 21052 --- [nio-8080-exec-1] o.s.kafka.core.KafkaTemplate             : Sending: ProducerRecord(topic=heymajo, partition=null, headers=RecordHeaders(headers = [], isReadOnly = false), key=null, value=this is a long message, timestamp=null)
2017-12-11 11:17:34.031 TRACE 21052 --- [nio-8080-exec-1] o.s.kafka.core.KafkaTemplate             : Sent: ProducerRecord(topic=heymajo, partition=null, headers=RecordHeaders(headers = [], isReadOnly = true), key=null, value=this is a long message, timestamp=null)
inserting into database
2017-12-11 11:17:34.035 TRACE 21052 --- [nio-8080-exec-1] o.s.t.i.TransactionInterceptor           : Completing transaction for [tx.TheService.doIt] after exception: org.springframework.dao.InvalidDataAccessApiUsageException: 2 parameters were supplied, but 3 in parameters were declared in class [tx.TheService$Insert]
2017-12-11 11:17:34.035 TRACE 21052 --- [nio-8080-exec-1] o.s.t.i.RuleBasedTransactionAttribute    : Applying rules to determine whether transaction should rollback on org.springframework.dao.InvalidDataAccessApiUsageException: 2 parameters were supplied, but 3 in parameters were declared in class [tx.TheService$Insert]
2017-12-11 11:17:34.035 TRACE 21052 --- [nio-8080-exec-1] o.s.t.i.RuleBasedTransactionAttribute    : Winning rollback rule is: null
2017-12-11 11:17:34.036 TRACE 21052 --- [nio-8080-exec-1] o.s.t.i.RuleBasedTransactionAttribute    : No relevant rollback rule found: applying default rules
2017-12-11 11:17:34.036 DEBUG 21052 --- [nio-8080-exec-1] o.s.k.t.KafkaTransactionManager          : Initiating transaction rollback
org.springframework.kafka.core.KafkaProducerException: Failed to send; nested exception is org.apache.kafka.common.KafkaException: Failing batch since transaction was aborted
	at org.springframework.kafka.core.KafkaTemplate$1.onCompletion(KafkaTemplate.java:330)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:201)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.abort(ProducerBatch.java:156)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortUndrainedBatches(RecordAccumulator.java:642)
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendTransactionalRequest(Sender.java:307)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:204)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:162)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: Failing batch since transaction was aborted
	... 4 more
2017-12-11 11:17:34.041 ERROR 21052 --- [ad | producer-1] o.s.k.support.LoggingProducerListener    : Exception thrown when sending a message with key='null' and payload='this is a long message' to topic heymajo:

org.apache.kafka.common.KafkaException: Failing batch since transaction was aborted
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendTransactionalRequest(Sender.java:307) [kafka-clients-0.11.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:204) [kafka-clients-0.11.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:162) [kafka-clients-0.11.0.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2017-12-11 11:17:34.043 TRACE 21052 --- [nio-8080-exec-1] .s.t.s.TransactionSynchronizationManager : Removed value [org.springframework.kafka.core.KafkaResourceHolder@550e85d3] for key [org.springframework.kafka.core.DefaultKafkaProducerFactory@efbbfef] from thread [http-nio-8080-exec-1]
2017-12-11 11:17:34.051 ERROR 21052 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessApiUsageException: 2 parameters were supplied, but 3 in parameters were declared in class [tx.TheService$Insert]] with root cause

org.springframework.dao.InvalidDataAccessApiUsageException: 2 parameters were supplied, but 3 in parameters were declared in class [tx.TheService$Insert]
	at org.springframework.jdbc.object.RdbmsOperation.validateParameterCount(RdbmsOperation.java:429) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.object.RdbmsOperation.validateParameters(RdbmsOperation.java:390) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.object.SqlUpdate.update(SqlUpdate.java:167) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.object.SqlUpdate.update(SqlUpdate.java:239) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at tx.TheService.doIt(TheService.java:39) ~[classes/:na]
	at tx.TheService$$FastClassBySpringCGLIB$$a8f5dece.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at tx.TheService$$EnhancerBySpringCGLIB$$9b8502b9.doIt(<generated>) ~[classes/:na]
	at tx.MyController.doThis(MyController.java:17) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
```

but sometimes the service method seems to just hang forever, from the thread dump i get this:

```
"http-nio-8080-exec-6" #37 daemon prio=5 os_prio=0 tid=0x0000000021fed800 nid=0x52d4 waiting on condition [0x00000000241bc000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007756ec1b8> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.apache.kafka.clients.producer.internals.TransactionalRequestResult.await(TransactionalRequestResult.java:50)
	at org.apache.kafka.clients.producer.KafkaProducer.abortTransaction(KafkaProducer.java:600)
	at org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer.abortTransaction(DefaultKafkaProducerFactory.java:288)
	at org.springframework.kafka.core.KafkaResourceHolder.rollback(KafkaResourceHolder.java:57)
	at org.springframework.kafka.transaction.KafkaTransactionManager.doRollback(KafkaTransactionManager.java:172)
```

when i then launch another concurrent request (while the first one is still 'hanging') i get this:

```
2017-12-11 11:22:57.305 DEBUG 21052 --- [nio-8080-exec-7] o.s.k.t.KafkaTransactionManager          : Creating new transaction with name [tx.TheService.doIt]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT; ''
2017-12-11 11:22:57.306 ERROR 21052 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not create Kafka transaction; nested exception is org.apache.kafka.common.KafkaException: TransactionalId myID: Invalid transition attempted from state ABORTING_TRANSACTION to state IN_TRANSACTION] with root cause

org.apache.kafka.common.KafkaException: TransactionalId myID: Invalid transition attempted from state ABORTING_TRANSACTION to state IN_TRANSACTION
	at org.apache.kafka.clients.producer.internals.TransactionManager.transitionTo(TransactionManager.java:497) ~[kafka-clients-0.11.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.TransactionManager.transitionTo(TransactionManager.java:491) ~[kafka-clients-0.11.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.TransactionManager.beginTransaction(TransactionManager.java:185) ~[kafka-clients-0.11.0.0.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.beginTransaction(KafkaProducer.java:546) ~[kafka-clients-0.11.0.0.jar:na]

```
I get the impression that if i wait long enough (30+ seconds?) between invocations, it always works.

**Comment by jorgheymans** [comment]
here is the javaconfig for my sample app, all pretty standard AFAICT:

```
@Configuration
@EnableKafka
public class KafkaConfig {

  @Bean
  public ProducerFactory<Integer, byte[]> producerFactory() {
    DefaultKafkaProducerFactory<Integer, byte[]> factory = new DefaultKafkaProducerFactory<>(
        producerConfigs());
    factory.setTransactionIdPrefix("myID");
    return factory;
  }

  @Bean
  public Map<String, Object> producerConfigs() {
    Map<String, Object> props = new HashMap<>();
    props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092,localhost:9093");
    props.put(ProducerConfig.RETRIES_CONFIG, 3);
    props.put(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, true);
    props.put(ProducerConfig.BATCH_SIZE_CONFIG, 16384);
    props.put(ProducerConfig.LINGER_MS_CONFIG, 1);
    props.put(ProducerConfig.BUFFER_MEMORY_CONFIG, 33554432);
    props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, IntegerSerializer.class);
    props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
    return props;
  }

  @Bean
  public KafkaTemplate<Integer, byte[]> kafkaTemplate() {
    return new KafkaTemplate<>(producerFactory());
  }

  @Bean
  KafkaTransactionManager kafkaTransactionManager() {
    return new KafkaTransactionManager(producerFactory());
  }
}
```

the service method

```
  @Transactional
  public void doIt() {
    System.out.println("sending to kafka");
    ListenableFuture send = kafkaTemplate.send("test-topic", "this is a long message");
    send.addCallback(new ListenableFutureCallback() {
      @Override
      public void onFailure(Throwable ex) {
        ex.printStackTrace();
      }

      @Override
      public void onSuccess(Object result) {
        System.out.println(result);
      }
    });
    System.out.println("inserting into database");
    new Insert(dataSource).update("ABC", "DEF");
  }

```

**Comment by garyrussell** [comment]
See https://github.com/spring-projects/spring-kafka/issues/514#issuecomment-350805546

**Comment by garyrussell** [comment]
I am not familiar with this problem; I suggest you explore the [producer configuration properties](https://kafka.apache.org/documentation/).

**Comment by jorgheymans** [comment]
Trying to narrow down the problem, I created a one node setup: 1 kafka and 1 zk instance. Using kafka 1.0 with spring-kafka 2.1.0.RELEASE. I removed the transaction rollback, so really all i am trying to do is send a message to kafka transactionally. I don't know how to make this more basic.

```
  @Transactional
  public void doIt() {
    kafkaTemplate.send(Application.TOPIC, "the message");
  }
```

But the same problem occurs :/

When enabling debug logging on the kafka side, i see that upon invoking the service method for the second time, Kafka starts spamming this in the logs:

```
[2017-12-12 12:36:26,142] DEBUG [TransactionCoordinator id=444] Returning CONCURRENT_TRANSACTIONS error code to client for myTxId0's AddPartitions request (kafka.coordinator.transaction.TransactionCoordinator)
[2017-12-12 12:36:26,169] DEBUG [TransactionCoordinator id=444] Returning CONCURRENT_TRANSACTIONS error code to client for myTxId0's AddPartitions request (kafka.coordinator.transaction.TransactionCoordinator)
[2017-12-12 12:36:26,196] DEBUG [TransactionCoordinator id=444] Returning CONCURRENT_TRANSACTIONS error code to client for myTxId0's AddPartitions request (kafka.coordinator.transaction.TransactionCoordinator)
[2017-12-12 12:36:26,223] DEBUG [TransactionCoordinator id=444] Returning CONCURRENT_TRANSACTIONS error code to client for myTxId0's AddPartitions request (kafka.coordinator.transaction.TransactionCoordinator)
[2017-12-12 12:36:26,250] DEBUG [TransactionCoordinator id=444] Returning CONCURRENT_TRANSACTIONS error code to client for myTxId0's AddPartitions request (kafka.coordinator.transaction.TransactionCoordinator)
[2017-12-12 12:36:26,278] DEBUG [TransactionCoordinator id=444] Returning CONCURRENT_TRANSACTIONS error code to client for myTxId0's AddPartitions request (kafka.coordinator.transaction.TransactionCoordinator)
[2017-12-12 12:36:26,305] DEBUG [TransactionCoordinator id=444] Returning CONCURRENT_TRANSACTIONS error code to client for myTxId0's AddPartitions request (kafka.coordinator.transaction.TransactionCoordinator)
[2017-12-12 12:36:26,332] DEBUG [TransactionCoordinator id=444] Returning CONCURRENT_TRANSACTIONS error code to client for myTxId0's AddPartitions request (kafka.coordinator.transaction.TransactionCoordinator)
```

**Comment by jorgheymans** [comment]
drats, the issue was because i was using Windows. Don't use it for transaction testing: https://github.com/apache/kafka/pull/3283 

>At this point the producer received a response to its abort message, so it considers the transaction aborted and moves on to begin a new transaction. That new transaction will hang and continuously retry with CONCURRENT_TRANSACTIONS errors because the broker hasn't actually finished aborting the previous transaction.
