### ISSUE TITLE
transactional messages sent even tx is rolled back

### ISSUE THREAD

**Issue by jorgheymans** [spring-projects/spring-kafka#514]
Hi,

Following the issue #513 , i also noticed that in some cases the messages are sent to the kafka topic even though they should not. The output i get in this case is this:

```
2017-12-11 11:40:54.910  INFO 20764 --- [nio-8080-exec-1] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId : cb8625948210849f
2017-12-11 11:40:54.911  INFO 20764 --- [nio-8080-exec-1] o.a.k.c.p.internals.TransactionManager   : [TransactionalId myID] ProducerId set to -1 with epoch -1
2017-12-11 11:40:55.184  INFO 20764 --- [ad | producer-1] o.a.k.c.p.internals.TransactionManager   : [TransactionalId myID] ProducerId set to 8003 with epoch 0
2017-12-11 11:40:55.185 TRACE 20764 --- [nio-8080-exec-1] .s.t.s.TransactionSynchronizationManager : Bound value [org.springframework.kafka.core.KafkaResourceHolder@7baa4161] for key [org.springframework.kafka.core.DefaultKafkaProducerFactory@79c8e442] to thread [http-nio-8080-exec-1]
2017-12-11 11:40:55.185 DEBUG 20764 --- [nio-8080-exec-1] o.s.k.t.KafkaTransactionManager          : Created Kafka transaction on producer [CloseSafeProducer [delegate=org.apache.kafka.clients.producer.KafkaProducer@6c03d517]]
2017-12-11 11:40:55.185 TRACE 20764 --- [nio-8080-exec-1] o.s.t.i.TransactionInterceptor           : Getting transaction for [tx.TheService.doIt]
sending message to kafka: this is the message 1512988855188
2017-12-11 11:40:55.188 TRACE 20764 --- [nio-8080-exec-1] .s.t.s.TransactionSynchronizationManager : Retrieved value [org.springframework.kafka.core.KafkaResourceHolder@7baa4161] for key [org.springframework.kafka.core.DefaultKafkaProducerFactory@79c8e442] bound to thread [http-nio-8080-exec-1]
2017-12-11 11:40:55.189 TRACE 20764 --- [nio-8080-exec-1] o.s.kafka.core.KafkaTemplate             : Sending: ProducerRecord(topic=heymajo, partition=null, headers=RecordHeaders(headers = [], isReadOnly = false), key=null, value=this is the message 1512988855188, timestamp=null)
2017-12-11 11:40:55.222 TRACE 20764 --- [nio-8080-exec-1] o.s.kafka.core.KafkaTemplate             : Sent: ProducerRecord(topic=heymajo, partition=null, headers=RecordHeaders(headers = [], isReadOnly = true), key=null, value=this is the message 1512988855188, timestamp=null)
inserting into database
2017-12-11 11:40:55.227 TRACE 20764 --- [nio-8080-exec-1] o.s.t.i.TransactionInterceptor           : Completing transaction for [tx.TheService.doIt] after exception: org.springframework.dao.InvalidDataAccessApiUsageException: 2 parameters were supplied, but 3 in parameters were declared in class [tx.TheService$Insert]
2017-12-11 11:40:55.227 TRACE 20764 --- [nio-8080-exec-1] o.s.t.i.RuleBasedTransactionAttribute    : Applying rules to determine whether transaction should rollback on org.springframework.dao.InvalidDataAccessApiUsageException: 2 parameters were supplied, but 3 in parameters were declared in class [tx.TheService$Insert]
2017-12-11 11:40:55.227 TRACE 20764 --- [nio-8080-exec-1] o.s.t.i.RuleBasedTransactionAttribute    : Winning rollback rule is: null
2017-12-11 11:40:55.227 TRACE 20764 --- [nio-8080-exec-1] o.s.t.i.RuleBasedTransactionAttribute    : No relevant rollback rule found: applying default rules
2017-12-11 11:40:55.227 DEBUG 20764 --- [nio-8080-exec-1] o.s.k.t.KafkaTransactionManager          : Initiating transaction rollback
org.springframework.kafka.support.SendResult@6ca4a48b
2017-12-11 11:40:55.254 TRACE 20764 --- [nio-8080-exec-1] .s.t.s.TransactionSynchronizationManager : Removed value [org.springframework.kafka.core.KafkaResourceHolder@7baa4161] for key [org.springframework.kafka.core.DefaultKafkaProducerFactory@79c8e442] from thread [http-nio-8080-exec-1]
2017-12-11 11:40:55.265 ERROR 20764 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessApiUsageException: 2 parameters were supplied, but 3 in parameters were declared in class [tx.TheService$Insert]] with root cause

org.springframework.dao.InvalidDataAccessApiUsageException: 2 parameters were supplied, but 3 in parameters were declared in class [tx.TheService$Insert]
	at org.springframework.jdbc.object.RdbmsOperation.validateParameterCount(RdbmsOperation.java:429) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.object.RdbmsOperation.validateParameters(RdbmsOperation.java:390) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.object.SqlUpdate.update(SqlUpdate.java:167) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.object.SqlUpdate.update(SqlUpdate.java:239) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at tx.TheService.doIt(TheService.java:40) ~[classes/:na]
	at tx.TheService$$FastClassBySpringCGLIB$$a8f5dece.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at tx.TheService$$EnhancerBySpringCGLIB$$e9f7111b.doIt(<generated>) ~[classes/:na]
	at tx.MyController.doThis(MyController.java:17) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.23.jar:8.5.23]
```

**Comment by garyrussell** [comment]
Consumers can receive uncommitted messages by default; see `isolation.level` in the [Kafka docs](https://kafka.apache.org/documentation/).

**Comment by jorgheymans** [comment]
indeed, missed the isolation.level setting thanks for pointing it out.
