### ISSUE TITLE
Kafka dependency version 1.0.x : missing class to launch tests

### ISSUE THREAD

**Issue by HeleneLevry** [spring-projects/spring-kafka#562]
When I use spring-kafka 2.1.x, I cannot launch any embedded tests due an error when I initialise the Class Rule with : 
@ClassRule
public static KafkaEmbedded embeddedKafka = new KafkaEmbedded(1, true, TEMPLATE_TOPIC);

I have the error : 
java.lang.NoClassDefFoundError: org/apache/kafka/common/security/auth/SecurityProtocol
	at kafka.utils.TestUtils$.createBrokerConfig(TestUtils.scala:220)
	at kafka.utils.TestUtils.createBrokerConfig(TestUtils.scala)
	at org.springframework.kafka.test.rule.KafkaEmbedded.before(KafkaEmbedded.java:187)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.security.auth.SecurityProtocol
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more

When I add the dependency for Kafka 1.0.0, the error change to : 
java.lang.NoClassDefFoundError: org/apache/kafka/common/protocol/SecurityProtocol
	at kafka.server.KafkaConfig$.<init>(KafkaConfig.scala:567)
	at kafka.server.KafkaConfig$.<clinit>(KafkaConfig.scala)
	at kafka.utils.TestUtils$.createBrokerConfig(TestUtils.scala:233)
	at kafka.utils.TestUtils.createBrokerConfig(TestUtils.scala)
	at org.springframework.kafka.test.rule.KafkaEmbedded.before(KafkaEmbedded.java:187)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.protocol.SecurityProtocol
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

I have those errors only when the embedded Kafka is in 1.0.0 version. In previous version of spring-kafka (2.0.x or under), the embedded version of Kafka is 0.11.0.x or under and my tests are working fine.

Thanks in advance.

**Comment by garyrussell** [comment]
The `SecurityProtocol` class was moved from `org.apache.kafka.common.protocol` (in 0.11.0.x) to `org.apache.kafka.common.security.auth`.

The old class is being referenced by the kafka server...

>at kafka.server.KafkaConfig$.(KafkaConfig.scala:567)

So it seems like you still have the `kafka_2.11-0.11.0.x` jar on the classpath.

Perhaps you haven't changed the version of `spring-kafka-test` to 2.1.x?

**Comment by HeleneLevry** [comment]
Thanks for the answer !

For those who have the same issue, here is the solution. 

To use spring-kafka 2.1.x or higher, use this dependency : 
!-- spring-kafka -->
<dependency>
    <groupId>org.springframework.kafka</groupId>
    <artifactId>spring-kafka</artifactId>
    <version>2.1.x.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.springframework.kafka</groupId>
    <artifactId>spring-kafka-test</artifactId>
    <version>2.1.x.RELEASE</version>
    <scope>test</scope>
</dependency>

If you are using spring-kafka 2.1.x, you need to use Kafka 1.0.0. You can find the Kafka Client compatibility on http://projects.spring.io/spring-kafka/. 
You need to use the dependencies for kafka-clients and kafka_2.11 in 1.0.0 version:

<dependency>
	<groupId>org.apache.kafka</groupId>
	<artifactId>kafka-clients</artifactId>
	<version>1.0.0</version>
</dependency>
<dependency>
	<groupId>org.apache.kafka</groupId>
	<artifactId>kafka_2.11</artifactId>
	<version>1.0.0</version>
</dependency>

There is a change of package for some classes between 0.11.0.x and 1.0.0 kafka's versions. Be careful of what version of kafka is compatible with the version of spring-kafka used.
