### ISSUE TITLE
Kafka Listener stop getting messages after sometime

### ISSUE THREAD

**Issue by goyalnitin784** [spring-projects/spring-kafka#638]
HI 

I have integrated spring kafka listener.Code written inside my listener takes more than 1 minute to process a single record.After Some time,messages stop coming to listener.When I ran my application in  spring package info loglevel I found below mentioned logs:

```
partitions revoked:[reprice-topic-0, reprice-topic-1, reprice-topic-2]
partitions assigned:[]
```

I have written below Code :

```java
package com.yatra.misc.rofl.common.config;

import java.util.HashMap;
import java.util.Map;

import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.kafka.annotation.EnableKafka;
import org.springframework.kafka.config.ConcurrentKafkaListenerContainerFactory;
import org.springframework.kafka.config.KafkaListenerContainerFactory;
import org.springframework.kafka.core.ConsumerFactory;
import org.springframework.kafka.core.DefaultKafkaConsumerFactory;
import org.springframework.kafka.listener.AbstractMessageListenerContainer;
import org.springframework.kafka.listener.ConcurrentMessageListenerContainer;
import org.springframework.stereotype.Component;

import com.yatra.misc.rofl.reprice.service.impl.RepriceAndRebookKafkaListener;
import com.yatra.platform.commons.property.PropertyManager;

@Component
@EnableKafka
public class KafkaConfig {

    private static final Logger logger = Logger.getLogger(KafkaConfig.class);

    private String bootstrapServers;

    @Value("${reprice.group.id}")
    private String eStreamGroupID;

    @Autowired
    private PropertyManager propertyManager;

    @Bean
    KafkaListenerContainerFactory<ConcurrentMessageListenerContainer<String, String>> kafkaListenerContainerFactory() {
        logger.info("Going to create kafkaListenerContainerFactory");
        ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(consumerFactory());
        factory.setConcurrency(1);
        factory.getContainerProperties().setPollTimeout(3000);
        factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.MANUAL_IMMEDIATE);
        return factory;
    }

    @Bean
    public ConsumerFactory<String, String> consumerFactory() {
        logger.info("going to create consumerFactory");
        return new DefaultKafkaConsumerFactory<>(consumerConfigs());
    }

    @Bean
    public Map<String, Object> consumerConfigs() {
        Map<String, Object> propsMap = new HashMap<>();

        bootstrapServers = propertyManager.getProperty("bootstrap.servers");
        propsMap.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
        propsMap.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false);
        propsMap.put(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, "100");
        propsMap.put(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, "15000");
        propsMap.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        propsMap.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        propsMap.put(ConsumerConfig.GROUP_ID_CONFIG, eStreamGroupID);
        propsMap.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        logger.info("kafka consumer loaded with properties : " + propsMap);
        return propsMap;
    }

    @Bean
    public RepriceAndRebookKafkaListener repriceAndRebookKafkaListener() {
        return new RepriceAndRebookKafkaListener();
    }


}


@KafkaListener(id = "reprice0", group = "rofl-group", topicPattern = "reprice-topic")
	public void listenPartition0(ConsumerRecord<String, String> msgg, Acknowledgment ack) {
		TenantKeeper.setTenant("roflint");
		try{
			
			ack.acknowledge();
                      //here is the code which takes more than 1 minute to execute.
		}catch (Exception e){
			
		}
	}
```

**Comment by cemo** [comment]
It might be better to have a thread dump when consuming stops.

**Comment by garyrussell** [comment]
Also turn on DEBUG logging to see consumer polling activity - if you don't see polling, the consumer thread is "stuck" someplace.

**Comment by garyrussell** [comment]
See `max.poll.interval.ms` (which defaults to 5 minutes) [here](https://kafka.apache.org/documentation/).

If you take 1 minute to process a record and more than 5 records were fetched, the broker thinks your consumer is dead.

**Comment by brijanresilinc** [comment]
Hi i am facing similar issue 
after this log 
 Sending metadata request {topics=[xyz]} to node 0
updated cluster metadata version 268 to Cluster(nodes = [kafka1.xyz.com:9092 (id: 0 rack: null)], partitions = [Partition(topic = xyz, partition = 0, leader = none, replicas = [1,], isr = []])
i could see the value leader none causing problem

**Comment by CarloMendola** [comment]
Hi,
same issue here. I have a project with 2 @KafkaListener and after some time one of the 2 listener stop to receive messages. As soon as the kafka consumer stop consuming messages a cpu leak starts. 
Sometimes after a while the listener restarts and sometimes doesn't.
When it restarts on its own, i found in the logs the following trace:

> [2018-04-20T09:26:15,949] [ERROR] org.springframework.kafka.listener.LoggingErrorHandler:37 - Error while processing: null -  -
org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:722) ~[kafka-clients-1.0.1.jar!/:?]
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:600) ~[kafka-clients-1.0.1.jar!/:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1250) ~[kafka-clients-1.0.1.jar!/:?]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.commitIfNecessary(KafkaMessageListenerContainer.java:1327) ~[spring-kafka-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.processCommits(KafkaMessageListenerContainer.java:1188) [spring-kafka-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:688) [spring-kafka-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by garyrussell** [comment]
@CarloMendola What version are you using? I recommend upgrading to at least 1.3.4 (current release is 2.1.5). 1.3.x introduced a much simpler threading model thanks to KIP-62.

**Comment by larsduelfer** [comment]
Hi there, while testing our consumer, we are simulating a connection failure to the broker by cutting the connection with local firewall rules in linux. When the connection is cut, we receive the following logs

```
2018-04-25 19:45:31.698 TRACE 23808 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=activities-service-eventprocessing] Sending OffsetCommit request with {csm.projectmanagement.project-2=OffsetAndMetadata{offset=2500, metadata=''}} to coordinator broker:9092 (id: 2147483646 rack: null)
2018-04-25 19:45:41.707  INFO 23808 --- [eventprocessing] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=activities-service-eventprocessing] Group coordinator broker:9092 (id: 2147483646 rack: null) is unavailable or invalid, will attempt rediscovery
```

When the connection is established again, we receive the following logs:

```
2018-04-25 19:56:15.874  INFO 23808 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupIdactivities-service-eventprocessing] Discovered group coordinator broker:9092 (id: 2147483646 rack: null)
2018-04-25 19:56:15.874 TRACE 23808 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=activities-service-eventprocessing] Sending OffsetCommit request with {csm.projectmanagement.project-2=OffsetAndMetadata{offset=2500, metadata=''}} to coordinator broker:9092 (id: 2147483646 rack: null)
2018-04-25 19:56:15.876 ERROR 23808 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=activities-service-eventprocessing] Offset commit failed on partition csm.projectmanagement.project-2 at offset 2500: The coordinator is not aware of this member.
```
It obviously tries to commit the last offset again but does not succeed. That sound like a similar problem.

We are using Spring Kafka 2.1.4 and configured a Consumer Factory with a SeekToCurrentErrorHandler and a RetryTemplate. Furthermore, we manually acknowledge the processed records and use ackMode MANUAL, where the commit is actually send to Kafka at the last record of the currently processed set of records. The commit is done synchroniously.

Errors that occur while processing the messages in the listener are handled correctly. It is just the scenario described here, when the connection to the broker is lost and the consumer cannot commit the offset that the reconnection does not work properly.  

Do you have any idea if we are missing something here? I would also have expected to get error log messages, when the connection to the broker is lost and a reconnection failed after a certain number of attempts. 

Any ideas / help is highly appreciated. Thanks in advance!

**Comment by garyrussell** [comment]
It's generally better to start a new issue rather than piggy-backing on an existing one.

I believe this is fixed in 2.1.5 by this: https://github.com/spring-projects/spring-kafka/commit/6bd58b2b66f2af172e5a6750b02b43daf83aad24 and this: https://github.com/spring-projects/spring-kafka/commit/b0be198a5833d931ecf65f85ce5f1f579f309c8e#diff-3dc07fec508b7a158b2ed0ba4b48e37c

**Comment by larsduelfer** [comment]
@garyrussell Sorry for that, I was thinking it had something in common. I will try 2.1.5. Thanks a lot so far!

**Comment by larsduelfer** [comment]
I tried now version 2.1.5 and it fixed my problem described above! Thanks!

**Comment by garyrussell** [comment]
Closing due to inactivity.

**Comment by vpshastry-nutanix** [comment]
I'm on 2.13-2.4 and still see this behavior.

**Comment by garyrussell** [comment]
That looks like a kafka version. The versions we are talking about here are spring-kafka versions.

This issue is over 2 years old. 

If you feel there is a problem open a new issue with code configuration and logs.
