### ISSUE TITLE
Spring Kafka Test with scala 2.12

### ISSUE THREAD

**Issue by jdin** [spring-projects/spring-kafka#673]
We could not get working spring-kafka-test in combination with scala 2.12.
It looks like that the problem is in EmbeddedKafka which is dependent only on scala version 2.11.
Do you guys have it in your roadmap to support scala 2.12 as well?

**Comment by garyrussell** [comment]
What problems are you having? I just ran the complete test suite with no problems after changing the scala version to 2.12.

```
BUILD SUCCESSFUL in 5m 38s
21 actionable tasks: 21 executed

$ git diff
diff --git a/build.gradle b/build.gradle
index 4f589de..71b4cdc 100644
--- a/build.gradle
+++ b/build.gradle
@@ -78,7 +78,7 @@ subprojects { subproject ->
                kafkaVersion = '1.1.0'
                log4jVersion = '2.11.0'
                mockitoVersion = '2.18.0'
-               scalaVersion = '2.11'
+               scalaVersion = '2.12'
                springRetryVersion = '1.2.2.RELEASE'
                springVersion = '5.1.0.BUILD-SNAPSHOT'
                springDataCommonsVersion = '2.1.0.BUILD-SNAPSHOT'
```


BTW, AFAIK, the Kafka folks still recommend using 2.11: https://kafka.apache.org/quickstart

**Comment by jdin** [comment]
Very strange,

My versions are:
* spring-kafka 2.1.5.RELEASE
* spring-kafka-test 2.1.5.RELEASE
* kafka_2.12 1.1.0
* kafka_2.12 1.1.0-test

My exception stacktrace is:

```
java.lang.NoClassDefFoundError: org/apache/kafka/common/utils/MockTime

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.springframework.kafka.test.rule.KafkaEmbedded.<clinit>(KafkaEmbedded.java:100)
	...
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.utils.MockTime
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
```

	
class `MockTime` exists but the package is `kafka.utils`.

Do we do something wrong?

We will try in a meanwhile to do a sample project to demonstrate it ...

**Comment by artembilan** [comment]
`spring-kafka 2.1.5.RELEASE` is not so compatible with Apache Kafka `1.1.0`: https://docs.spring.io/spring-kafka/docs/2.1.5.RELEASE/reference/html/deps-for-11x.html

Maybe you can try to do Scala `2.12` testing against Apache Kafka `1.0.x` ?

**Comment by jdin** [comment]
I am getting similar problem with kafka version 1.0.1 (the rest of deps are the same)

```
java.lang.NoClassDefFoundError: org/apache/kafka/test/TestUtils

	at kafka.utils.TestUtils$.<init>(TestUtils.scala:70)
	at kafka.utils.TestUtils$.<clinit>(TestUtils.scala)
	at kafka.zk.EmbeddedZookeeper.<init>(EmbeddedZookeeper.scala:29)
	at org.springframework.kafka.test.rule.KafkaEmbedded.startZookeeper(KafkaEmbedded.java:365)
	at org.springframework.kafka.test.rule.KafkaEmbedded.before(KafkaEmbedded.java:212)
	at ...
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.test.TestUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
```

The class `TestUtils `exists in `kafka:test` but the package is `kafka.test`, not `org.apache.kafka.test`

**Comment by garyrussell** [comment]
Yes; I was testing on master; it works on 2.1.x with 1.0.1 but not 1.1.0.

I'll take a look but can't make any guarantees we will support it.

**Comment by jdin** [comment]
Guys, I think you can close this issue, Indeed it just works. We can also confirm it.
The problem was on our side. We were missing kafka-clients:test library.
Thanks a lot for the quick help!

**Comment by garyrussell** [comment]
I was able to get it to work, but I had to comment out the code we added to `KafkaEmbedded` 2.1.5 for the change to the method signature in 1.1.0 for `TestUtils.createBrokerConfig()`. It seems that the additional parameter they added was not aded in the 2.12 version of the jar (:sad:).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>kgh673</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>kgh673</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.1.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<version>1.1.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<version>1.1.0</version>
			<classifier>test</classifier>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka_2.12</artifactId>
			<version>1.1.0</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka_2.12</artifactId>
			<version>1.1.0</version>
			<classifier>test</classifier>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>


</project>
```
We are releasing 2.1.6 today; I will change the check to be non-fatal so that it will work with both versions of the jar.

**Comment by jdin** [comment]
Just saw your comment :) We did not face your findings. So if needed you can reopen the issue.

**Comment by david-romero** [comment]
Thank you so much @artembilan!  Your previous comment has saved me the afternoon :smile: 
I'm using `spring-kafka-test 2.1.7.RELEASE` and `kafka-streams 1.1.0` and I wasn't able to run my tests.
