### ISSUE TITLE
Spring-kafka-test:1.3.5.RELEASE doesn't compatible with kafka-client:1.0.1

### ISSUE THREAD

**Issue by makcpop** [spring-projects/spring-kafka#682]
Hi!
In our project we use spring-kafka-test:1.3.5.RELEASE and kafka-client:1.0.1. I found that these versions should be compatible(in documentation), but I faced the following issue.

I use KafkaEmbedded in tests, and when test is running, I receive an exception: 

`java.lang.NoClassDefFoundError: org/apache/kafka/common/protocol/SecurityProtocol
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.springframework.kafka.test.rule.KafkaEmbedded.createProperties(KafkaEmbedded.java:223)
	at org.springframework.kafka.test.rule.KafkaEmbedded.before(KafkaEmbedded.java:191)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.protocol.SecurityProtocol
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
`

I looked through it and found out that SecurityProtocol was moved and now the current import path in KafkaEmbedded is wrong. In spring-kafka-test:2.0.x generics for scala.Option in method KafkaEmbedded was deleted and it can fix the issue. I tried to do it, but TestUtils.createBrokerConfig doesn't compile with no generics scala.Option arguments.

Could you please look through it?

**Comment by artembilan** [comment]
Please, read this for the compatibility configuration trick: https://docs.spring.io/spring-kafka/docs/2.1.6.RELEASE/reference/html/deps-for-11x.html.

Of course, use there your required Apache Kafka version `1.0.1`.

**Comment by garyrussell** [comment]
Note that 1.3.x is NOT compatible with 1.1.0, but with those overrides you can use it with 1.0.1.

We will add a similar section to the 1.3.x documentation.
