### ISSUE TITLE
kafka consumer in the container  stopped get message from broker at sometime 

### ISSUE THREAD

**Issue by arebya** [spring-projects/spring-kafka#718]
Consumer just stop to get message with no error log.The topic has 6 partitions,only 2 partitions with lags from some time and don't change any more.  The version of spring-kafka is 1.3.3.RELEASE.How can I find the problem and solve it ?

**Comment by indraneelb1903** [comment]
I think you will need to provide more information. A minimal verifiable sample would be helpful.

**Comment by garyrussell** [comment]
You should also look in the logs (client and server) and take a thread dump to see what the container threads are doing.

**Comment by arebya** [comment]
Thank you for your answers.
Container thread dump here:
```
"*****-0-C-1" #138 prio=5 os_prio=0 tid=0x00007f4933d00000 nid=0x1ba runnable [0x00007f47d5045000]                                                                                                      
   java.lang.Thread.State: RUNNABLE                                                                                                                                                                                      
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)                                                                                                                                                         
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)                                                                                                                                                 
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)                                                                                                                                              
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)                                                                                                                                                 
        - locked <0x00000000c49adb08> (a sun.nio.ch.Util$2)                                                                                                                                                              
        - locked <0x00000000c49adaf0> (a java.util.Collections$UnmodifiableSet)                                                                                                                                          
        - locked <0x00000000c47000a0> (a sun.nio.ch.EPollSelectorImpl)                                                                                                                                                   
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)                                                                                                                                                          
        at org.apache.kafka.common.network.Selector.select(Selector.java:527)                                                                                                                                            
        at org.apache.kafka.common.network.Selector.poll(Selector.java:321)                                                                                                                                              
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:432)                                                                                                                                           
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232)                                                                                                        
        - locked <0x00000000c48ecc98> (a org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient)                                                                                                              
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:208)                                                                                                        
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1096)                                                                                                                             
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1043)                                                                                                                                 
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:622)                                                                                 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                                                                                       
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                                      
        at java.lang.Thread.run(Thread.java:745) 

```
The  consumer group(6 consumers online) has listened about 300+ topics ,the consume work is just some database retryable operations. While we use BatchAcknowledgingMessageListener,the config items :
session.timeout.ms=15000ms,
kafka.max.poll.records=100,
max.poll.interval.ms=300000ms

**Comment by garyrussell** [comment]
That looks fine, the thread is waiting in the consumer normally; do you see anything in the logs - e.g. about topic/partition assignment/revocation?

You might need to enable DEBUG logging.

**Comment by arebya** [comment]
I enabled DEBUG logging ,found nothing except Fetcher request log 、heartbeat request log、commit offset log

**Comment by garyrussell** [comment]
You should direct this question to the Kafka folks; it appears to have nothing to do with Spring.

**Comment by arebya** [comment]
Ok.Thank you for your comments! I will close it!

**Comment by yanliqing** [comment]
Did you solved this problem? I hava same problem too.
