### ISSUE TITLE
failing deserialization causes unexpected behaviour in `SeekToCurrentErrorHandler`

### ISSUE THREAD

**Issue by michaelkuechler** [spring-projects/spring-kafka#795]
spring-kafka provides nice functionality to directly deserialize/convert the kafka message to the required type (e.g. `CustomMessageType`). however: if this deserialization fails (e.g. on emtpy kafka-message; see below*), the `SeekToCurrentErrorHandler` in particular has unexpected behaviour: instead of seeking current offset, its essentially doing a no-op, because passed `List<ConsumerRecord<?, ?>> records` is empty (remember: deserialization of the kafka message to 
`ConsumerRecord<?, CustomMessageType>` failed…).

*expected behaviour:* on error, the handler sets the offset past the failing message.

*example:* (with spring-kafka:2.1.8)
```
// configuration
	@Bean
	public ConcurrentKafkaListenerContainerFactory<String, CustomMessageType> myContainerFactory(ConsumerFactory<String, CustomMessageType> consumerFactory) {
		ConcurrentKafkaListenerContainerFactory<String, CustomMessageType> factory = new ConcurrentKafkaListenerContainerFactory<>();
		factory.setConsumerFactory(consumerFactory);
		factory.getContainerProperties().setErrorHandler(new SeekToCurrentErrorHandler()
//			{ // copy of super
//				public void handle(Exception thrownException, List<ConsumerRecord<?, ?>> records, Consumer<?, ?> consumer, MessageListenerContainer container) {
//					Map<TopicPartition, Long> offsets = new LinkedHashMap<>();
//					// WHY IS "records" EMPTY IF DESERIALIZATION FAILED?! BECAUSE OF THAT, IT WONT SEEK PAST THE RECORD!
//					records.forEach(r -> offsets.computeIfAbsent(
//						new TopicPartition(r.topic(), r.partition()),
//						k -> r.offset()
//					));
//					offsets.forEach(consumer::seek);
//					throw new KafkaException("Seek to current after exception", thrownException);
//				}
//			}
		);
		return factory;
	}

// consumer
	@KafkaListener(topics = TOPIC, containerFactory = "myContainerFactory")
	public void receive(@Payload ConsumerRecord<String, CustomMessageType> record) {
		//...
	}
```

(*)
in my case, conversion is failing in `org.springframework.kafka.support.serializer.JsonDeserializer#deserialize(java.lang.String, byte[])` with `SerializationException` because the reader obtained from `com.fasterxml.jackson.databind.ObjectMapper` fails with ```com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]```

**Comment by garyrussell** [comment]
The deserializer is invoked by Kafka - the error occurs before Spring even gets the data - it's not clear how the error handler is even called in that case; the error handler is only called if your listener throws an exception; please dump a stack trace in your custom handler so we can see where it's called from.

```java
    new RuntimeException(thrownException).printStackTrace();
```

Deserialization problems need to be handled in the `Deserializer` itself. In 2.2. we have added an `ErrorHandlingDeserializer`.

https://docs.spring.io/spring-kafka/docs/2.2.0.M2/reference/html/_reference.html#error-handling-deserializer

**Comment by michaelkuechler** [comment]
```
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition mytopic-4 at offset 5. If needed, please seek past the record to continue consumption.
Caused by: org.apache.kafka.common.errors.SerializationException: Can't deserialize data [[]] from topic [mytopic]
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1355)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:358)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1596)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1234)
	at org.springframework.kafka.support.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:248)
	at org.springframework.kafka.support.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:224)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:923)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$2600(Fetcher.java:93)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1100)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1200(Fetcher.java:949)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:570)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:531)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1178)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1111)
	at brave.kafka.clients.TracingConsumer.poll(TracingConsumer.java:53)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:699)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

-----

> Deserialization problems need to be handled in the Deserializer itself. In 2.2. we have added an ErrorHandlingDeserializer.

that might be an answer… (i.e. "not a problem of that error handler, deal with it in the deserializer"). and it would mean that one has to be very aware of the fundamental difference between these cases.

**Comment by garyrussell** [comment]
Ah, yes, ok, I forgot about this logic - the error handler is being invoked here...

```java
/**
 * Handle exceptions thrown by the consumer outside of message listener
 * invocation (e.g. commit exceptions).
 * @param e the exception.
 */
protected void handleConsumerException(Exception e) {
	try {
		if (!this.isBatchListener && this.errorHandler != null) {
			this.errorHandler.handle(e, Collections.emptyList(), this.consumer,
					KafkaMessageListenerContainer.this);
		}
		else if (this.isBatchListener && this.batchErrorHandler != null) {
			this.batchErrorHandler.handle(e, new ConsumerRecords<K, V>(Collections.emptyMap()), this.consumer,
					KafkaMessageListenerContainer.this);
		}
		else {
			this.logger.error("Consumer exception", e);
		}
	}
	catch (Exception ex) {
		this.logger.error("Consumer exception", ex);
	}
}
```

... the list is empty since the `poll()` failed.

We should have a release candidate of 2.2 out next month, with GA early October. 2.2.0.M2 (milestone) is currently available.

If you can't wait for that; you could use a custom deserializer (which wraps the Json deserializer) that, e.g.,  sets the payload to `null` or some other object that tells your listener that deserialization failed.

**Comment by jiayanguo** [comment]
I am still facing the same issue after added ErrorHandling deserializer2.

`props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, ErrorHandlingDeserializer2.class);
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, ErrorHandlingDeserializer2.class);
        props.put(ErrorHandlingDeserializer2.KEY_DESERIALIZER_CLASS, StringDeserializer.class);
        props.put(ErrorHandlingDeserializer2.VALUE_DESERIALIZER_CLASS, JsonDeserializer.class.getName());
        props.put(JsonDeserializer.VALUE_DEFAULT_TYPE, "com.**");
        props.put(ConsumerConfig.GROUP_ID_CONFIG, groupId);
        props.put(JsonDeserializer.TRUSTED_PACKAGES, "com.**");`

rg.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition IN-VIDEO-PIRequisition-6 at offset 0. If needed, please seek past the record to continue consumption.
Caused by: org.apache.kafka.common.errors.SerializationException: Can't deserialize data [[]] from topic [IN-VIDEO-PIRequisition]
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.9.9.3.jar!/:2.9.9.3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1356) ~[jackson-databind-2.9.9.3.jar!/:2.9.9.3]
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:358) ~[jackson-databind-2.9.9.3.jar!/:2.9.9.3]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1596) ~[jackson-databind-2.9.9.3.jar!/:2.9.9.3]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1234) ~[jackson-databind-2.9.9.3.jar!/:2.9.9.3]
	at org.springframework.kafka.support.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:372) ~[spring-kafka-2.2.9.RELEASE.jar!/:2.2.9.RELEASE]
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1041) ~[kafka-clients-2.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3300(Fetcher.java:110) ~[kafka-clients-2.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1223) ~[kafka-clients-2.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1400(Fetcher.java:1072) ~[kafka-clients-2.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:562) ~[kafka-clients-2.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:523) ~[kafka-clients-2.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1230) ~[kafka-clients-2.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1187) ~[kafka-clients-2.0.1.jar!/:na]
Can't deserialize data [[]] from topic


Any ideas?
