### ISSUE TITLE
JsonDeserializer not supported for both key and value: value is deserialized as key

### ISSUE THREAD

**Issue by Sir4ur0n** [spring-projects/spring-kafka#815]
Spring Boot Parent: 2.0.5.RELEASE
Spring Kafka: 2.1.10.RELEASE (but problem seen since 2.1.6.RELEASE)

Issue: if we use a JsonDeserializer for both the key and the value, in a @KafkaListener, at runtime, the value is incorrectly parsed as the type of the key, thus creating an exception:
`java.lang.ClassCastException: MyKeyType cannot be cast to MyValueType`

The problem is exactly the same as described in #610 which somehow got closed, claiming that it was fixed in 2.1.3.RELEASE.

Repository to reproduce the issue: https://github.com/Sir4ur0n/spring-kafka-error
Launch the main app, then hit http://localhost:8080/

You get this exception:
```
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void foo.bar.Listener.verify(org.apache.kafka.clients.consumer.ConsumerRecord<foo.bar.Key, foo.bar.Record>)' threw exception; nested exception is java.lang.ClassCastException: foo.bar.Key cannot be cast to foo.bar.Record
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:267) ~[spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:80) ~[spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:51) ~[spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1077) [spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1057) [spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:999) [spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:867) [spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:725) [spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
Caused by: java.lang.ClassCastException: foo.bar.Key cannot be cast to foo.bar.Record
	at foo.bar.Listener.verify(Listener.java:15) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181) ~[spring-messaging-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114) ~[spring-messaging-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:48) ~[spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:248) ~[spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	... 10 common frames omitted
```

**Comment by artembilan** [comment]
You have this code there in your application:
```
 @Bean
  ConsumerFactory<Key, Record> employeeMasterDataRecordConsumerFactory() {
    return new DefaultKafkaConsumerFactory<>(
        baseConfig(),
        new JsonDeserializer<>(Key.class),
        new JsonDeserializer<>(Record.class));
  }
```

The problem that by default it uses a `this.typeMapper.setTypePrecedence(useHeadersIfPresent ? TypePrecedence.TYPE_ID : TypePrecedence.INFERRED);`.
So, your local `Key.class` is going to be ignored and the `JavaType javaType = this.typeMapper.toJavaType(headers);` will be called during deserialization. And there we have the logic like this:
```
String typeIdHeader = retrieveHeaderAsString(headers, getClassIdFieldName());
```
Where a default `classIdFieldName` refers to the `public static final String DEFAULT_CLASSID_FIELD_NAME = "__TypeId__";`. Therefore a provided type for value is going to be in charge for deserialization.

What you need is just configure a deserializer for the key like this: `new JsonDeserializer<>(Key.class, false)` to let it to know that headers don't matter.

**Comment by Sir4ur0n** [comment]
Hi,

There's no such constructor taking a boolean in `org.springframework.kafka.support.serializer.JsonDeserializer`. However I found `org.springframework.kafka.support.serializer.JsonDeserializer#setUseTypeMapperForKey` but setting this to `false` doesn't change the problem.
I pushed a second commit to my example repository to showcase the issue, feel free to use it to reproduce.

**Comment by artembilan** [comment]
OK. I see. That ctor has appeared since version `2.2`:
```
/**
 * Construct an instance with the provided target type, and
 * useHeadersIfPresent with a default {@link ObjectMapper}.
 * @param targetType the target type.
 * @param useHeadersIfPresent true to use headers if present and fall back to target
 * type if not.
 * @since 2.2
 */
public JsonDeserializer(Class<T> targetType, boolean useHeadersIfPresent) {
```

Anyway there is a workaround via `Jackson2JavaTypeMapper`:
```
/**
 * Set a customized type mapper.
 * @param typeMapper the type mapper.
 * @since 2.1
 */
public void setTypeMapper(Jackson2JavaTypeMapper typeMapper) {
```

Where you do like this:
```
JsonDeserializer<Key> deserializer = new JsonDeserializer<>(Key.class);
Jackson2JavaTypeMapper typeMapper = new DefaultJackson2JavaTypeMapper();
typeMapper.setTypePrecedence(TypePrecedence.INFERRED);
deserializer.setTypeMapper(typeMapper);
```

**Comment by Sir4ur0n** [comment]
`mvn dependency:tree | grep spring-kafka` -> `org.springframework.kafka:spring-kafka:jar:2.1.10.RELEASE:compile`

There's no such `setTypeMapper` method in Jackson2JavaTypeMapper, but there's one in DefaultJackson2JavaTypeMapper, so I adapted your code.
I tried using the same type mapper for both key and value deserializers, or using different mappers, it never works. I pushed a new commit in https://github.com/Sir4ur0n/spring-kafka-error to showcase the problem.

Did you manage to make it work in my example repository?

**Comment by artembilan** [comment]
I did changes to your sample like these:
```
@Bean("template")
  KafkaTemplate<Key, Record> kafkaTemplate() {
    JsonSerializer<Key> keySerializer = new JsonSerializer<>();
    keySerializer.setUseTypeMapperForKey(true);

    JsonSerializer<Record> valueSerializer = new JsonSerializer<>();

    return new KafkaTemplate<>(
        new DefaultKafkaProducerFactory<>(
            baseConfig(),
            keySerializer,
            valueSerializer));
  }
```
and this:
```
@Bean
  ConsumerFactory<Key, Record> employeeMasterDataRecordConsumerFactory() {
    JsonDeserializer<Key> keyJsonDeserializer = new JsonDeserializer<>(Key.class);
    keyJsonDeserializer.setUseTypeMapperForKey(true);

    JsonDeserializer<Record> recordJsonDeserializer = new JsonDeserializer<>(Record.class);

    return new DefaultKafkaConsumerFactory<>(
        baseConfig(),
        keyJsonDeserializer,
        recordJsonDeserializer);
  }
```

So, essentially you just need to say which (de)serializer is used for `key` or `value`. In that case they populate appropriate headers into the Kafka record: `__TypeId__` is default and when it is `keySerializer.setUseTypeMapperForKey(true);`, the header is `__Key_TypeId__`.
This way deserializers will take a look to the proper headers for type info.

You also can configure serializers do not not populate type headers at all, e.g. `keySerializer.setAddTypeInfo(false);`.
This way deserializers will rely on the provided types.

**Comment by Sir4ur0n** [comment]
Thank you, this seems to work!
