### ISSUE TITLE
ListenerContainerIdleEvent is not published with parent container

### ISSUE THREAD

**Issue by chrismoli** [spring-projects/spring-kafka#878]
Spring Kafka version 2.2.0.RELEASE.
I'm using a ConcurrentKafkaListenerContainerFactory and set concurrency to 1. 
```
        @Bean
	KafkaListenerContainerFactory<ConcurrentMessageListenerContainer<String, String>>  kafkaListenerContainerFactory() {
    	ConcurrentKafkaListenerContainerFactory<String, String> factory =
                                new ConcurrentKafkaListenerContainerFactory<String, String>();
        factory.setConsumerFactory(consumerFactory());
        // acknowledgement after listener completes
        factory.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.RECORD);
        factory.getContainerProperties().setErrorHandler(containerRestartErrorHandler);
        // idle interval
        factory.getContainerProperties().setIdleEventInterval(idleEventInterval);
        // non-responsive configurations
        factory.getContainerProperties().setNoPollThreshold(noPollThreshold);
        factory.setConcurrency(1);
        return factory;
    }
```

And a handler for ListenerContainerIdleEvent. This is trying to stop and start the container at idle event.
```
@EventListener
    public void eventHandler(ListenerContainerIdleEvent event) throws ESPProcessorException {
    	
		MessageListenerContainer container = ((MessageListenerContainer)event.getSource());
		restartContainer(container, this.executor, this.abortRestartTimeoutSeconds, false);
    }
	
    public static synchronized void restartContainer(MessageListenerContainer container, Executor executor, Long abortRestartTimeoutSeconds, boolean restart) {

		LOGGER.info("Stopping container."+ container.getAssignedPartitions());
		executor.execute(() -> container.stop());
		// isRunning is false before the container.stop() waits for listener thread
		int n = 0;
		while (container.isRunning() && n++ < abortRestartTimeoutSeconds) {
			try {
				Thread.sleep(1000);
			}
			catch (InterruptedException e) {
				Thread.currentThread().interrupt();
				break;
			}
		}
		if(container.isRunning()) {
			LOGGER.fatal("Failed to reconnect to Kafka. Triggering system exit.");
			System.exit(1); //non zero value to exit says abnormal termination of JVM
		}

		
		LOGGER.info("Starting container.");
		container.start();
		// wait for container to start 
		n = 0;
		while (!container.isRunning() && n++ < abortRestartTimeoutSeconds) {
			try {
				Thread.sleep(1000);
			}
			catch (InterruptedException e) {
				Thread.currentThread().interrupt();
				break;
			}
		}
		if(!container.isRunning()) {
			LOGGER.fatal("Failed to start container. Triggering system exit.");
			System.exit(1); //non zero value to exit says abnormal termination of JVM
		}
		LOGGER.info("Container started." + container.getAssignedPartitions());

    }
```

But I see it is not the parent container (ConcurrentMessageListenerContainer) passed in the event, but the child container(KafkaMessageListenerContainer). 

```
	private void publishIdleContainerEvent(long idleTime, Consumer<?, ?> consumer, boolean paused) {
		if (getApplicationEventPublisher() != null) {
			getApplicationEventPublisher().publishEvent(new ListenerContainerIdleEvent(
					this, idleTime, getBeanName(), getAssignedPartitions(), consumer, paused));
		}
	}

```

When idle event happens, I see this wired behavior: an exception thrown right after container start, handled by a custom exception handler I added which does the same restart. And in the end I see 2 consumers running. Where as I set concurrency to 1 and it was only 1 at the beginning.
2018-11-16 11:50:48.469  INFO 19644 --- [-listener-0-C-1] c.f.w.e.f.p.e.ConsumerEventListener      : Stopping container.[ESP.QREP-1, ESP.QREP-0, ESP.QREP-7, ESP.QREP-6, ESP.QREP-5, ESP.QREP-4, ESP.QREP-3, ESP.QREP-2]
2018-11-16 11:50:49.471  INFO 19644 --- [-listener-0-C-1] c.f.w.e.f.p.e.ConsumerEventListener      : Starting container.
2018-11-16 11:50:58.476  INFO 19644 --- [-listener-0-C-1] o.a.k.c.c.ConsumerConfig                 : ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = earliest
	bootstrap.servers = [espkfkgtm1.fmr.com:29092, espkfkgtm2.fmr.com:29092, espkfkgtm3.fmr.com:29092]
	check.crcs = true
	client.id = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = esp-listener
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = kafka
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer

2018-11-16 11:50:58.546  INFO 19644 --- [-listener-0-C-1] o.a.k.c.u.AppInfoParser                  : Kafka version : 2.0.0
2018-11-16 11:50:58.546  INFO 19644 --- [-listener-0-C-1] o.a.k.c.u.AppInfoParser                  : Kafka commitId : 3402a8361b734732
2018-11-16 11:50:58.546  INFO 19644 --- [-listener-0-C-1] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 
2018-11-16 11:50:58.566  INFO 19644 --- [-listener-0-C-1] c.f.w.e.f.p.e.ConsumerEventListener      : Container started.null
2018-11-16 11:50:58.567 ERROR 19644 --- [-listener-0-C-1] f.w.e.f.p.e.ContainerRestartErrorHandler : Container error. Restarting container. 

java.lang.NullPointerException: null
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.seekPartitions(KafkaMessageListenerContainer.java:608) [spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:736) [spring-kafka-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

2018-11-16 11:50:58.590  INFO 19644 --- [-listener-0-C-1] c.f.w.e.f.p.e.ConsumerEventListener      : Stopping container.null
2018-11-16 11:50:58.595  INFO 19644 --- [-listener-0-C-2] o.a.k.c.Metadata                         : Cluster ID: hUpyTm5PRGKjQveu0yr-DQ
2018-11-16 11:50:58.596 DEBUG 19644 --- [-listener-0-C-2] essageListenerContainer$ListenerConsumer : Commit list: {}
2018-11-16 11:50:58.597  INFO 19644 --- [-listener-0-C-2] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService
2018-11-16 11:50:58.600  INFO 19644 --- [-listener-0-C-2] essageListenerContainer$ListenerConsumer : Consumer stopped
2018-11-16 11:50:58.601 DEBUG 19644 --- [-listener-0-C-2] o.s.k.l.KafkaMessageListenerContainer    : KafkaMessageListenerContainer [id=esp-listener-0, clientIndex=-0, topicPartitions=none assigned] stopped normally
2018-11-16 11:50:59.592  INFO 19644 --- [-listener-0-C-1] c.f.w.e.f.p.e.ConsumerEventListener      : Starting container.
2018-11-16 11:50:59.593  INFO 19644 --- [-listener-0-C-1] o.a.k.c.c.ConsumerConfig                 : ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = earliest
	bootstrap.servers = [espkfkgtm1.fmr.com:29092, espkfkgtm2.fmr.com:29092, espkfkgtm3.fmr.com:29092]
	check.crcs = true
	client.id = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = esp-listener
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = kafka
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer

2018-11-16 11:50:59.601  INFO 19644 --- [-listener-0-C-1] o.a.k.c.u.AppInfoParser                  : Kafka version : 2.0.0
2018-11-16 11:50:59.601  INFO 19644 --- [-listener-0-C-1] o.a.k.c.u.AppInfoParser                  : Kafka commitId : 3402a8361b734732
2018-11-16 11:50:59.601  INFO 19644 --- [-listener-0-C-1] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 
2018-11-16 11:50:59.602  INFO 19644 --- [-listener-0-C-1] c.f.w.e.f.p.e.ConsumerEventListener      : Container started.null
2018-11-16 11:50:59.631  INFO 19644 --- [-listener-0-C-3] o.a.k.c.Metadata                         : Cluster ID: hUpyTm5PRGKjQveu0yr-DQ
2018-11-16 11:50:59.631  INFO 19644 --- [-listener-0-C-3] o.a.k.c.c.i.AbstractCoordinator          : [Consumer clientId=consumer-3, groupId=esp-listener] Discovered group coordinator espkfkpocpm1.fmr.com:29092 (id: 2147483646 rack: null)
2018-11-16 11:50:59.634  INFO 19644 --- [-listener-0-C-3] o.a.k.c.c.i.ConsumerCoordinator          : [Consumer clientId=consumer-3, groupId=esp-listener] Revoking previously assigned partitions []
2018-11-16 11:50:59.635  INFO 19644 --- [-listener-0-C-3] o.s.k.l.KafkaMessageListenerContainer    : partitions revoked: []
2018-11-16 11:50:59.635 DEBUG 19644 --- [-listener-0-C-3] essageListenerContainer$ListenerConsumer : Commit list: {}
2018-11-16 11:50:59.635  INFO 19644 --- [-listener-0-C-3] o.a.k.c.c.i.AbstractCoordinator          : [Consumer clientId=consumer-3, groupId=esp-listener] (Re-)joining group
2018-11-16 11:51:00.453  INFO 19644 --- [-listener-0-C-1] o.a.k.c.c.i.AbstractCoordinator          : [Consumer clientId=consumer-1, groupId=esp-listener] Attempt to heartbeat failed since group is rebalancing
2018-11-16 11:51:00.454  INFO 19644 --- [-listener-0-C-1] o.a.k.c.c.i.ConsumerCoordinator          : [Consumer clientId=consumer-1, groupId=esp-listener] Revoking previously assigned partitions [ESP.QREP-1, ESP.QREP-0, ESP.QREP-7, ESP.QREP-6, ESP.QREP-5, ESP.QREP-4, ESP.QREP-3, ESP.QREP-2]
2018-11-16 11:51:00.455  INFO 19644 --- [-listener-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : partitions revoked: [ESP.QREP-1, ESP.QREP-0, ESP.QREP-7, ESP.QREP-6, ESP.QREP-5, ESP.QREP-4, ESP.QREP-3, ESP.QREP-2]
2018-11-16 11:51:00.455 DEBUG 19644 --- [-listener-0-C-1] essageListenerContainer$ListenerConsumer : Commit list: {}
2018-11-16 11:51:00.455  INFO 19644 --- [-listener-0-C-1] o.a.k.c.c.i.AbstractCoordinator          : [Consumer clientId=consumer-1, groupId=esp-listener] (Re-)joining group
2018-11-16 11:51:00.466  INFO 19644 --- [-listener-0-C-3] o.a.k.c.c.i.AbstractCoordinator          : [Consumer clientId=consumer-3, groupId=esp-listener] Successfully joined group with generation 36
2018-11-16 11:51:00.467  INFO 19644 --- [-listener-0-C-3] o.a.k.c.c.i.ConsumerCoordinator          : [Consumer clientId=consumer-3, groupId=esp-listener] Setting newly assigned partitions [ESP.QREP-7, ESP.QREP-6, ESP.QREP-5, ESP.QREP-4]
2018-11-16 11:51:00.468  INFO 19644 --- [-listener-0-C-1] o.a.k.c.c.i.AbstractCoordinator          : [Consumer clientId=consumer-1, groupId=esp-listener] Successfully joined group with generation 36
2018-11-16 11:51:00.470  INFO 19644 --- [-listener-0-C-1] o.a.k.c.c.i.ConsumerCoordinator          : [Consumer clientId=consumer-1, groupId=esp-listener] Setting newly assigned partitions [ESP.QREP-1, ESP.QREP-0, ESP.QREP-3, ESP.QREP-2]
2018-11-16 11:51:00.477 DEBUG 19644 --- [-listener-0-C-1] essageListenerContainer$ListenerConsumer : Committing on assignment: {ESP.QREP-1=OffsetAndMetadata{offset=2, metadata=''}, ESP.QREP-0=OffsetAndMetadata{offset=1, metadata=''}, ESP.QREP-3=OffsetAndMetadata{offset=1, metadata=''}, ESP.QREP-2=OffsetAndMetadata{offset=1, metadata=''}}
2018-11-16 11:51:00.483  INFO 19644 --- [-listener-0-C-1] o.s.k.l.KafkaMessageListenerContainer    : partitions assigned: [ESP.QREP-1, ESP.QREP-0, ESP.QREP-3, ESP.QREP-2]
2018-11-16 11:51:00.574 DEBUG 19644 --- [-listener-0-C-3] essageListenerContainer$ListenerConsumer : Committing on assignment: {ESP.QREP-7=OffsetAndMetadata{offset=2, metadata=''}, ESP.QREP-6=OffsetAndMetadata{offset=13, metadata=''}, ESP.QREP-5=OffsetAndMetadata{offset=0, metadata=''}, ESP.QREP-4=OffsetAndMetadata{offset=1, metadata=''}}
2018-11-16 11:51:00.580  INFO 19644 --- [-listener-0-C-3] o.s.k.l.KafkaMessageListenerContainer    : partitions assigned: [ESP.QREP-7, ESP.QREP-6, ESP.QREP-5, ESP.QREP-4]

**Comment by chrismoli** [comment]
@garyrussell Thanks for the fix! Do you know when this will be released?

**Comment by garyrussell** [comment]
2.2.1 is scheduled for Wednesday this week. https://github.com/spring-projects/spring-kafka/milestones
