### ISSUE TITLE
Kafka 2.1.1 - Useless warnings - The configuration 'admin.retries' was supplied but isn't a known config.

### ISSUE THREAD

**Issue by Vity01** [spring-projects/spring-kafka#985]
Spring Kafka 2.2.4, Kafka 2.1
You get a (useless) warnings during startup Spring context.
I didn't define any such property in my app configuration file.

```
2019-03-01 09:54:10.581  WARN [main] --- o.a.k.clients.consumer.ConsumerConfig    : The configuration 'admin.retries' was supplied but isn't a known config.
2019-03-01 09:54:10.689  WARN [main] --- o.a.k.clients.consumer.ConsumerConfig    : The configuration 'admin.retry.backoff.ms' was supplied but isn't a known config.
```

Stacktrace
```
    at org.apache.kafka.common.config.AbstractConfig.logUnused(AbstractConfig.java:287)
    at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:796)
    at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:617)
    at org.apache.kafka.streams.processor.internals.DefaultKafkaClientSupplier.getConsumer(DefaultKafkaClientSupplier.java:44)
    at org.apache.kafka.streams.processor.internals.StreamThread.create(StreamThread.java:668)
    at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:705)
    at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:551)
    at org.springframework.kafka.config.StreamsBuilderFactoryBean.start(StreamsBuilderFactoryBean.java:294)
```

**Comment by artembilan** [comment]
There is nothing what we can do with from this project perspective.
This is really a logic is presented in the Apache Kafka per se.
See their `StreamsConfig.getMainConsumerConfigs()` source code:
```
   // add admin retries configs for creating topics
        final AdminClientConfig adminClientDefaultConfig = new AdminClientConfig(getClientPropsWithPrefix(ADMIN_CLIENT_PREFIX, AdminClientConfig.configNames()));
        consumerProps.put(adminClientPrefix(AdminClientConfig.RETRIES_CONFIG), adminClientDefaultConfig.getInt(AdminClientConfig.RETRIES_CONFIG));
        consumerProps.put(adminClientPrefix(AdminClientConfig.RETRY_BACKOFF_MS_CONFIG), adminClientDefaultConfig.getLong(AdminClientConfig.RETRY_BACKOFF_MS_CONFIG));
```
That's the place where they populate these admin-specific properties into the target `ConsumerConfig`.

I suggest you to raise this concern against Apache Kafka.

Meanwhile closing this one as "Works as Designed".

**Comment by axblu** [comment]
Fyi, there is an issue regarding this problem at Kafka: https://issues.apache.org/jira/browse/KAFKA-6793
